apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: n8n
  name: n8n-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 2Gi
