apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: warehouse-keeper
  namespace: data
spec:
  replicas: 1
  containerTemplate:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  dataVolumeClaimSpec:
    accessModes: ["ReadWriteOnce"]
    storageClassName: longhorn-single-replica
    resources:
      requests:
        storage: 5Gi
