apiVersion: v1
kind: Service
metadata:
  name: clickhouse-lb
  namespace: data
  annotations:
    metallb.io/loadBalancerIPs: 10.10.10.10
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: warehouse-clickhouse
    clickhouse.com/role: clickhouse-server
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: native
      port: 9001
      targetPort: 9001
