apiVersion: v1
kind: Secret
metadata:
    name: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:ujhKa0miRoVDh6wve6t9dfvoBwq4Ibn5Lp/23Er/hbqj7Ooz7P0HcL+k58HcOq7OZIVxaIObZw==,iv:MA/U8zwWuS8q93MKWuOE6w6SwCXo7qng4/BbZAWjilE=,tag:fcnJ55znJGSmr6KMkQfr0g==,type:str]
    postgresql_password: ENC[AES256_GCM,data:GJR/VnX6GaCYFCPXBbNXizDZXY9AuJj6ZITQ+cM7s1+47LXy,iv:hwU79Ag+Bt/X+k1clX/se8oK40fujFGA+lmZYHOg68k=,tag:oH4G7cr1oFYQZQohIkkUPg==,type:str]
    bootstrap_email: ENC[AES256_GCM,data:CE/EooCBlSwcPEVnGlZpaFBF0pdHUle6DooAikE92w==,iv:YsfESJlJOvkWhLRWFcglzls6Q6N73KZhimbuasAKpTU=,tag:4AaCTUJHSgSi67Wd65tieQ==,type:str]
    bootstrap_token: ENC[AES256_GCM,data:Dn20rcpfZdLOrRjvSpF3pnwfHqHLKgWIAPMsAr5Wi1e+xJj4DktnMm7Ip3gb,iv:DGxF9ZBWWqPyp9CNV9GaQeT+C9qiNO1yONRO1LF+E7Y=,tag:0/A3c7vByYT90PqQkl0fRg==,type:str]
    bootstrap_password: ENC[AES256_GCM,data:ic5Z5LiKYUNdM2xwOVZvERzsXF++Brr4G+RhgIwqVy4bn3sb51Aoo5G/,iv:L1vvCqgX93jXn/1a4NP4+bCNnXrjnpYHEADExRoo2V4=,tag:e0n45pOxhhE1GSLXTkTYKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSTJUR29WU0syT0lxYlox
            NE1PbVRxdlp5UXdKTDh1dFpDR0VUNzJ3RERjCmpEN2pBdWdoT29qeFFtelBCS24z
            YXBGYmJSNm5uR2tvVndha2dpK1RLd1UKLS0tIDgwZGtPNFV3UlRRTEpFc1lvVkFj
            dmprQjAvRGZxbWplYjZWZDhTYnJyUmcKkA9HUl7mhCBp7tjDMHIU5xQ5b1imzZwO
            oA828WnFuTQw3Pwl+eKPssCqwY4P1sQnF+egjsRcba/qWyB50fRdUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T06:46:43Z"
    mac: ENC[AES256_GCM,data:J1vxe+V9hu3lDKdq/LpUJAzlDpjfDSnoni/O36D9XTjk42SMb1RJUrXw3puuRVbHrfZRd3mLBWcPCrQfyxvtF2fkv4GtEM56pxZd7dbj7ByP3sH+K4VROIARbQxWN6qnRXMhdwquVg15aeqmK3bAx/BGopWVuc1BykL4tViLOKQ=,iv:iJS4w4XkMj5wmrTxUq3bBqn37ZDFcvmG7Ve8aJEtjyE=,tag:wNC8cKDo1BJDYMOIKY7C7g==,type:str]
    version: 3.13.1
