apiVersion: v1
kind: Secret
metadata:
    name: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:92MqqJ8pTihmZvlnz1ezJocsUSGhVmnY7h+3+oZQU6+oJ3+6s27+OvvXn754fyT54usUYYHLLA==,iv:sZ6OTN9VsrAqY5Ed3dBGiaQx5gJtC+X0OotMp6iFQhQ=,tag:QUl+1lR8ue9mllfIHNqOrQ==,type:str]
    postgresql_password: ENC[AES256_GCM,data:3a/9AZRTVmf6mRMc2YoaFqQfTdBF2WyfXvE6eSYU3zrxkmgu,iv:6hhEs37ogo8JnzUhB8q8sYh6N85WcTA0KEMckMg+JKY=,tag:wRoMKeLb5grfxO1aJrAm5w==,type:str]
    bootstrap_email: ENC[AES256_GCM,data:2Qur6+M/dkVq11fOkZkdQbOrf0NbU/nVz/I7pHK8vg==,iv:rqYTZ2/j6flAFVPndzZ1xaDONvPXWt3EFE6BXZhaj/E=,tag:0ficb5ugU//czkRAzCGzWg==,type:str]
    bootstrap_token: ENC[AES256_GCM,data:KFT6BUiTVnubyLwBm5cFpSJEpMeHl0O/hLKNK4E/zFPE7Kyg71SoDobV6wBY,iv:awWa2qwxZ6QtswBuv78H5NzSahYUGEm5uuOf8nJ2B8o=,tag:buD3KVan+7mNQ5ITMSVS7w==,type:str]
    bootstrap_password: ENC[AES256_GCM,data:Ytq6u2hKpJppQg+MmPRyUNL17Hh4rHs5o5XDnaphgxhC5Gi9qlfIMvj7,iv:K+BBPQsmnx+lqUH/9r9hlOq8auhbtaV1SNVcfieYlME=,tag:AeHK+/H69BneyXv+Zro+NA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXb0lRMVpsbzFWaHNSZGhX
            ZStwR1NjM0xGOXJDbjlreWQvQzJrOVFRVFFnCkFUeUtRM05vcHpLRnVzK3ZKVkdr
            NlNYdFNyYUt0RUVsTzdLMjZQWGgxRGsKLS0tICtZVUo0c0FDcFA0NmRzaGoyTDdM
            am9hZkU2Q0tYQldlWWRiV0dOc0FhajQKrMNP9hVUOHcveQkdgLpaERzdcUeFKxd8
            lJjejhYHDma9MlLYB9J0yhYneziUVrl6hOphX2s5sK2dypaD/KS+3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T06:12:34Z"
    mac: ENC[AES256_GCM,data:hpN16dpW5R2YzVheJ9GgzQ1v2rACnABQMsdpRa31dTp+mhmHuZHSWJ+gNxBSGxUcIs2SG6pVx1fPSCibi4sbMdoy3NZOdwTqMxDaTyMz5TKpmVKSPE8qaMLhFO5+UXSWYkEfpNsEmEepkRY3p1c5y2gWGyj71HyqrnWk0MWIqN0=,iv:3lhUI9ezBLooTHTC+6TAbG3a8aJDc8Csd8gnxmgEAVo=,tag:dUMjbLxKqxwDv9JFGm+dCw==,type:str]
    version: 3.13.1
