apiVersion: v1
kind: Secret
metadata:
    name: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:ZrJEEAwHbgEYIrv3WttOJBCegE1NbvOLz4ugcGSwZAXSEtGhnpD/j/JEcW7dyP4SGLmeMqTvxw==,iv:63zrbic+2qLqdtvB9UjcRuqHvKzNdz0j1K7Z2fuNUiU=,tag:o5EJ+xRHicv8v5dU5nTWsQ==,type:str]
    postgresql_password: ENC[AES256_GCM,data:6+kazQUjGN6pY6X/XLiASp+C7/l9b7wnpnBRHhPBuYqtF1F5,iv:su53bCpgSOxwl8WGupAMp0irtey7bmg7OGFZRijNZqA=,tag:6u3Nm2BO7rwDldxgCPK1lw==,type:str]
    bootstrap_email: ENC[AES256_GCM,data:pIfe6fT8lHD3jKjwjLYrUL7gRbMu50JpKeehGShaWg==,iv:83/rz8USfZy3fUUsgeJPvLVjxQtF4wYiJ9WRmas84wI=,tag:T3wtJ9NGsYLgLX9nGPEmtQ==,type:str]
    bootstrap_token: ENC[AES256_GCM,data:Q9rzVAz7oIdqdDVbiPo3utsATqRqLIssGcPMzW6IGBvdPLusmR/uMmMjzkhd,iv:dmckGBAt79mOTe4G7tGOkBOORFobdC/teHbd9KOodeE=,tag:QBx+k4zBjOnyrHUQpiDb9w==,type:str]
    bootstrap_password: ENC[AES256_GCM,data:qaNdwAOGNJwpBHp38QE4BneIWxO/p7KDQljv+mVPdmSLdzLbkcwcxMEn,iv:k15qhIv0R64I2Jr0l6+pqATWCT/eZ40GVZSFqItJ9eA=,tag:fjYww3B9l/3dcFUybsXTlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycktxK0Z1NllFbkV3cUl6
            ZVVhK0F2UzBpRklDUm82MzlrYXg0TDZZSTE4CmJvWVlHbkpyWkNGeTBkdlFDYzhW
            V1RNaWMxM01lMWkvSFl4RDQvU0VSZUkKLS0tIEthd2JuVGZRZ3laK1d5cFJIL3l6
            VVhraVNPSFg0endPRDZYNzZWeHNRdkkKG7u/0WXWT+8BV8e3PIqAjj7uW8HTkIOK
            eA15NlGI1fXw86pXjzPwTUiR+0jp3Mwvl25n8jXxwr9oewaXvN3vcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-25T02:10:13Z"
    mac: ENC[AES256_GCM,data:einXIz/p8JyUkHR9gKhijWpkxkUOqyr2VegFK1zqmNeVJ5JP9VrUXzAlnaQFArJDYNNF4V9a5NXTF478JcQxWVICvOrWgR2LuoCR4/dSJosd11B/VCLSpYZeuayr0Z7ba5WeFMENNXPPtERQtXFtxOc8tzXtFuHt86zoyfy1/ik=,iv:wkN/MoJH9OdJGRCooNyjJqQNTmQMPYWLCvUqx5fw2bc=,tag:0mk/ZkTsJOK4QBOE9icIiQ==,type:str]
    version: 3.13.1
