apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-settings
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: seerr-settings
    creationPolicy: Owner
  data:
    - secretKey: settings.json
      remoteRef:
        key: seerr/settings.json
