apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-settings
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: seerr-settings
    creationPolicy: Owner
  data:
    - secretKey: config.toml
      remoteRef:
        key: seerr
        property: config.toml
