apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-external-secret
  namespace: cloudflare-ddns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: cloudflare-ddns
    creationPolicy: Owner
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: cloudflare
        property: api_token
    - secretKey: DOMAINS
      remoteRef:
        key: cloudflare
        property: domains
