apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagster
  namespace: data
spec:
  install:
    createNamespace: true
  interval: 1h
  chart:
    spec:
      chart: dagster
      version: 1.13.9
      sourceRef:
        kind: HelmRepository
        name: dagster
  values:
    dagster-user-deployments:
      deployments:
        - name: "k8s-example-user-code-1"
          image:
            repository: "docker.io/dagster/user-code-example"
            tag: "1.13.9"
            pullPolicy: Always
          dagsterApiGrpcArgs:
            - "--python-file"
            - "/deploy_k8s/definitions.py"
          port: 3030
