apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media
  name: ntfy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      containers:
        - name: ntfy
          image: binwiederhier/ntfy
          args:
            - serve
          env:
            - name: NTFY_BASE_URL
              value: http://ntfy.${cluster_domain}
            - name: NTFY_ATTACHMENT_CACHE_DIR
              value: "/var/cache/ntfy/attachments"
            - name: NTFY_UPSTREAM_BASE_URL
              value: "https://ntfy.sh"
            - name: NTFY_AUTH_ACCESS
              value: "*:up*:write-only"
            - name: NTFY_CACHE_FILE
              value: /var/lib/ntfy/cache.db
            - name: NTFY_AUTH_FILE
              value: /var/lib/ntfy/auth.db
            - name: NTFY_BEHIND_PROXY
              value: "true"
            - name: NTFY_ENABLE_LOGIN
              value: "true"
            - name: NTFY_ENABLE_SIGNUP
              value: "true"
          envFrom:
            - secretRef:
                name: ntfy
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 10m
            limits:
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /v1/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /v1/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: /var/lib/ntfy
              name: ntfy-data
            - mountPath: /var/cache/ntfy/attachments
              name: ntfy-attachments
      restartPolicy: Always
      volumes:
        - name: ntfy-data
          persistentVolumeClaim:
            claimName: ntfy-data
        - name: ntfy-attachments
          persistentVolumeClaim:
            claimName: ntfy-attachments
