apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-external-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: ntfy
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ntfy
  refreshInterval: 6h
