apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agregarr-settings
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: agregarr-settings
    creationPolicy: Owner
  data:
    - secretKey: settings.json
      remoteRef:
        key: "op://<vault-name>/agregarr/settings.json"
