apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agregarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn # longhorn-backup
  resources:
    requests:
      storage: 5Gi
