volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    envFrom:
      - secretRef:
          name: autobrr
    #environment:
    #- DB_HOST=${apps_pg_host}
    #- DB_NAME=romm # Should match MARIADB_DATABASE in mariadb
    #- DB_USER=romm-user # Should match MARIADB_USER in mariadb
    #- DB_PASSWD= # Should match MARIADB_PASSWORD in mariadb
    #- ROMM_AUTH_SECRET_KEY= # Generate a key with `openssl rand -hex 32`
    #- SCREENSCRAPER_USER= # These are the recommended metadata providers
    #- SCREENSCRAPER_PASSWORD= # https://docs.romm.app/latest/getting-started/metadata-providers/#screenscraper
    #- RETROACHIEVEMENTS_API_KEY= # https://docs.romm.app/latest/getting-started/metadata-providers/#retroachievements
    #- STEAMGRIDDB_API_KEY= # https://docs.romm.app/latest/getting-started/metadata-providers/#steamgriddb
    #- HASHEOUS_API_ENABLED=true # https://docs.romm.app/latest/getting-started/metadata-providers/#hasheous
    volumes:
      - romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - romm_redis_data:/redis-data # Cached data for background tasks
      - /path/to/library:/romm/library # Your game library. Check https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure for more details.
      - /path/to/assets:/romm/assets # Uploaded saves, states, etc.
      - /path/to/config:/romm/config # Path where config.yml is stored
    ports:
      - 80:8080
