apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: romm
  namespace: romm
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bjw-s-labs
    namespace: flux-system
  values:
    controllers:
      romm:
        containers:
          app:
            image:
              repository: ghcr.io/rommapp/romm
              tag: latest
            env:
              DB_HOST: apps-cluster-rw.cnpg-apps.svc.cluster.local
              DB_PORT: "5432"
              DB_NAME: romm
              DB_USER: romm
            envFrom:
              - secretRef:
                  name: romm-secret
    service:
      app:
        controller: romm
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        hosts:
          - host: "romm.${cluster_domain}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: romm-config
        globalMounts:
          - path: /romm/config
      resources:
        type: persistentVolumeClaim
        storageClass: longhorn-backup
        accessMode: ReadWriteOnce
        size: 10Gi
        globalMounts:
          - path: /romm/resources
      redis-data:
        type: emptyDir
        globalMounts:
          - path: /redis-data
      library:
        type: nfs
        server: 192.168.1.131
        path: /volume1/media/complete/roms
        globalMounts:
          - path: /romm/library
      assets:
        type: nfs
        server: 192.168.1.131
        path: /volume1/media/complete/roms/assets
        globalMounts:
          - path: /romm/assets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: romm
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bjw-s-labs
    namespace: flux-system
  values:
    controllers:
      mariadb:
        containers:
          app:
            image:
              repository: mariadb
              tag: "11.4"
            env:
              MARIADB_DATABASE: romm
              MARIADB_USER: romm
            envFrom:
              - secretRef:
                  name: romm-secret
    service:
      app:
        controller: mariadb
        ports:
          db:
            port: 3306
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: longhorn-backup
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /var/lib/mysql
