apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 1h
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: traefik
      version: 39.0.8
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    api:
      dashboard: true
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints:
          - web
        matchRule: Host(`traefik.${cluster_domain}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    service:
      annotations:
        metallb.io/loadBalancerIPs: 192.168.100.200
    ports:
      web:
        forwardedHeaders:
          trustedIPs:
            - 10.42.0.0/16
            - 10.43.0.0/16
    providers:
      kubernetesCRD:
        allowExternalNameServices: true
