apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudflare-tunnel
  namespace: traefik
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: "*.${cluster_domain}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik
                port:
                  number: 80
