apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airbyte-db-external-secret
  namespace: data
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: airbyte-db
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: airbyte/username
    - secretKey: password
      remoteRef:
        key: airbyte/password
    - secretKey: CONFIG_DATABASE_REPLICA_USER
      remoteRef:
        key: airbyte/username
    - secretKey: CONFIG_DATABASE_REPLICA_PASSWORD
      remoteRef:
        key: airbyte/password
  refreshInterval: 6h
