apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airbyte-external-secret
  namespace: data
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: airbyte-secret
    creationPolicy: Owner
  data:
    - secretKey: email
      remoteRef:
        key: airbyte/username
    - secretKey: password
      remoteRef:
        key: airbyte/password
  refreshInterval: 6h
