apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: airbyte
  namespace: data
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`airbyte.${cluster_domain}`)
      kind: Rule
      services:
        - name: airbyte
          port: 8001
