apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: airbyte
  namespace: data
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`airbyte.${cluster_domain}`)
      kind: Rule
      services:
        - name: airbyte-airbyte-server-svc
          port: 8001
    - match: Host(`airbyte.${cluster_domain}`) && PathPrefix(`/api/v1/connector_builder/`)
      kind: Rule
      services:
        - name: airbyte-airbyte-connector-builder-server-svc
          port: 80
