apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: freshrss
  name: freshrss
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
        - name: freshrss
          image: freshrss/freshrss
          env:
            - name: BROWSER_START_DIR
              value: /apps/freshrss
            - name: PGID
              value: "100"
            - name: PUID
              value: "1037"
            - name: TZ
              value: America/Denver
          #envFrom:
          #  - secretRef:
          #      name: freshrss-oidc
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: 4000m
              memory: 2Gi
            limits:
              cpu: "10"
              memory: 8Gi
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: /freshrss
              name: freshrss-freshrss
            - mountPath: /temp
              name: freshrss-temp
            - mountPath: /app/Data
              name: freshrss-data
            - mountPath: /app/Logs
              name: freshrss-logs
            - mountPath: /app/common
              name: freshrss-common
      restartPolicy: Always
      volumes:
        - name: freshrss-freshrss
          persistentVolumeClaim:
            claimName: freshrss
        - name: freshrss-common
          persistentVolumeClaim:
            claimName: freshrss-common
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-data
        - name: freshrss-logs
          persistentVolumeClaim:
            claimName: freshrss-logs
        - name: freshrss-temp
          emptyDir:
            sizeLimit: 100Gi
