apiVersion: v1
kind: Secret
metadata:
    name: bytebase
stringData:
    postgres_password: ENC[AES256_GCM,data:F08YQ1MQWEmkOxkoSNGu35KI1K0EX4GUhVC7qwVcT6C78jZRkpTSWg==,iv:I9ji62cZtP/FKWPhPsNnF6M58in2ovYw259sbDNGtko=,tag:dJ6RVOmQUqYCqYrCmqD6dQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMUFoOGRVbkVVNFZjdEwz
            dENwZUJKQWIxWU8zV0ExRFM1SDkzamVQYkJrClFoOWJBZCsvLzlxQU9FVXZXN1VO
            bDMzQnVoMmE2bWlrLytsU3FpOVh4aXMKLS0tIDNBZHVnZWJXRWtiRml4aGVheExE
            aWhlTTdrMkcxNlZBM24yMi9idnB3RWsKmGTiG2WRsP8vlLELY2//CwPY3CxhOpYc
            O+wPF6zVDAvHZndJUdFCTpY8TsyauBIrrY2Jf+Lbz60qidynWc6wQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T04:54:56Z"
    mac: ENC[AES256_GCM,data:nmkjNn8d63iKt8tqtv4BzOeKqbBSQ9NR6PHqYsnT+eP6aAN94UF5jHuYe2cXY0vfvMObjcY9LHzSn/ZHI9Irlu89KTspd13Har+u2iO3lEc1Qq0aPLTUBvHZOGiWc33w6lxHqJTGRK6ESd6/cf4tb93LC6t45X3qcKOwJChPDMU=,iv:mO0rFpZUM4Nh6ennOwBaLGOnMkoRXaMxIJVFye3PF+k=,tag:U30SeRjizUf/5VQQK7grSw==,type:str]
    version: 3.13.1
