apiVersion: v1
kind: Secret
metadata:
    name: bytebase
    namespace: data
stringData:
    postgres_password: ENC[AES256_GCM,data:MF5LjSfPfZx/MB5cfiC17M7ZtUtt0+CJMuKm5UGigN4BpdAmnvKIzA==,iv:j9py0TopyybHjKXr7Q24PXgyLsN6IvBkPM851oEW96k=,tag:a9AOa8rkj4RgGZ9A0UjAhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMkhuVDRKbUZ5SHdOM2Zh
            YzYyTEFlV1BNSUxnM2U5dzNFVWplSHJsL3ljCk5WeHZwdlRoV3NXTUxWR0RrRndu
            UDFrOHBGYU1JQ1NIblVpYS96ams4aEUKLS0tIGkwdXVxSGtGelVpaGpYSlA1Mklw
            Wkp0Mlh3cE16VmFTQlJDc0JENFpzZk0KdJGVo4IbqUzVFaKfz7gfgOGL4f+VQomJ
            5akmbn+ctHOAUAoWyp7SHs1xtt83fvYePcpDUGX5pruNXw6lwgTDuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-09T02:53:10Z"
    mac: ENC[AES256_GCM,data:APobTLXx5O9hiKdho7+vcOhuOSNkttV5l6LQlGWYqDCa9WCmru6fxdBtLIttvKiA9HVxLMYh8ZNeAg8Il7mxnME6cIOsUeLqJGnchv+hl6iedBVSScDRenVJY+t/m8shXah+J7njSquQDMouHhpPmSdsK/3dG6yCF9J0mPRDG60=,iv:B9v9WEyMHoswV5UsXvnzoyOXKL4n7sMNt7GMPhVcldE=,tag:5dD8bU6uRfieKAHwZNdiRw==,type:str]
    version: 3.13.2
