apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr-settings
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: bazarr-settings
    creationPolicy: Owner
  data:
    - secretKey: config.yaml
      remoteRef:
        key: bazarr/config.yaml
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr-external-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: bazarr
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: bazarr
  refreshInterval: 6h
