apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
    namespace: media
stringData:
    POSTGRES_ENABLED: ENC[AES256_GCM,data:6a37aA==,iv:eke0sFijpiypJ9COW1qCBUwzoU2bVAX3q2IIGsON50E=,tag:0LytEBxgQVhnhW0/mUoIqg==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:XCxG1sKct2GTkDzU+S/t/Iv5w9IuFP/J1Kgqyc9KcoDzXMkPrS47wHf3C01aQ80=,iv:q5RU0u9FPpnmzWHMgNG5KSMKhq+GxM8WELhbtVvgIr0=,tag:cooRB+WSgn956UAFWmj6WQ==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:TcD8wg==,iv:PrwZxFEIL5w8by/H78Z5KIUiAvie8JnWSaAuVoU00s4=,tag:DUgYPiMxHc71mBC73LkyNg==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:iFvrhaWV,iv:Pxf3f8LOUqyeWGdhl083KMZlPdnZDOha/mH2+U/HNEo=,tag:vHEq2nOZBZ7YwRwLCo9rRw==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:Bg08uW27,iv:rhdXpgisV2luBalEiXI+rhja3BEbLhM+1W2YiHyiXX0=,tag:4bRkCSZ1HccskMEXe/+hoA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:eqWe2rvd/PZoy5tZ4BA8zuRwPvCT4eZgKsctmdmOglynHG1iHhCoylLkxsw=,iv:X2M87qm/RmdDrioXte2UC+oWWHVukAcvIDajWibugfQ=,tag:Y7FnMSMisPPkybXGmVaNHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMK1dOOXF0ZlFDckNRa29T
            WGIzcG04MGZXTDl6K1ZhRUMvRVVWNFhhQlNVCm40Ylg5QUh0eWkyYUZwWXdrb05X
            UUxOeHMrTGxSTlF1NVMvcm42R0JpSlUKLS0tIDluU2h2aUVlaFc0azBjSFZiTGxj
            WVZkcWFyVzRLekx2MTFZYmsxdWtRWWMKclrTW4Qvu+xjHw5IyL1Z5K3G/WUtY1Gy
            +pCpvca1LYlSwP3bxenOQHoRvPZegwZ37bHU4QbAn6doRQMo4hHetw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T11:42:39Z"
    mac: ENC[AES256_GCM,data:+hPXxM7dci6eK24t1V44kWKZAPJqfytF8LsAtVtSI+3QiSMp0ZZAaIqkb3C1JSwnibqfzxZiwoCT8mH/ynepDIcKEbT8XbfeXkvxSP2cK4xywY0L1PscS1Xnw6a93WRAVtBj6tSXmGaxDWqBIb2YBW3SWmKT7jmYilaYohTIGnE=,iv:v+qad+YLj6rl/AsBxq2/RhXkaZ8gW/VnU0v5ciVVpfY=,tag:dVQ9VDi32pgFWD5A3VEcWg==,type:str]
    version: 3.13.1
