apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp
  namespace: headlamp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: headlamp
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        values.yaml: |
          config:
            oidc:
              clientID: "{{ .client_id }}"
              clientSecret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: headlamp
