apiVersion: v1
kind: Secret
metadata:
    name: headlamp
stringData:
    client_id: ENC[AES256_GCM,data:YWWZLC8Gdpar/cBY3CcnbICvN6l0IKzN3IgovP0CAWtnmyPNMI9aRA==,iv:J7rBssrxNUxGhP5xlx+v9EJeIvTL1sV3Milasphd2CY=,tag:Ln22YbTK5+/qDZCOMP3QWQ==,type:str]
    client_secret: ENC[AES256_GCM,data:e6nRJwWogxcrCVnLxP89Tm2xsls6SB376bq7g1n8JSS6TL0DIHQOGk4VaZCrRp+XCFBBY4Cqb95OL28pbwVejow3ZFXPnpdHqO3B1bB6vqAfWJ9SzAZITzYldGQeHCxbZ/+hF4gKrlz2ZOtlUD4kj6Zfpj+aNM/XERt7vSxX0vA=,iv:M3dlR8RM6/FrEt2e+owo0IsW4NyWgANf8UPY+jLD1Pc=,tag:6eJ7kyRjbpT+GFgMIRy4kw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNFd5THM0cHRMRVo1OGxW
            bHpXcktLNm94NlRONEVIaC8yeWdPdkdQR1E0Ckpud3Y4Njd3SHJHc3pVRFlGek53
            ejVBdmtONlc1amJ6ODArVU1Wc0Y4aTQKLS0tIGVkQTRUNXBaN1Y2Nzk0L3lQd1hl
            VHoyMzRha3ZjbHo0ajFBRGtUQXBjQ1UKzhNy/zwzQv9V6ocH2ZGdovlaSUU9++Sd
            Od3xLrQfGTN3wA85RawweNq+ZyZc2Y6AUJdTdSWNOdwKew3p/s8CjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T03:45:08Z"
    mac: ENC[AES256_GCM,data:iQnbm/5svOBDDwKAXIesZOVzp6C1ztamc3VZ2+3XIt7Hj31eCSHC9MsNr+GJDIu3ygR37ZOx6tN67kNg1La2zeZ5tM+xGXi1ti4q/qjxKsjg81qhCfXxd2f4oaN8Q2/EDMhOjxeOK4cNwANVwqIBnTDGMadw0rEn7IzWxBsIixs=,iv:8uhFUZW1HxJOriyatrLD7XtJ5BI03L4wckj1AgdycVc=,tag:+5ZMcYNY/27EHzqEebaDCA==,type:str]
    version: 3.13.1
