apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: private-ingress
spec:
    ingressClassName: ENC[AES256_GCM,data:T8OQtec5X+mT4U9YD0F0yHQ=,iv:3IBc+OhCVhfA/AMXwW5aSRc9kEyRpM7HSXmIUabyywE=,tag:bN9gvq/t4rSDyAk2fI8Bng==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:JSA1dogkG9otkOxxx86pIgoDoDf5Mkun+dxg2A==,iv:KLMyi1KuSZJKZqtcZQ9OgMzYwbvtJOaimYI9F5qpG1M=,tag:z5NaBk/S+OUnQfUWB4hbGw==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:6Q==,iv:UwtYpMFL1NmjjGg7B1PAClHj2Yj7mNSdr7SzlX+Pv5s=,tag:M66WtlyNM9+ALpWfxHS26w==,type:str]
                  pathType: ENC[AES256_GCM,data:TRQnk26X,iv:FukcgiHAxSYFVeLBjc9JsHZvzj2lah/FbwOJwVLUynw=,tag:nzcdDoFlI6g2XmQ7d1bvuQ==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:pHzKKMpihA==,iv:RGCquK7gslCuhNVw3OLgztPUF2Z/Iak1jyAp+SKCM7Y=,tag:WOvjVMdItv74thD6YtdP6g==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:A48=,iv:hOe1H+VJCWWJ0iPUsNP8gSQdeBKpHoIE4/Z0ImTZjV0=,tag:s+1f+Zp27nZq+xoWSWf8QA==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWlZrU3hoWk5vSm90WFNE
            NlVUSUVRbm9TZHY2d3VFY3JCVGdyTFJvd0dVCi94UTBSWHJxaVlUZ0swNzQwSHAy
            TnNXc1lmYjhmUkI3SlVaQnJXaVdSejQKLS0tIHVnQ1FLWlJvUkxpUXdpTURibk5x
            ZWc2ekwvWGlVZ0RtR3dtVnl2LzB3TWsKIJU8SFgPJeXJY6Ra5/wpL0fXZIu/t7e/
            ZyE+YhyZ6zx+O9T/g1C/qc38L/GFwoXH6P/IcrTBrUf9QJdsJOpaRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-24T23:44:57Z"
    mac: ENC[AES256_GCM,data:/47Ll9CsS14zjPlsFggkdREExNUpdnEK+FJwfIBxgZ8T9Tw9me/mklRUPOIdLNGeZyKM7U1vONXgoDjHIFNw1Xy1kj8Un19TtORhdruuCDsG7F62RQFvT52uWM+6SattKEM+UZLupdypREEYjIrHsdqlodOwkJHFdXCXF7xOmOQ=,iv:cH1NMxF7ACp82BM7S1pipwV8JY2mGcpG4rsjqf2+dY4=,tag:MKabOOPPqmjpKBh4oXIKYA==,type:str]
    version: 3.13.1
