apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: private-ingress
    namespace: traefik
spec:
    ingressClassName: ENC[AES256_GCM,data:vUeUo69hzVIO063xmtsBuS4=,iv:4zrvIeSqqtJVCjBdCiRe0UyMuFd9UF7NH8XedNQPOkc=,tag:Jzw2zLY4exN+2JPnsL2VyQ==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:t5oNyYTakvZSjSl758uuNzbcdy0MvTab+5i6bQ==,iv:pI9w73SBBSzxudiVmebf/H70sxTLDwcheUyZHfe0WKE=,tag:+8im1VdRDRwPsdjdN7VeaQ==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:ug==,iv:2Oc8keOhl7DTBv+hgozDoeGq0hAH+8Tk4uzlWeo5WeU=,tag:1nwvUm8iuMq40KuS1Hr90g==,type:str]
                  pathType: ENC[AES256_GCM,data:PhMWk8jN,iv:AHajcNGrn87fLdMGjYZc6rBc0dF85kDXIoYz4mHLtx4=,tag:Vt2gs9wBPs0/HY5PZLAKSw==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:F3wrPbszQw==,iv:f7uenndOMWdelJ0TQeaElIVC2L2BSfNtrrrEpc97y1A=,tag:GFDqs3Uq+Rg8k/3rVg3Yng==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:6Tg=,iv:5TMJW03bV/2EAT58W/w4tnOI8PoEi39tKMUI6szzze8=,tag:KMiZD7WLkeW5HFJcmJcAKQ==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWFFvc3M4R2I5TUp5T0Na
            TFFxVTV4VWgrZzZqdWpQZ3hNaWkxcHhOSW1RCjdCVzB1TUxFU0pGM1lFU0RHL0lG
            bjZKWXBia1VlbHJJNDJSbjl4b3pFa0UKLS0tIFp0YmdUQ2I2NEJ2VTRzSHpVUmtG
            SXZ5UmRjSXN6cHRZR0ZKVUdDS3RpbFEK5Qm0hgeoagwFmG5sI85o6UiH4dERx4S5
            z7WbkBC0to7+WP/gDjq28wo9nqUu2HUlpyt5o6E7lVLFQIX2yrBr8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-24T23:48:09Z"
    mac: ENC[AES256_GCM,data:9OvZ2DJU6G+rP/Smk9odlN9jo6ITvGewBx3DQieb6YYNQmVWOpPsF0szU8nfybVtyTdYMfEaHxp9KJcaDPeRKdBLuy0kgic+aaUTBf63sB9kLeg1PHTW6zlbxSF4LqTBavD3YzkW6gjd7DoVftCxWx+K4fgwPDaR63/FI3bC9L0=,iv:wANsaanfcs5gcDrmY67Eyc2tK0a+aUb/GMQSoHwLnlQ=,tag:0StLEYojMC0UWUHaFfO+3Q==,type:str]
    version: 3.13.1
