apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr-external-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: autobrr
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: autobrr
