apiVersion: v1
kind: Secret
metadata:
    name: autobrr-secret
    namespace: media
stringData:
    AUTOBRR__POSTGRES_HOST: ENC[AES256_GCM,data:PYb3sitXUxT72ScFSvXFS5eS3voMC+RNHzgVa+9hitPN94aemhBpI8iqEOXVq5I=,iv:abC3jVPYaz/kt9gBeThC3nnFi8PgWQfirK5rumz5rrA=,tag:a1vNmwLFJ7JmotRy1lmS0Q==,type:str]
    AUTOBRR__POSTGRES_PORT: ENC[AES256_GCM,data:i/+s3A==,iv:/oH62HZ4Ydv/wdsqcfJRLTystbv0qOmmdRk843/PKw0=,tag:IwpcoXxjWhMtbOmfDacgSw==,type:str]
    AUTOBRR__POSTGRES_DATABASE: ENC[AES256_GCM,data:+7BUKC99zQ==,iv:+Cci1wEU5KuFdyuvX9nTdPaKFiV2xmpJa61IILhlnUI=,tag:7EpC+ocawUz6D7cFW+nCqA==,type:str]
    AUTOBRR__POSTGRES_USER: ENC[AES256_GCM,data:frSZpNsdWA==,iv:gXeMJZ5S+IRBtW4eKw/vc7Ud1XMm0bwFYpb87796Ny0=,tag:+do5QKzyR0NCs+IndNTL0w==,type:str]
    AUTOBRR__POSTGRES_PASS: ENC[AES256_GCM,data:D5mWLVhcdFrV3q0tws4AjfxpuNyaJaRq2LLOD/yuIiSjoAIEHvEhl/iYqbc=,iv:WO/USrjzUkvV2PaoWaeUrBdMnPHfyL1CbNxsoOEEwlA=,tag:oSYS0YTmLE/0baGLmzeCpQ==,type:str]
    AUTOBRR__OIDC_ENABLED: ENC[AES256_GCM,data:AzaZhQ==,iv:Vw4WhiKZVMOCg3TKqiKekrEb3v6cIm+nW9pPBlxQ1KM=,tag:VJFwa8umNUiXoqqKGOt/ig==,type:str]
    AUTOBRR__OIDC_ISSUER: ENC[AES256_GCM,data:wvkdmEx8YjdeL4p8P7QZ7O5UcpK92mNYS5HRqXEVrPl7/yNbYpvguqfqwp8W19s37dQhT9ysduIJcQ==,iv:E6nB+jvnAkIct9tFyWW6pXwGjneGetrbJPZJ9TkwXQs=,tag:nduvsVHuJkO6Lm9es8GYrg==,type:str]
    AUTOBRR__OIDC_CLIENT_ID: ENC[AES256_GCM,data:5g3orqZfB70YU9rEOKNs6P0sTDLoq5MNa6rqDTIhko4iVhQQOWQqgg==,iv:RI9RP53ST1Z9OB0inAfygbIrmUIcqD7QuJOZDySeXDM=,tag:Oaovqupu4b+CP6vJHH2ZgA==,type:str]
    AUTOBRR__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:SUSHZOCH/dAbOgmD2t7mTV8rdqwuJSVnPykC8s4QRMZbjk6XhTL93/4ao2EG8kaS7jykXmuE1hSbqgXvUIkX0hcAmWWDJAWzS3CgT9Ceq1+fH8+9BuE7FnR8du+2eTms7PeYgPAmmw+QE4MOAzTTeOZMWQpgaXWKuIatRupBChc=,iv:IthVlQEMHDIil+jlYP+8xs6B8ek1a2QKCFWUDs86HyE=,tag:0pOut3oCLmBoBVfApPWpIQ==,type:str]
    AUTOBRR__OIDC_REDIRECT_URL: ENC[AES256_GCM,data:N+zee69+l0d0+A4J92nLTNVNYkPBaqii4NxOB5lVTpx06i3GOdAlxfJGobHK0fTFOTZvGWv08Go=,iv:Y1re9BMT+T5GT86GdWXm0me8N66yAXynvTTEx8xggv0=,tag:FDVjO+tY5MIqQOax8bSHwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbzdjTGVxdENZVVFlTkJu
            VkQrYkRSNlZ3Sk52RVZYSVNxNkprZllEOXc0CkRiWU5ncUtaRUd3YVVNN1ppemRH
            dnVKbDhlblMxdjhvbmdhZ00yVGxRNXMKLS0tIGxGYzhVcGxlVWw0VDZiQXphRnpZ
            U1cxcmhvUWhXTlFSNm1ORmVjNGFYVTAKdCVFAXSP2MQhMcKKav+rC0y0VV/THkPG
            3pQfs34sow8/ORx+Rkx/lQY1LsTHWYmrpFiVRETxJh+htyUMEyXmlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T11:42:43Z"
    mac: ENC[AES256_GCM,data:6CEwRuo/9PUoZaDAiLmhoXV5NS/lY2tPCd/4cQiZJsnHTtVCzbEdGNtgCC7g8wJdenoA6VqM5ewYdq3DPW1+IfWQPLaODBMRerymHHQJUvdQPBWdW2J9VVmEgUWpYy5YVt/yrAJMi71xCRRu/FFEryrz31AvPT2zWhbB0rV6fNc=,iv:AIpw/+1XvP8jtepF9a+uA2SRqdhUwqFhIWuWDiRJNww=,tag:oVWNnrmqqHPXgJME++BPwg==,type:str]
    version: 3.13.1
