apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-api-data
  namespace: rustdesk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hbbs-keys
  namespace: rustdesk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
