apiVersion: v1
kind: Secret
metadata:
    name: rustdesk-api-admin
    namespace: rustdesk
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:+jlde+s=,iv:65RhhXLsiUuphNcz0ErSNygmHmFVpMF7ZvsXOHbXZ5M=,tag:GC6FK8vCQG/qXO4C0U6a6A==,type:str]
    password: ENC[AES256_GCM,data:GRJOPAGky/ncf8iADgmss34G+ekw6yM9hSzIhwotGFIBQFga9jo2rC60qICPpg==,iv:08PDtuyvIT+PvtV7ijpobnmFannp8JbhPabNxH5rN74=,tag:P27Yrsw261OxAcX6H73how==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyckwzUmFFdmJCSGs1eEw5
            b01jL1VWT05jWStoR3V6NmJLaUhDaWJiUmlrCkVmcDlWWi9jOUR5dGVFMHJXeHBG
            Z2I4Mjg3VVg4ZjRWZlQ4SWE2MzlOUkEKLS0tIGR1R0ptamdJd0MxT05aY3k0b1U5
            dVlsWGdSNVJaWk1iRE43SW9SWnVlNlUKknPFra/XCEWVfZGN5F8c4CwwfeJonhIR
            vYsWGSx63lgwyuKUIL9ZoNykKhgrd77PL1F6uwDFMZq/LWhYPccIhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-20T22:15:35Z"
    mac: ENC[AES256_GCM,data:DPfzQA8suoa7f3geblkn2Kbrhs7wYomi4f38sB4Q6td3XRZbeuIT+6611Kqk89LbSvyKYpk+AbrvivqaGJIxpI6I1jLCqSin6J8G1d1Gpu4rPKnyB80l/tZUN2/Qov+az/b6xSIPo4qe/tomV+++5rJBrDKTWKLJkEqkrR/L7Cw=,iv:wChSenSnZwq6iIpfyDO/GMvmllnhm9DKeSvm1oc5yFA=,tag:y4JeolSuamyp+Vk7/etsxw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: rustdesk-api-config
    namespace: rustdesk
type: Opaque
stringData:
    server.yaml: ENC[AES256_GCM,data:9SqGhE4awKXKQbO5Fl/G9A/EaZVeljZ6Hf2VhCdjm/piKr9fwsljc85mZ8ihQxWkvVUmhpEaRDyaUutt0CLN0K4QoRIK2Wbbf0qQizDT76qGvV4Iy4J8nMhFMjVQ/NT/FWTVdDK5z6Vfntv8UWM5I9jyVoMegvdemj0aQAxwcoZMQGDKFUtBoEyFx/w0Kb9XH8yCJZ9QyBEdmIJik+8UyoYwe1cnFF5qvpOWNPP5FwppLle/YpjGEBU0g8NdtwIkMclUReEoz3f6xncZt1e5Z/RU1uXZqKYji9aXnEwLj09187nD8Pf4NyPAXmRxi8mPFGHWalfEJOr/FL48NFXA9JTbdABb4vKZ/itsnXWKTN3vr4K4qVD99lHbTT3FiqlDdL6x+NK9Plskcl+NRWJalMbaCUK5W9tUD7iBN33EuME3Yy4s0Pfiy8SBd5ccXbsIE/DTXmeUwZ7aplZiwnwN9eoOwnwHU9fizaeNR8Ma10oxi4w=,iv:pmQis3mO24bflh6ekEZkQ6ctzDFjW9QYDLzV77H49Jo=,tag:poHoGM90PTR4d8MJ0k1DTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyckwzUmFFdmJCSGs1eEw5
            b01jL1VWT05jWStoR3V6NmJLaUhDaWJiUmlrCkVmcDlWWi9jOUR5dGVFMHJXeHBG
            Z2I4Mjg3VVg4ZjRWZlQ4SWE2MzlOUkEKLS0tIGR1R0ptamdJd0MxT05aY3k0b1U5
            dVlsWGdSNVJaWk1iRE43SW9SWnVlNlUKknPFra/XCEWVfZGN5F8c4CwwfeJonhIR
            vYsWGSx63lgwyuKUIL9ZoNykKhgrd77PL1F6uwDFMZq/LWhYPccIhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-20T22:15:35Z"
    mac: ENC[AES256_GCM,data:DPfzQA8suoa7f3geblkn2Kbrhs7wYomi4f38sB4Q6td3XRZbeuIT+6611Kqk89LbSvyKYpk+AbrvivqaGJIxpI6I1jLCqSin6J8G1d1Gpu4rPKnyB80l/tZUN2/Qov+az/b6xSIPo4qe/tomV+++5rJBrDKTWKLJkEqkrR/L7Cw=,iv:wChSenSnZwq6iIpfyDO/GMvmllnhm9DKeSvm1oc5yFA=,tag:y4JeolSuamyp+Vk7/etsxw==,type:str]
    version: 3.13.1
