apiVersion: v1
kind: Secret
metadata:
    name: vault-token-global
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:Ix3ucT5oDADw6rSG0Eg/PPOVBzWPUcMIvkVdeYdW9OkldrELJJ+w9NOiGRrgzl88OE1dhOZUnlJUWfcgZ/9qDFD0H54aJO8xKEdFveBibNo+IgoL7SkewY6IEeIoy5FNHpGVYY8DFclzBIBn6mlu/Xi52/9ys9zvsLBo2KzbIbDetmWqY6ZFo2tz3TyG4D4gLvONXpEHqPg1ABCFGva+DH2KuSdqUbqdtaloQzsYknn/XJqgS5N0AKkifLvLYHTRigF2BYZ+q0h15S+sm1IQNGzK5sThFG1QJlvaU6g7Vp6ph4qyz+v+P8XzMb9nKIhFU2tlIw+K87MJLBi36GZb0kN+HrBZnxo4jQ9Y1tZpqiPaaT04psFaPHvN1UBxMAtx9Bca1R2b4WV//JSQ9elIUKsH2rxVRTBfMIDAJ0j62LabQZC8OLkNnYp5XeGpJCGW15XXzYrJieotGVA2ouCWGDZHVr9ayeOUfTDiwGXFJz4HOf2K47T02HSkRUo+XTALlzI0cKFF7tWKSSrNnbsYWz/BucKTQTT8YaNlTLaSZbkqLUspuJ21oXMzzmGimS32uBNGvqHRrQZKHZSAHaTT93VRvlrPrz84YvXpeV9WvFPpWvLDOKAo44B5D0d1KoXVL+jv5oayhefWLw7dFOKq3MjP/HaMIes4WgNfbW5pOwKPfM7d4+n9xyuG+R1rZkes5F3l8t6E1sBT6Kv4ttduCWLmZVzUxMYUY6Lf+nCBuIKPRBNLKjfG5c4D68d4BvfyZTm7V2GzKbX+07+K4fscwCIR/EFb2IQf3bF3PwzfqLoJu/VsnD7f2L4r08fBb6tOxDAmeO+XEWzL09yLPyccE+qSE//JhC11mLOUoBu+D5qMTbphfyTpVUwqUqUQ8PDpkrnOobhQHySJyXEDmIC2B059madwL3MpQq0NcsYE85SZi2WziVCfadERQoj0c5vQCQS98KszqwQ3wLCyI4q4wj2ghWgsT89tejbDexNocd03zmbxqYYS+EXnrjhfcw1FDs3xjSNrSFSXcJyqyG9llrqhWKsOxebFcZutQPhwx4/K+H51yO06Kfdk+A24xiTWKtWGAfYudw0xXYobDBq3T0ao9muWClp/M5smm9xTeKikY+Bf,iv:0nLMqsNvORlrAvu//Cn5GJI5fIERHrKvjMwi5YOcDMc=,tag:/F+RLmVjX/UMnQ0ARvZAvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcitVZzUyTGZkenlZalpI
            WE5zSE1qeWhoaU9yZzRXeG9pVTNmZnRoUkhrCnVUZGl4bENodmt0ZEN1S0VXcXFH
            V09JbER6eitwRDhtQ3R2WFVZcjBkRmsKLS0tIGdaSkRQK1U3OVAybVhCYm9IWEkz
            Q2FFbXJUV0pNVHdGemJseHhSZ1NvSEkKhXD86RteYAxirqrTy73NHNIaBWBbZYNm
            gPVZOw3x3ES6BoGVvaLg0v63bI1XfWi0uItuLxjppWp4LWaqNRMcpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T07:04:09Z"
    mac: ENC[AES256_GCM,data:V3tBL+BG7x+DswgE8kiwq7K2k8HhGPM6bHvjYxwsf7+Uqwg1ll4A/P/tKDv2NpeUjyD2mOc09hTh7ege1yMAVXq+xYBCpg2yF8EXU5g0cpAcx8cfpzdVOOIbezUg+F3D0APZzu4SR4jijyi1bxDYn2NZaprOGW1xjXIYear7OCY=,iv:+ZhP3HSviK81CxxesRDKfTBKzy+OZAGJtk8FhLEch+0=,tag:fqq3Tn59WGd9bzHJv/SefA==,type:str]
    version: 3.13.1
