# Just to get calibre up right away. Switch to argocd later
apiVersion: v1
kind: Namespace
metadata:
  name: calibre
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  namespace: calibre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      containers:
        - name: calibre-web
          image: lscr.io/linuxserver/calibre-web:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Denver
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: config
              mountPath: /config
            - name: books
              mountPath: /books
      volumes:
        - name: config
          emptyDir: {}
        - name: books
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: calibre-web
  namespace: calibre
spec:
  selector:
    app: calibre-web
  ports:
    - port: 8083
      targetPort: 8083