apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: home-assistant
  name: home-assistant-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 2Gi
