apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-dbs
resources:
  - namespace.yaml
  - cert-issuer.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - app-cluster.yaml # Note, this may cause ordering issues
  - app-databases.yaml
  - secret.yaml
