resources:
  - agregarr
  - autobrr
  #- bazarr
  - configarr
  - plex
  - prowlarr
  - qbittorrent-vpn
  - qui
  - radarr
  - sabnzbd
  - seerr
  - sonarr
  - tautulli
  - flaresolverr
  - fileflows
