apiVersion: v1
kind: Secret
metadata:
    name: data-db-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Aha9+w==,iv:H3d4Li5wBE6A7xKGagmUp9blWnTvEr5jAhkJBr9cpzs=,tag:rSd6Umy7VblH8GZq0WnMeQ==,type:str]
    password: ENC[AES256_GCM,data:Y2YwJ07KOqwfQwjICW1yjjOWgZXpKlva1Nhgx4gd3SpXT/e8/eXXNgm+hNHf,iv:jdzBqSluVcmLCdUrgmDK7wnmwS4TEVMjeovG1eUKvxU=,tag:fc7Y3UkOvNifkCHM+0lsgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU1JMNFltRTF1Yy9FSE45
            U2pRYXdxTnFJbUFESFphYk5LNHVhTGhjTWdBCm5MNkJETm5DRWxuQ25TaUczN1E3
            Y01IM3RwVno3SWRNQkFMbGIzY2paTGMKLS0tIFJKY3N1UGR6WmdpRUhoUjIvb1ZL
            YnE3QU96SEloSDYrM1FkYzBqdGtmeWMKuQLCNuZDZMtz8iHLCY9o7xehU0t1Aob9
            xyg7h+JMz/4eKI2VVGIwHQ8j0+VZsiMPFI9Y0V09YKHlBMlQCC4zcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-25T01:30:35Z"
    mac: ENC[AES256_GCM,data:TGOP07xO36w0W7nnil3PsUOGCmEvMpuYFhZyr69A6hSY5UQ5CSfJ+vjFFxa5+V0ZlNzl2rZIyGWhlwvuFbIJJhZ1sVX0Wfy+7+F0DM1S8fKfNCAXKeD3nOD3QSgRXj/oA59djbgdv2wpgxI72gFqL9TnD0XAF783i5h9iJIkMqU=,iv:ArHoBMR1QPVCeBQvHaizoqKQggOn/7LLxW5K0Chwqog=,tag:zfaYCzL13cpDtIVzYLi5Pg==,type:str]
    version: 3.13.1
