apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

resources:
  - helm-release.yaml
  - helm-repository.yaml
  - pvc-config.yaml
  - service.yaml
  - ingress-route.yaml
