apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: romm
  name: nextcloud-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 2Gi
