apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: data-cluster
  namespace: data
spec:
  instances: 3
  enableSuperuserAccess: true
  certificates:
    serverTLSSecret: data-cluster-server-cert
    serverCASecret: data-cluster-server-cert
    clientCASecret: data-cluster-client-cert
    replicationTLSSecret: data-cluster-client-cert
  bootstrap:
    initdb:
      database: app
      owner: data
  storage:
    size: 15Gi
  managed:
    roles:
      - name: data
        login: true
        passwordSecret:
          name: data-db-secret
