apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-data-external-secret
  namespace: data
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: data-db-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: data-lakehouse-cnpg
        property: username
    - secretKey: password
      remoteRef:
        key: data-lakehouse-cnpg
        property: password
