apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: op-secret-store
spec:
  provider:
    onepasswordSDK:
      vault: the-white-lodge
      auth:
        serviceAccountSecretRef:
          name: op-token
          key: token
          namespace: external-secrets
      cache:
        ttl: 5m
        maxSize: 100
