apiVersion: v1
kind: Secret
metadata:
    name: generate-secrets
stringData:
    generate_db_password: ENC[AES256_GCM,data:96jMrer/QjAgNjWsoMc4D9sAZnhErNBVRz6S65Rzaoh6PCev85VxtCbC03jL,iv:DZ+hCaOo16KPxZLa6RePw3AJCUpoffWzlvkvvxCADhw=,tag:9rCmzi5FtokoNjtUWDsXQQ==,type:str]
    generate_aad_client_secret: ENC[AES256_GCM,data:r+MN2LMxPHY7vXwcQzqTOUjHrOE6dGPSzabVFdQvcshAz3L2gvQvVw==,iv:NCOCgguIyM8COPXdA4Dq7la3fNIrIJvgClNHIxtvQWM=,tag:AWFg0qMHPfXeurLLyr0cTQ==,type:str]
    azure_tenant_id: ENC[AES256_GCM,data:F+s84KQPTdNcX1cpbItK4GO/mBWdrEZDpPyCgv+cv2B3XHNV,iv:D1n1oc6Xy75c8uo6iDnI11Vc8Nu6FmJSFO5Xv5swo6o=,tag:uRG26znD5nJEX/MbhwFIhg==,type:str]
    azure_client_id: ENC[AES256_GCM,data:B0qfSMIilxJEfKKxDMXCVaRtc+L+oWNztKZ8KgGSKLmIaP0G,iv:B1mv4bL97f/iIUSeipPlYJ0FUFrYIIZ5SOLJ+w/HPpc=,tag:fwjQuHiuGPrVHyc/Sl9MQQ==,type:str]
    azure_user_id: ENC[AES256_GCM,data:Fk75U3tKTvprlBTAIgng7SPB8gz+hrjb396+8Tsy+/ZeTKAy,iv:w0cLHIohRBuK/UoH4iRziC2l1GwJxl1xi1tFezuIdCE=,tag:hgPpmCFJl/uxM+HmCnwLUw==,type:str]
    azure_domain: ENC[AES256_GCM,data:+1uCcRLNE0xHYMQhTovhLlhXw2ngD86eyfYCf2ToGTYU3Ub/,iv:8TkmoGsfCZDTNPmI36NOuaoTfz0Ine8jSyhAdgsOAFs=,tag:8YmPZboV1CbeKA9dgRO+eQ==,type:str]
    db_password: ENC[AES256_GCM,data:QFd4WzEjigbK7xGr4Zg9IzvS9y15rqTOhstfFJ3YiPejVh9p+Q/tGV9QL7ex,iv:hf9vYj/Pd8wkcsTM+Ct8aG/Ir9rNSDspNzk0RnSOa7M=,tag:j6qxlEwp2xS8nYEqBGcakw==,type:str]
    embedded_admin_password: ENC[AES256_GCM,data:fYOh2Lli8yIz3yGdBQmx6WD+eUlw/lI7M3+CXca6P2ELk89BN3VHMRIQHVyCAw==,iv:i7OTs4/03dxV4DK3U5wHQ6ki9KFmaCCJWN6vTLJOjvg=,tag:uY6bXAPKZVX/tOappyIQYw==,type:str]
    embedded_reviewer_password: ENC[AES256_GCM,data:WS5BVniFU0k9IOrTDvvuvXfe1viacATyML72JrHw33FPnz4fFWmyrpo=,iv:kOh4UcixwC9+jIBmHq61KxiGk9+KSW+BdPPtqfxQ1zc=,tag:b8cJ1NJGN6oFs5LS7gtasg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVjdkbm8zNzlreGxraFA3
            Q2FZUFprdytRTFNvSGcrTURmZUhxenlYTzMwCllFMmorM01qN3IzajhHNk1sME1K
            K2RBbGlqSWxkZERqTjVISFZuaW05YkEKLS0tIDhuSStrWUZJeC9vYVo3S2FuUXdR
            cXJnVzUvR01Fc2VaTWdpOWJzZzRzNEkKRo/ulGVB1baV0E3i1qB3Rx2iFjrzY45J
            78v9STMPnhvO7d+KL5YQJ4aTEtyGE92zKs7X+2zczXrFAEM0jpsAWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T07:22:49Z"
    mac: ENC[AES256_GCM,data:/cOa6iz9KQg0jyhffjGYBVZFKxwkKWRI+mDYn2Bznp03Ek8zqbG9aVPGJX09K3FxZ3jTLGzU3oFrbJHy9xqt2ncT3S+Esjmwy7l5yjvL+cF4zn++v9lIk0tqpbFr0n31BYzSe+UzBnKEOWpKij2uJr42TAHPrB8LR9Kvq12/hWc=,iv:FAyTro3iOGY2fQbYUDksN/8gdPeJWgEtHgD2pRknDGQ=,tag:hjwVfoVv91TYzSTUWRt72Q==,type:str]
    version: 3.13.1
