apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-bootstrap
  namespace: cloudnative-pg
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pg-client-ca
  namespace: cloudnative-pg
spec:
  isCA: true
  commonName: pg-client-ca
  secretName: pg-client-ca
  duration: 87600h
  renewBefore: 8760h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-bootstrap
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pg-client-ca
  namespace: cloudnative-pg
spec:
  ca:
    secretName: pg-client-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pg-replication-cert
  namespace: cloudnative-pg
  labels:
    cnpg.io/reload: ""
spec:
  commonName: streaming_replica
  secretName: pg-replication-cert
  duration: 8760h
  renewBefore: 720h
  usages:
    - client auth
  issuerRef:
    name: pg-client-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-client-cert
  namespace: cloudnative-pg
spec:
  commonName: postgres
  secretName: pgadmin-client-cert
  duration: 8760h
  renewBefore: 720h
  usages:
    - client auth
  issuerRef:
    name: pg-client-ca
    kind: Issuer
    group: cert-manager.io
