apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-cluster-server-cert
  namespace: cnpg-apps
spec:
  secretName: apps-cluster-server-cert
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  duration: 2160h
  renewBefore: 360h
  usages:
    - server auth
  dnsNames:
    - apps-cluster-rw
    - apps-cluster-ro
    - apps-cluster-r
    - apps-cluster-rw.cnpg-apps.svc
    - apps-cluster-ro.cnpg-apps.svc
    - apps-cluster-r.cnpg-apps.svc
    - apps-cluster-rw.cnpg-apps.svc.cluster.local
    - apps-cluster-ro.cnpg-apps.svc.cluster.local
    - apps-cluster-r.cnpg-apps.svc.cluster.local
  ipAddresses:
    - 192.168.100.202
  issuerRef:
    name: cnpg-apps-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-cluster-client-cert
  namespace: cnpg-apps
spec:
  secretName: apps-cluster-client-cert
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  duration: 2160h
  renewBefore: 360h
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: cnpg-apps-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
