apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: apps-cluster
  namespace: cnpg-apps
  annotations:
    kustomize.toolkit.fluxcd.io/depends-on: helm.toolkit.fluxcd.io/namespaces/cnpg-apps/cloudnative-pg
spec:
  instances: 3
  enableSuperuserAccess: true
  certificates:
    serverTLSSecret: apps-cluster-server-cert
    serverCASecret: apps-cluster-server-cert
    clientCASecret: apps-cluster-client-cert
    replicationTLSSecret: apps-cluster-client-cert
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: apps-credentials
        #postInitApplicationSQLRefs:
        #  secretRefs:
        #    - name: my-secret
        #      key: secret.sql
        #  configMapRefs:
        #    - name: my-configmap
        #      key: configmap.sql
  storage:
    size: 15Gi
  monitoring:
    enablePodMonitor: true
