apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: apps-cluster
  namespace: cnpg-apps
  annotations:
    kustomize.toolkit.fluxcd.io/depends-on: helm.toolkit.fluxcd.io/namespaces/cnpg-apps/cloudnative-pg
spec:
  instances: 3
  enableSuperuserAccess: true
  certificates:
    serverTLSSecret: apps-cluster-server-cert
    serverCASecret: apps-cluster-server-cert
    clientCASecret: apps-cluster-client-cert
    replicationTLSSecret: apps-cluster-client-cert
  postgresql:
    pg_hba:
      - hostssl all all all cert # modified from `hostssl all postgres all cert`
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: apps-credentials
  storage:
    size: 15Gi
  monitoring:
    enablePodMonitor: true
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "cnpg-apps-lb"
              annotations:
                metallb.io/loadBalancerIPs: 10.10.10.2
            spec:
              type: LoadBalancer
              ports:
                - name: cnpg-apps
                  protocol: TCP
                  port: 5432
                  targetPort: 5432
        - selectorType: ro
          serviceTemplate:
            metadata:
              name: "cnpg-apps-ro-lb"
              annotations:
                metallb.io/loadBalancerIPs: 10.10.10.3
            spec:
              type: LoadBalancer
    roles:
      - name: authentik
        login: true
        passwordSecret:
          name: authentik-db-secret
      - name: immich
        login: true
        passwordSecret:
          name: immich-db-secret
      - name: lidarr
        login: true
        passwordSecret:
          name: lidarr-db-secret
      - name: n8n
        login: true
        passwordSecret:
          name: n8n-db-secret
      - name: nextcloud
        login: true
        passwordSecret:
          name: nextcloud-db-secret
      - name: mealie
        login: true
        passwordSecret:
          name: mealie-db-secret
      - name: paperless-ngx
        login: true
        passwordSecret:
          name: paperless-ngx-db-secret
      - name: semaphore
        login: true
        passwordSecret:
          name: semaphore-db-secret
      - name: bytebase
        login: true
        passwordSecret:
          name: bytebase-db-secret
      - name: dbgate
        login: true
        passwordSecret:
          name: dbgate-db-secret
      - name: radarr
        login: true
        passwordSecret:
          name: radarr-db-secret
      - name: sonarr
        login: true
        passwordSecret:
          name: sonarr-db-secret
      - name: bazarr
        login: true
        passwordSecret:
          name: bazarr-db-secret
      - name: prowlarr
        login: true
        passwordSecret:
          name: prowlarr-db-secret
      - name: autobrr
        login: true
        passwordSecret:
          name: autobrr-db-secret
      - name: deduparr
        login: true
        passwordSecret:
          name: deduparr-db-secret
      - name: qui
        login: true
        passwordSecret:
          name: qui-db-secret
      - name: romm
        login: true
        passwordSecret:
          name: romm-db-secret
      - name: wikijs
        login: true
        passwordSecret:
          name: wikijs-db-secret
      - name: zammad
        login: true
        passwordSecret:
          name: zammad-db-secret
      - name: sabnzbd
        login: true
        passwordSecret:
          name: sabnzbd-db-secret
      - name: wizarr
        login: true
        passwordSecret:
          name: wizarr-db-secret
      - name: ntfy
        login: true
        passwordSecret:
          name: ntfy-db-secret
      - name: test
        login: true
        passwordSecret:
          name: test-db-secret
