apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik
  namespace: cnpg-apps
spec:
  name: authentik
  owner: authentik
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: lidarr
  namespace: cnpg-apps
spec:
  name: lidarr
  owner: lidarr
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: cnpg-apps
spec:
  name: immich
  owner: immich
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: n8n
  namespace: cnpg-apps
spec:
  name: n8n
  owner: n8n
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: nextcloud
  namespace: cnpg-apps
spec:
  name: nextcloud
  owner: nextcloud
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: mealie
  namespace: cnpg-apps
spec:
  name: mealie
  owner: mealie
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: paperless-ngx
  namespace: cnpg-apps
spec:
  name: paperless-ngx
  owner: paperless-ngx
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: semaphore
  namespace: cnpg-apps
spec:
  name: semaphore
  owner: semaphore
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: bytebase
  namespace: cnpg-apps
spec:
  name: bytebase
  owner: bytebase
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: dbgate
  namespace: cnpg-apps
spec:
  name: dbgate
  owner: dbgate
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr
  namespace: cnpg-apps
spec:
  name: radarr
  owner: radarr
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sonarr-main
  namespace: cnpg-apps
spec:
  name: sonarr-main
  owner: sonarr
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sonarr-log
  namespace: cnpg-apps
spec:
  name: sonarr-log
  owner: sonarr
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: bazarr
  namespace: cnpg-apps
spec:
  name: bazarr
  owner: bazarr
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: prowlarr
  namespace: cnpg-apps
spec:
  name: prowlarr
  owner: prowlarr
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: autobrr
  namespace: cnpg-apps
spec:
  name: autobrr
  owner: autobrr
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: deduparr
  namespace: cnpg-apps
spec:
  name: deduparr
  owner: deduparr
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: qui
  namespace: cnpg-apps
spec:
  name: qui
  owner: qui
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: wikijs
  namespace: cnpg-apps
spec:
  name: wikijs
  owner: wikijs
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: romm
  namespace: cnpg-apps
spec:
  name: romm
  owner: romm
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: zammad
  namespace: cnpg-apps
spec:
  name: zammad
  owner: zammad
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sabnzbd
  namespace: cnpg-apps
spec:
  name: sabnzbd
  owner: sabnzbd
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: wizarr
  namespace: cnpg-apps
spec:
  name: wizarr
  owner: wizarr
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ntfy
  namespace: cnpg-apps
spec:
  name: ntfy
  owner: ntfy
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: test
  namespace: cnpg-apps
spec:
  name: test
  owner: test
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
