apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: autobrr
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .AUTOBRR__POSTGRES_USER }}"
        password: "{{ .AUTOBRR__POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: autobrr
  refreshInterval: 6h
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: bazarr
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .POSTGRES_USERNAME }}"
        password: "{{ .POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: bazarr
  refreshInterval: 6h
