apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-apps-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-apps-cluster
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cnpg-apps-operator
  path: ./cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
