apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-apps
resources:
  - certificates.yaml
  - cluster.yaml
  - databases.yaml
  - namespace.yaml
  #- pooler.yaml
  - secret.yaml
  - push-secret.yaml
