apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: apps-cluster-client-cert
  namespace: cnpg-apps
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: op-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: apps-cluster-client-cert
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: apps-cluster-client-cert
          property: cert
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: apps-cluster-client-cert
          property: key
