apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:6Vrm,iv:Kvj0wSGNxv9+c684cHfXv5HgsYbjtuINoShNg/H/Z7M=,tag:MUWTwwkvVdFNnUn8c2XTlQ==,type:str]
    password: ENC[AES256_GCM,data:99YipNNnVNNrwOxAUFKqYsj7AsvkN84cMApUQJ4zyCQyh6+bzVbNR5VMwCstP46Vmw==,iv:1v1DJRRuzP89SwevIpMbF5RBrf4KZFbCUY0BCjWPL3g=,tag:zYzGF+aJetLuCYjr4/JJKA==,type:str]
kind: Secret
metadata:
    name: apps-credentials
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYTdVbXBmdkJac0lYV2kx
            STdnQUR5Z3lURFJxUlRNTVlLYzEyYjY1a1UwCmRMTENod0xBNzB5bXlSM2JBeExl
            bzJqUGlrQ2dEdnQ2a1R0SmVlRXNKckUKLS0tIEs5NG0zS1BBLy8wZitiWEIxbnZ0
            THVjNHlYamxtNUlNNCtKYTNRMTZVNzQKCzIJUZDyRzHpR5NZUPsJ6yIXudp4V0RD
            waOVivGr+3tuai3l8RaFi2MsQjCMG4uKh0L1CpQHlYO2pmk0a6fXww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-26T08:06:51Z"
    mac: ENC[AES256_GCM,data:/PWnzbXOGnboNJdFSpqgJIwqLyrkfMJB0g1aVxflFHg7XUOSP5ueaaQwn+I2E8gK8SVQqcW8NbAygtq/W8hVrIILUCPDa/VvTTYOJDgnra/8PvbYogLKX88+anUwEIl3/KVN2qjl+/+S0U6phBTE8YQFuHdiXYWp0Gm68AgghpU=,iv:gA58+8UI9VfIZcBuHpWKWsPcABgfqVQGOaDoui86pUY=,tag:o3HKLi+va9LBIs2N9EWqVg==,type:str]
    version: 3.13.1
