apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:fDZG,iv:M797o/QR4VMF5D/TUKzHHpmg1uhvEX2QNWOWe7W3p6Q=,tag:bCg/K4MIseKVDAAhNUjCmA==,type:str]
    password: ENC[AES256_GCM,data:Y/6cS/ZKvxx2cfu5mH/MAh6ZK5tcIWRIVJSayKGt8rOFoA+gyIWUbJ9+uhv0dYmyTw==,iv:ksu277vfNFOv9YJic1xSVwYhGwrNImNVjwNNJegyDSM=,tag:k3Je0So2rqgUQFYZM4Ku0A==,type:str]
kind: Secret
metadata:
    name: app-secret
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRWsxUGRycXd5VU1uOGZD
            Wjlnd3RBL0x4M09Jc0MyS2tZZ1VsY21HOFhZCnNDbHE3U1haSm9ucVk2dnA3czVO
            STRkSWQ1NWkzcWhlb2xmK3N6bGprWEkKLS0tIEZ6Z29wYTNiQS9UL3ozVXlPb2ZK
            OUlKcVQ2dDBINll2WGdGSWZ6c1plRjQK8jVxybzSXmMNPaHJPXeUHjHiy1HeaY98
            tIPAfzDoScFE7j4qnsEBHNfiIKAI/eKkrrn7fdf1nb1BthoyABnhmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-26T07:52:29Z"
    mac: ENC[AES256_GCM,data:nVQNfEXZnTEMhUvvonDKKVc/X64wjLxuk+ifYkqVqgq3k8I80ozKFUq5+xvKU11h29YCXKFeD9estp49a1RVVg5A62yK09oBMNTT5hv0quI1VBBO2remkuppY3t/9/FlqtUMUj5ZW2ojGkgMplzFZ5xlaqOtoOxaX29YXn8FRMM=,iv:FdUmugFZo2L7UynTHZfmtDmFVQO9upLiApwjeJttFjM=,tag:CN+QoJk9rMFN9h3syKHD6g==,type:str]
    version: 3.13.1
