apiVersion: v1
data:
  username: ENC[AES256_GCM,data:vuB0,iv:5SfA/PvSoVgXJnrvAEHlhq0JN/VLpaXvF/3VWUYa16c=,tag:K62/GuNrYwmqRqXRLxz60A==,type:str]
  password: ENC[AES256_GCM,data:sj1/T+u8JQB/D2C9O1cTaUL6gIm/UrMPtmWLCNgn33v0CQBruh6TPhdxZkiZPdzSow==,iv:BsIgjcv2YnmoXSdutjqMEOfes0XLhOYLU8Db0epY1v8=,tag:ZAeIEDnfWOpVHc+/e/SQNQ==,type:str]
kind: Secret
metadata:
  name: app-secret
type: kubernetes.io/basic-auth
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcDJ3a3RodzcrSDRxbHBG
        Zm5xNVRvTEtVSHZkYlNGL2NEZGplSmtERlFzCldvSVRjcmpYSFBiWmg2UFZEa1dN
        VHZxcWxpU2pxZ1hBTmVUTCtMUnNNbEUKLS0tIC9tOGIwd3hCSHNSQlJEL2hsZG1t
        ckF3TlZuZnRtUEJ1a2Y0TnBlbzhCY1UK9Gl6GnSX3zZzo69zbNdX6oOo8n0KKJUt
        2tgHySvQhjYnDP/tBYbJHB8l4Jxjo/0tFdnZ4lCm2LnDaYcTTywjtg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-06-26T07:45:49Z"
  mac: ENC[AES256_GCM,data:QVNTEZqxx6JhxR09vDxwnb2bLxvq5+Dok7b+5zdY+LgdBhhztGTLpQTDAHjJvex10zgeDxHBxbNLwMpdPVpgq7eU7A6Ej/7IRU4F7w/nAfHlkPDO1Icycv3BcL7sGB3p18qifaP1ZGyc1yXPAFdMm2uEHXBnCj6s2MWKU1BO8UA=,iv:NtUOjqMzyZh4CbCs/qeCUkvWTCo5Rbuf/TavnWq+sig=,tag:H8J+Ghw2+rXmuPPHNg8nbg==,type:str]
  version: 3.13.1
