apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: media
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:Ip+IED37JfZFqyK6ZhLswjEN2OQlHpWdXsRbKoGplMs=,iv:/J5czyw7IV6lhW3/IiMyWMAEou9mJRdQLS9B4tT1zQE=,tag:/OF1L4YGiB0hr8hn/M4IKg==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:Lt1r8DhjgAJZfQ5YGsuC/C0Bn9K1rpdvoOkapaYVECn07FhJrwtkiMUTusuGeCw=,iv:S15c6C2f47g91AlPl0wlVHHP8TmM+BCk5Oboqth+u+c=,tag:iRkXb6/YoIwLkcbfpAnyfw==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:zK+TjrNZ,iv:vx6Lelzc4d4D8/YYeocyHbxB97ICJ5h9bPxYj//4fD4=,tag:oB2LXpRT9PdiwpLahBdV/Q==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:hiB8SB4f5kVjWT/8SkvTLCd7IFcnE1c12ylaCRpelMtV0Zc/R88h+N4=,iv:4Fb8FISOVEN0f1spiJcGr7DPFbTt0mZF+9mmUPOa8PU=,tag:4MuIPHgAIgcqureLanlE/Q==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:hWrn0aVWWkyED/g=,iv:xXCSr7GfI1HurBs+9FIJQycOTX1iEcvsclg4gSvX+wg=,tag:1cmjxrcWgG7HkMilJbQWqA==,type:str]
    SONARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:eDUVM7SC01CxQw==,iv:WYTGRiGzi997r+YUDbKqchk9OBZxzfP0nX3UdRJNtE8=,tag:pNlGgk5StyoD99gacVOXBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUjZrdWNGK1AyVjNzb3Zq
            a2FRc21WdzNWSEQ3cHFNWElQeGo2QjRjR25ZCjMrN3U5KytYQjRYb1MyeVVhcDRB
            bk1OVXZKUHc1OEVFSE9PeTBHRXRPSFEKLS0tIGtQU2xWTktsRC96dlo2dEZWTWdF
            YjFtRW5DblB5bGcvckRTV01ETW9kUGMK6z5DzoWfo9DXYi5v755Yngpq2wISt9z4
            BplhPySC4j2cLStZR3iSYvQNvSB2sK+rkswbnYXCwYskzr2mB9MoHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-24T15:42:44Z"
    mac: ENC[AES256_GCM,data:yfQ9gxHGafg8vDObKeaRdkm5Os6slORNtAVC1k2R+gt+tBzi6rrua4MFkMovk4102cKv0fQHRNe59bIBmER+PQRYiNb3YMNWy+gdVNqcdx4vEfgTeV6CkDWqoEZGGhYWF9junFdzztEY0NYxSa5owNzTXxnKKDWgptPEi9VwiCs=,iv:wi0EDf7lEqmaXoN/tui0KLT+dUlEQpQmud5cqV+K3b8=,tag:TL+6iDGPvwlwYH7j3G0oPw==,type:str]
    version: 3.13.1
