apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: media
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:/qcb0kZVMbNfV0SIKBw/anO5BK33KfPaB1VfoF3OPWU=,iv:01GSg27WmrNCX4BskIRP7ZMBx5Pl4+uZZHOpn2EEnIE=,tag:3z1U9oycbSv+xT6zIPa3vQ==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:PoXk9ktj,iv:tyMxLreTRIUg8eLMOE/1SDOLF2UYTitLC/Zh9a5reqE=,tag:p7w7wMiZ8kTvY0O14yHGvw==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:BuAjZ2IYZng0lHKXJqANXRHJCFcYzOz8RXjHkysv0qwAkka7uNOE9L0=,iv:oUeOBtU5jq7zhNJMpjnfRMu0tIKq7ROlLzNUn/vNnv8=,tag:DqFHt32WdFuzn6sk37Kegw==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:Jze0L5gUyCmYW3I=,iv:DE+9pl6x7lYMAb9QMe2XrDeyRBfo19hCITzC/saqDUI=,tag:vKq4mxbvgEvHF4p6u1Hydw==,type:str]
    SONARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:gTzOY7Us6APvbg==,iv:08xb60by+TcIASOqXaVloIrr54qmtZGsb5/GK7I8mFQ=,tag:j783TVU45B0r1T5G0yS7lA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYXZPSDhQejlNWjlKSDJm
            WVk2V0dHR0ppb2hSSjRzaGt4MlRTWTJYV0hjCmtaSXkzYUVvVEJLbEFYMzdhZE1M
            bWZoM0x1NWFlSEk5dFdueGN6ZkRNN3cKLS0tICtsUWcrT04yL3pJZU9QNzJ3ZkNa
            ZHBsaVhmRWx3TUgzT24wcUd3S3hib0EKtKQ7QMfMIakvhW2cR3HcainP6MFxVPGa
            Rkv97RyqsNZINfL4asJc0/N4DXLvUQx3zDyZH86BRowGgzTGI7IGTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T23:25:41Z"
    mac: ENC[AES256_GCM,data:EZ5XtzbPr18MuU7pViVJTtI1XE0l1zGe4/IVccZbjj5aPqBy22jashk9O0LsmeYkvuBHPeieJWPT7LtgbmSwyWtFp1RCzNysvv1gTN6GRwtKY13WKumG+4OfoU8tnU13zqj9OvHmhSxJC/fFH6B1jPVD3UEWDtOKs7dbbXG1BWU=,iv:3Hgl0vdGDyfIpDFY7266gh3txePwm0+7ba27355O6Ac=,tag:2RTipAdXTV7spwKVMgQMKg==,type:str]
    version: 3.13.1
