apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
stringData:
    access_key: ENC[AES256_GCM,data:NZ+ukmENpwUQMqwd/S8lFDjst3qbfvtfeFMRGUcHq3EPwf3qCeOZ/4mNQjxr,iv:F4077s0kqcMP9qjnTVaJ7G8uxGEHRuEs/3A3ZP2THLI=,tag:zDsLi1Wk43+ZdvwHXsThyw==,type:str]
    secret_key: ENC[AES256_GCM,data:Zg15iQcLkSw0tAGMU4rQ9kjsBHkKJyJ7DkLwUrOfh+AEW6d67DH+LMaPBMYEqw==,iv:131SV34VMtsm5vR6sDMlbt36zC5HnnoS/6dM+/d9jBo=,tag:nDbxmj5GRflf75YpP1UD4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRVd5WHBMb0ovSUkrLzVr
            NUxHS3pXdEdoNnFKcWFITXRNeVZGT1huTEhvCkJ1c1d3WFdPSW1nZmRMODdWemNC
            bVRUUXQ5Q2piSnFXY1FaK2JDQmFQM0kKLS0tIGJZdEptWFRwSElLNmxBSDI1dVZE
            MC9qVERzd09oM3Via2hGb3NtWWdNNDgKKKfiIsNpm/RuYKyLlZMxrKAczfSWW4ep
            4dJdyDELtZd61sKmLrr/dFqkZu99eSQyls/C5qBq3bJHQjP6WsQI3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T03:05:45Z"
    mac: ENC[AES256_GCM,data:qulM5b5oIHkDeO0KVnM0A7C+LnZQosyHntpaiCIleppbx4hKbMPqgRDY93WFy2SwphN3RqVoJplGq+up6H/ARcI+LE2ZxJGlBeIIw3XEyzf5qRXYcB/vNZ4smz1qp/sNfNlYPY/yYL6To3/csleSNIorXG51WljKF77KrML5cRk=,iv:kM67CfBefEni1RwNQrAzXIgOKnRn/pT4/vZRkCQ8C+s=,tag:eDvUEVy4d/or4dG7JHFx1A==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: rustfs-client-info
stringData:
    client-info.yaml: ENC[AES256_GCM,data:oQeKbeWk6smFjAsEzghSomJS0GqtBbZTD4VF6ufFnG+THMtdFR/S5YZvYDkuNY78hcAOqYFEs6NEdy0oy9j0Abae1P6e+n6XYMKhx75F0mD1M9iGaD7PzxD72SjphLLyyHi/6ghCtjYyHoFBBhGZu1d1wFwTmDyrncaEm5XHWOEXc3x6MJJPun5twVBRmbXBKA==,iv:d1ynJo1P4OyRkg+bL3rZovgDjJ6Hr3ATJGvpOByAnHc=,tag:eN9pTYEzsaneqydE2WrLSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRVd5WHBMb0ovSUkrLzVr
            NUxHS3pXdEdoNnFKcWFITXRNeVZGT1huTEhvCkJ1c1d3WFdPSW1nZmRMODdWemNC
            bVRUUXQ5Q2piSnFXY1FaK2JDQmFQM0kKLS0tIGJZdEptWFRwSElLNmxBSDI1dVZE
            MC9qVERzd09oM3Via2hGb3NtWWdNNDgKKKfiIsNpm/RuYKyLlZMxrKAczfSWW4ep
            4dJdyDELtZd61sKmLrr/dFqkZu99eSQyls/C5qBq3bJHQjP6WsQI3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T03:05:45Z"
    mac: ENC[AES256_GCM,data:qulM5b5oIHkDeO0KVnM0A7C+LnZQosyHntpaiCIleppbx4hKbMPqgRDY93WFy2SwphN3RqVoJplGq+up6H/ARcI+LE2ZxJGlBeIIw3XEyzf5qRXYcB/vNZ4smz1qp/sNfNlYPY/yYL6To3/csleSNIorXG51WljKF77KrML5cRk=,iv:kM67CfBefEni1RwNQrAzXIgOKnRn/pT4/vZRkCQ8C+s=,tag:eDvUEVy4d/or4dG7JHFx1A==,type:str]
    version: 3.13.1
