apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
stringData:
    access_key: ENC[AES256_GCM,data:q2tJx/Aa/HSK+gZ/FsALhxcVuodLfu0+kl2ZWxdzNFKSbuvTsdI3/2RsK5eo,iv:Q30K7M8EDX2vCYqXo/r/Q49sxFvXseKiTKcAo0fDsQI=,tag:FOL8K7BHaIAu9sWno0pj1g==,type:str]
    secret_key: ENC[AES256_GCM,data:c25k2kOIsMvIfYccqBW2gzqQsowgDLsr6CW/dnMT1g1NI/GbssKIkFi8z0KIyA==,iv:2gnmxGb/YhjwDQHLdQyDBwGu/z1iF6xFdyIenG+GZf4=,tag:3M2Rc9bE2NAXGBoQdHgrdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERFlnQ2VkTUpRT2JoZC9W
            aTRvUXByckI3aFJ6UVRsbDhTdm5XRFF6andnCkY1VTl1c2ZIOW9TeDc3VFJ6ZHZB
            N3VTZWVjSi9aT0dmck9ZWFhlYmoxSUUKLS0tIGo5ditwQ3pYTFd4d1B3N2JqM1lp
            NVplanIxVVAvSERKOUlOVEszbk1FTnMKCh393nj2zVin3MQHcfwFJcZqLYzHecGN
            x4Q/Z28a5VUWuKcbPyJAhW+VpjPTL7N4Da2cs9qnsQB1fwDIiV3W2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T03:14:50Z"
    mac: ENC[AES256_GCM,data:Hj8G079CWGnq8XxPt69tVETBrQkacPdV9hKmj1k8LKXPbyQTQp/xTLpONgvzL61jj2W4iAYSVIGgf0Zg55SUYhMSeX/kkVSkvCvEPcl5OMe1zgHc0nNmsSdGhyhroPbK52dnOCy7+TLYDeAlJXiYG25HgQYwvi+3Po7uZ9VJjF4=,iv:CCPOgqSaD5hbn5QFyFomYs0NnZQKEF9n0SZ4W2UYwBw=,tag:04RWz1InMluKemAEsQn1aw==,type:str]
    version: 3.13.1
