apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
stringData:
    access_key: ENC[AES256_GCM,data:b2Yc6SJLJeJRSboQIj4UpRk2BQLO3Cy4o1kFaVV2OpGkKZbsHTNQWJtKcQlo,iv:4+JmVt5HCn3IOCOQ9tUVVg/qjFyHDyqc1Ha3jyQy3vw=,tag:aSKTZD0apoMmKSZMHFZZ4g==,type:str]
    secret_key: ENC[AES256_GCM,data:gDC1m5AlhaOvPq40J2zKb8piYxmqbQpX+YDgNb0GQp88ALtmkueDMDsfs0LNdw==,iv:WDr0qRKOdM57GsSvpu2OkJp2ruzy36xNlj95RVwQx3Y=,tag:/2vQaJMLXqV2joFZcdvqaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWmNWbVc5djlibWhPVXBu
            Zk52YUt1aVdXWmtRYW04cm0rVVl3S0c0TGpRCmpzelAweVR0bFM2Vlk5SjdpbzNi
            NVVCV3c1UEx6WXpjbW5iQ044cHdKM0kKLS0tIGREUG9TOU5TeDNsRkhTeGdCclBR
            eEl5T1hwWUlPNC80SVBVT3QvNno1aVUKkLS6+7O8yyGzfdPnzM8HJ9WV9R3KGcHb
            dJWHRuuJJ2JpJsRhzSa9/SOtIzxw9JKzmDo9qPtmi/kydiCgA8+dyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-20T18:58:01Z"
    mac: ENC[AES256_GCM,data:FAEsE3q+sN9Rdyx1v1E8jICrcyQSxkRc7Rva1So0X+OmaxalEb1pBjK9ED4pkCWFD90ybCWfJE1uXZ66Ymf8w/XPKHRtyF3jSDoZ1y2R//B5YaJDavjJ/GmL03mXt0FVfiBz4PrTXAT7LhoZoyfbefy2yr5+HXk7draED5H+log=,iv:1w+nVEEpYMsZ4XzSheRMF0Uk/nVv4dAjCrDtbjKyPv4=,tag:zsF6Cr6yC2U8YcxXK4RGQQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: rustfs-client-info
stringData:
    client-info.yaml: ENC[AES256_GCM,data:+0i7RCTavkLJI3bSTB6ULKFjOPZkzXjudY3BBVAtHnrFLaPDnQ0vDtOWYjDP0pC0GNjOUkCx4jUkHytzzZBPJU5Wjiwl/+geHnMEJiji03Too5MaJNNtVolA1VlRhQqMPHOtdKs5CbJ83dLDyZFJyLuxQqx4rWHXUBxfdtw70u2F0jwu6OwlkB8Yzs9MTPs0Lw==,iv:384t22pbZjdO/p9r+7VN48bFDFy4YzXOL8mmT7eZRCM=,tag:L2p8Ggd+7enjt594Jrxy9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWmNWbVc5djlibWhPVXBu
            Zk52YUt1aVdXWmtRYW04cm0rVVl3S0c0TGpRCmpzelAweVR0bFM2Vlk5SjdpbzNi
            NVVCV3c1UEx6WXpjbW5iQ044cHdKM0kKLS0tIGREUG9TOU5TeDNsRkhTeGdCclBR
            eEl5T1hwWUlPNC80SVBVT3QvNno1aVUKkLS6+7O8yyGzfdPnzM8HJ9WV9R3KGcHb
            dJWHRuuJJ2JpJsRhzSa9/SOtIzxw9JKzmDo9qPtmi/kydiCgA8+dyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-20T18:58:01Z"
    mac: ENC[AES256_GCM,data:FAEsE3q+sN9Rdyx1v1E8jICrcyQSxkRc7Rva1So0X+OmaxalEb1pBjK9ED4pkCWFD90ybCWfJE1uXZ66Ymf8w/XPKHRtyF3jSDoZ1y2R//B5YaJDavjJ/GmL03mXt0FVfiBz4PrTXAT7LhoZoyfbefy2yr5+HXk7draED5H+log=,iv:1w+nVEEpYMsZ4XzSheRMF0Uk/nVv4dAjCrDtbjKyPv4=,tag:zsF6Cr6yC2U8YcxXK4RGQQ==,type:str]
    version: 3.13.1
