apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileflows
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fileflows
  template:
    metadata:
      labels:
        app: fileflows
    spec:
      securityContext:
        sysctls:
          - name: fs.inotify.max_user_watches
            value: "1048576"
          - name: fs.inotify.max_user_instances
            value: "512"
      containers:
        - name: fileflows
          image: revenz/fileflows
          env:
            - name: PUID
              value: "1037"
            - name: PGID
              value: "100"
            - name: TZ
              value: ${timezone}
          volumeMounts:
            - name: temp
              mountPath: /temp
            - name: data
              mountPath: /app/Data
            - name: logs
              mountPath: /app/Logs
            - name: common
              mountPath: /app/common
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
      volumes:
        - name: temp
          persistentVolumeClaim:
            claimName: fileflows-temp
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: logs
          persistentVolumeClaim:
            claimName: fileflows-logs
        - name: common
          persistentVolumeClaim:
            claimName: fileflows-common
