apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media
  name: fileflows
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fileflows
  template:
    metadata:
      labels:
        app: fileflows
    spec:
      containers:
        - name: fileflows
          image: revenz/fileflows
          env:
            - name: BROWSER_START_DIR
              value: /apps/media
            - name: PGID
              value: "100"
            - name: PUID
              value: "1037"
            - name: TZ
              value: America/Denver
          #envFrom:
          #  - secretRef:
          #      name: fileflows-oidc
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: "4"
              memory: 8Gi
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: /media
              name: fileflows-media
            - mountPath: /temp
              name: fileflows-temp
            - mountPath: /app/Data
              name: fileflows-data
            - mountPath: /app/Logs
              name: fileflows-logs
            - mountPath: /app/common
              name: fileflows-common
      restartPolicy: Always
      volumes:
        - name: fileflows-media
          persistentVolumeClaim:
            claimName: media
        - name: fileflows-common
          persistentVolumeClaim:
            claimName: fileflows-common
        - name: fileflows-data
          persistentVolumeClaim:
            claimName: fileflows-data
        - name: fileflows-logs
          persistentVolumeClaim:
            claimName: fileflows-logs
        - name: fileflows-temp
          emptyDir:
            sizeLimit: 100Gi
