apiVersion: v1
kind: Secret
metadata:
    name: fileflows-oidc
type: Opaque
stringData:
    OidcAuthority: ENC[AES256_GCM,data:Ok9+,iv:aMymwhnkqjq7x3SHmqgSnOqqlDWo5hjKpGyYP05Qong=,tag:AluP++MmtXw0AFl32mFVCA==,type:str]
    OidcClientId: ENC[AES256_GCM,data:Pt9u,iv:Ce3viOQzutpjV+UIFCcrBW8PGpbaZZbj+MFA5IXv1DQ=,tag:zpdipkLKG1KTSpxI5XCJtQ==,type:str]
    OidcClientSecret: ENC[AES256_GCM,data:+Hlo,iv:ZTpKETZpWIXkKz0b1i6GWqLxrh3Twls+z6oSkhC8hzw=,tag:5xxUoAfYqI+LNaDdOBNTOg==,type:str]
    OidcCallbackAddress: ""
    OidcRequiredGroup: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWERhYm9XdEV0VUpIcXA0
            a2QvTElyWDRPMWJjOFpNZDR3RnFPb0F3S1d3CmJnUGkwcEdaZWpqa1I4STkza3RD
            N29Pc0R3MVdBNE1PNHpRS3ZHblRMdHcKLS0tIEhONXg4eFZ3M3JXdnYyeWdGWmVm
            eE9ZdTdxOGQ0NDYwdlhXV054cjh6RjgK94IgbcfGMQ8iq3zh3E+ZvZTZRu6oUGVZ
            Fn3R3FYmrs5KWaNBRVlrGVOBE4mY5oZY4NkmwQOvlkRogQ8rLZ6Ixw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-17T02:38:14Z"
    mac: ENC[AES256_GCM,data:LSdWYg3f8yikL/A9RT6eyCV4axWQM277jsDhnwW32bAahJNeF4w4nFP5qfi8iBRoLzUl0jvHw0XhcINoSbK0yJl94Qaa00KvHktEhhdg8DRyhrl4y8ZpUvp7I1ua287sjhy7bZS9UutjZsS5J3PlczsGy1g9/3jw1sjiU3YhCm4=,iv:M0GLNeHUdIGc6fSk5Wu9++KFWgetGPm97rUr18oOllQ=,tag:160W8F9Srpp6wQk9D/0DOQ==,type:str]
    version: 3.13.1
