# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sabnzbd-config-seed
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  sabnzbd.ini: |
    [misc]
    host_whitelist = sabnzbd.theblacklodge.dev,
    username =
    password =
    trusted_clients = 10.42.0.0/16,10.43.0.0/16,
    inet_exposure = 4
