apiVersion: v1
kind: Secret
metadata:
    name: tautulli-secret
    namespace: media
stringData:
    TAUTULLI_API_KEY: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaVNrOTZZRUh0aTRDVWJj
            QW51c1lFdVdEbkhTbjRzTEtOSHRUdXhZMjN3ClNvNmRxMTRhMldKNmVvK0NUREg5
            U3NpUHI3dE1PRUhTMC80MXl5RmxHR3cKLS0tIEhTeHVCdVNDMG1wMXVwQmhHRnpW
            U1ZaTGV3cDgyelRvWHlQZGE5NlFjcHMKGiyTEsZxKE17fQ8zfiMidk0IlmkIhGED
            9kjkuZb2iICc9EPRZ5rRmz3HZ7nSKnCl7T7j25uzamg77uqISdz+SQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-16T02:16:12Z"
    mac: ENC[AES256_GCM,data:Cex8A50DTYWT4vzjdZe1Viv9imS2bn1H/v/oZo7r1UWHSCtLUzT5GDSEr5YaPjwC2ldWlnt1sI6dLr+3dH7Ti3LF5Bu5kRzuLqtcTP5uFSWB55G470c1IEu9xoqqCoiqBvRvII8Qav7nRWrzMqSKq5ig2clupkCFJR9h3tvimp0=,iv:tXXgD6rjd5vrXn3fwqB2vyDQpH//fPUFwg8p0l7ZYds=,tag:+ts2vhB3D8UXp4fuN49W+g==,type:str]
    version: 3.13.1
