apiVersion: v1
kind: Secret
metadata:
    name: fileflows-oidc
type: Opaque
stringData:
    OidcAuthority: ENC[AES256_GCM,data:J2Nm,iv:Vtlo3AmS5cbth+HFAN5us98buJSgdPp6PkspnIJRQiE=,tag:AMJsrrF/U6eHY5utoIzFIQ==,type:str]
    OidcClientId: ENC[AES256_GCM,data:oAJ9,iv:uFsYoxexUEbr5g6cOGdXr+cQMl8DN8vV91CzC4+Ykc0=,tag:DC11KfA44ZRiDM0NLWp4lA==,type:str]
    OidcClientSecret: ENC[AES256_GCM,data:Brx5,iv:LseK+vA7XsltDkYyusFrYt99F2XgQlN+A226XTgiGiw=,tag:PF0n1s9a/WbNEU+rAvWv5Q==,type:str]
    OidcCallbackAddress: ""
    OidcRequiredGroup: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MDF1OGdvbHQ2dUIxVVl6
            K3dGMENxaWFDTWY4anluL2NaMSs5SExpclZRClpFZk1iMFZXME5GejFndmRONStM
            bmRSelQ4amNpdHQwOXZQUnh6akU5QUEKLS0tIHk0YVd5UCtmK1BwZGk4cDhhMG5i
            T3R2eVFzN2lZT0dQbmtRcnptS3VQREkKmk0DOZ/OhjArkTCWO9CSvJ4M9Du75AhU
            8OkOar9tdypUfUDQaRD69Mqdv6zx04wQEKpE7C1thYWX+gIclj7D6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-09T01:16:52Z"
    mac: ENC[AES256_GCM,data:mEL01nakcV8Fbg7B3ufr25wY0di9YuoduN4K3dhVw87fCfcCCgFlCqh5a44JEGrkBWWwfiW4I0FjkIVISTDK8gslHuNhTq7/BSG69fm2DgRBfpQx8IQaSMHRKgZnkYO2pIholitizQFGExli22FeAb5NHs6WtPpqPR4jC3227y0=,iv:/wnjpFu+i36sg7/meZlgWaQzhXLn/yvj8acZXAYq9wM=,tag:CiOe1r3FRl+tDqOsSvkOgA==,type:str]
    version: 3.13.2
