apiVersion: v1
kind: Secret
metadata:
    name: notifier-secret
    namespace: media
stringData:
    APPRISE_RADARR_PUSHOVER_URL: ENC[AES256_GCM,data:CeIjEy/TOi3G+bzlZ1aNqF380qMWRGOcz3AhdDNSFuTQAhGFfZYUadVrON8syKJPu4U+Lzl7kXzepbhHRw==,iv:NBsfBei+xUq4EgIWlmbvlsKIm78/4sz/+Y0UYIv1n5I=,tag:bRMbBB6Vc4zggh4WaS1a0w==,type:str]
    APPRISE_SEERR_PUSHOVER_URL: ENC[AES256_GCM,data:jQPg0OLA2FNRQj8ZHOsR33wZF9Zzi4YBWFZTpuwkNkT/+FuGNSoniCmxnALnMNYpSIYmxDLriKgBcxbv,iv:Tr/173ugF7Ycg1RbcGwxJcbsy0hY6rWqJpR6I73IP6k=,tag:GOE6EJ8msDMWwS8NFFgqNQ==,type:str]
    APPRISE_SONARR_PUSHOVER_URL: ENC[AES256_GCM,data:RITdRcueKHNGulShhkIgKMovfpdHNFewFiYQl5U4dkiObwxM5xOR+LPLiTEB/UYOQTZTTEi6KfiESaRTDw==,iv:x0pE36yVDArTQNg93v+Fb38SAmQ5vGEBcPhPkajQE6o=,tag:xfqjkbkrwB0Dy9TVn3opPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ3ROeC96dVZkOHdQa0lW
            dGRTMldxYTRQSXpNaU9MdVFBU0w4RjNLL1FRCks0WFowVjQzQ0JYdUlPZjlOYmVV
            MFF5emNFeDZNc1NIUzNSWm9XbTFIT28KLS0tIEpwWlk4NU83U21VYTZuRm1WNy8r
            Sk9NVzdDQ2E3UG16bU5Ob1g5Vm5ZNncKFQg2I7tHe3kX+Ry93ZuidWWBgTHQiqZt
            cOhPn38T86tpOaiCbtanojAaIq1rd6I1R9rGXy5zEYtRDayur+dSmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T11:22:55Z"
    mac: ENC[AES256_GCM,data:lRwnkln0cPLPRnsGmV1QTGq+VYoyYda+Fz5p/eagdCNxfRs880YUqNejEK9Em6h3HFFxOIg7bJq6TLL6Ez1FUAvXKfHWSkP7XfSqUOYdh7UTIuT5vs70rkooSlqLxJB831XzoHWBs1ktzC5UtVp/76Jr7G0gcg+Dn9yqJTPB7mA=,iv:5P1Kif+ZRFtYP01AnYL+2hsIm3PE5m1y77KofZgwZRI=,tag:FgGwoVcpj78Ru7dROIs9Mw==,type:str]
    version: 3.13.1
