{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "generate.fullname" . }}-secrets
  labels:
    {{- include "generate.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "generate.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.database.passwordSecretKey }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteKeys.dbPassword }}
    {{- if .Values.azureAd.clientSecret.enabled }}
    - secretKey: {{ .Values.azureAd.clientSecret.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteKeys.aadClientSecret }}
    {{- end }}
{{- else if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generate.secretName" . }}
  labels:
    {{- include "generate.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.values }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
