apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: media
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:unMel7U1SqWJzCQxsVVwK9l1M73qRNjBNRyVV6zQVIA=,iv:qRYLeREbkLKlqrOpFkX/nawL+UL4L+qgWfP4Ci9si5E=,tag:993cHWKk+AZvBfPEWtTbzw==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:Z6wC30JS,iv:Iepz2iIYd5ieMmKCfE5u1/6nKtKQSVHTVyoczQ0YBdA=,tag:Z3FckA4Gyv1ATfooJPJSJA==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:CRzFshod22XAmu5ifq7ZLGdQYQyOyJAhdSAR3XKJVICXXRaDZTNNe6A=,iv:Ue8VWJgcYJP5XUoa4kpfkFbuds/mKIUOnudPkQ6kHjY=,tag:w5CNxXVxZFtE2BFpO2h9nQ==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:YML07LLv,iv:0yDphe4oqP76cTu4H8DR1viWQW1g7RW5g6kunD+bU9k=,tag:Y+lx6Xc+i1usUj506eyL4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bU1tdGM0V2VGUEt4VEtR
            dndpcEFCVXF5dXBOd2xkMy9jUVJ0MVQzalRZCkRhNXFKZ0pPRW1lMFZIUVhKQkF5
            dWZCMWRpNGxNb1RqMnhBb3ZmYmJLVncKLS0tIHpCa1FSNmtUa3I3UVVPeTZtdG9O
            eDRFZFRnT2FManJkaGRMZTIxOGVrdjQK4lThkrtCEO21auavUugNEvwvzstYBrZO
            sOO6v/wsR8/hFYNsh091LeczK9MSG77KH3M4oW1Jx3actiFqFDgYew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T23:23:10Z"
    mac: ENC[AES256_GCM,data:n1ApF7hjahNxiA/kYQddD9nNKyHqGsjN6+yvU7mp1YOHmvv8y9xGProAEEn4EOLo37aWugJ2STcuiC+qQzmA/5wfssIAYxyz7JGbiyai3smYawXgKXDGDjTTvJmo2b/lRezDyy7p7vkyaQXmu1AHGzN1EQm1C7n54JBiI4oLCO0=,iv:2F56CWIUZFz12VrcD+RdttQTptwr22JLBnj3eHXwiKs=,tag:bU69bks2dlYZiYYZRngUTA==,type:str]
    version: 3.13.1
