apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: media
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:Prg6993CnDLmIgqmMFoKf5jR2bDfAHp3XQz4fScAunE=,iv:1g/oTg9asNOBFeFUzhZNvfvAUIHTaPjPRGiT4oIDx0A=,tag:d85GJB0eds6gKRCl+TtOOw==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:vD/oHawSvcLBPtHcHGSQOP45Uc/RzVjRvM4HqERAJBk8PeHBx08zyVwlWtQLJbw=,iv:EfA+GOfbOlLqgyVVl/7MMOYYuIMHb9t6JCuQUTpv4Z8=,tag:TlbSJ4rrsqZsvkNFEmq5RQ==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:7YaPxkeN,iv:nEF+YlkcLRL2yBYEtdQKQpVQU89gmDYxw+y5E5kj4Ak=,tag:K5W8suMT4y28/vhgJM1+RQ==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:b59ilCpmqJoEAwVgc+/GKEXMJwNFt58oJN5mej6dH5j7z0m3LDZ+DCM=,iv:cq/bEoJzI/9Z5vTrVBXGlImht+WkJBKlcrmSNl3Ty8Y=,tag:7+ePLvlTy3TK1Xt1xZaeMA==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:6R2MwKZE,iv:7uLlbLkHsV65zmeUC0gWmfZf8GyBhjwdvVKQKdH/mgk=,tag:XBudTLa9gfHrNYOtLi6Oiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUzB1bGdJNG0wR3oxSDlK
            b1pIQjBwY05WbU03T0haVUlEVzRjU1dvNDNjCmhjWUFRMTFESmRRTzVBQ2NFd3Yy
            WHZ2Y2RuZGVXYjVXeUVFRUllOHRNQjQKLS0tIEVBaEJ0Qk9iYzZYWENaaXBRZlpJ
            dW1XN0dhc3E5cmFNQldKdlhsS0hSNjgKJ5UspXF68CXAHJkGKr3wTyKPHniXRx/N
            3RWdS1M7yKj3V5X7o7c0IlSmwcb62xwNPFjPP5g4ltBCA4uLqCYBAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T11:23:30Z"
    mac: ENC[AES256_GCM,data:BrV1kdK64qgfnxAimhEuvunR+idPMjLe3Qv3qLBDjro99RmJ//ZW5kEneXlH08Be1I1erW0DTHtjxfT4jg5pijBzbJYGC+Mxcg+glH7GPUykuSFWH9OjOPIUNvYIJvDKIoZRpY0CF14i25pA7nCBk7gxPziPMuMP8Q7oS9yHAy0=,iv:JKJGEceaBuKOfoj8IX5gO9KWD/ZKd+ZUbGyvab5XEbM=,tag:9Tg4YPhhJmx/Qy7NAvOrfg==,type:str]
    version: 3.13.1
