apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: media
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:CkySj11ZrD3IlmZTm/1FWKaZdzjP0WICZ6YG43XrYi4=,iv:NjZmldKDAiFFQ+bmMy2Lc0QpA7U4k6h+iOqejA6EO1U=,tag:dNRelXcs8VZFawAQY7FYjA==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:OvJbamzf,iv:Bg1AGPVk/ei0RI+DTXD5OrmnQwyzA11eD58w/WnxPtw=,tag:Z6NTEO+RLz+6Eh9XtHUINw==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:v+aJxxDqv+ohLge6KXIEBPv3MJiMhefqv9/M5xmpgIoQaYks1wDExT0=,iv:g77Rc/7RwfmkCLrxjah9Vx5d126WTRgt+CgkytHg18U=,tag:NMkh/n1vSJJBuVkg3CUY7g==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:Tt/5ORfQ,iv:ygW97euCziQpYc2UBTcv141rHABULV7NKNEsHdvX0xU=,tag:0Fl5S952IGKnpw+F3H+jdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSGpMWEZKMUNmY2Uyb2lt
            TGQ2eWdaZnp0eERyUjZFMmxDTzRtUW1UWlc4Cmt1NlBGS2QydUFLVHBaWk4rbHg4
            NFlmNU8xWlRaTDN5Yjh5N0xlSFE5eWsKLS0tIFRPMloyK1Ryc3NPcmN6U3BCSC9s
            WXJIa0VNYkxxU25jTnBWN3RFYXFQWEUKU3GxGPJT4YHU121jYqluZGzMtK9A3oNB
            +Tp+tlJWoBvA7aNdMk8dy+bfpk4BQWz0oN9cnDughK+6hSSYOorFmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-09T03:59:59Z"
    mac: ENC[AES256_GCM,data:7oH5rXrJDb7da9mx4JJbMhE1V2ygQSQvlRppPjwefJHXD6ai5/R0vKctiZht5FfXnkCN3xLPksIWlI8hvYKTTNs6O6aQm4lE8MRiiTsNpVzFt3wNCabkI7rCNEyI3WtKQbATyDVLGDanF9CDalXnr5vrJgmYiJN0nTflIy6h4f8=,iv:Dh5YwIl0DLJmREhYpXs7XL0bPOOq9VzMAZr6jBjKVXY=,tag:UFI4pkqNXqVo/6pkMTdURw==,type:str]
    version: 3.13.2
