apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-external-secret
  namespace: cloudflare-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: cloudflare-tunnel
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: cloudflare/api_token
    - secretKey: cloudflare-account-id
      remoteRef:
        key: cloudflare/account_id
    - secretKey: cloudflare-tunnel-name
      remoteRef:
        key: cloudflare/tunnel_name
