apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-settings
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cluster-settings
  data:
    - secretKey: acme_email
      remoteRef:
        key: cloudflare
        property: username
