apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
type: Opaque
stringData:
    cloudflare-account-id: ENC[AES256_GCM,data:HjWWTS1t+F8r3s9hZ41Qc4/TvST/WvsIgw5GURZ/Omc=,iv:FT5i9reykvYItro2sejcwMVgQDkOYaJKaPIkjZ+sB5M=,tag:W6R29cMmGtPeFuGIDokaTw==,type:str]
    cloudflare-api-token: ENC[AES256_GCM,data:zZlU2yXQ3d/YbAjmJyFTVthYsLDcG1/iv59E9af5B+q67t7VV0XkKel7EyFVZjFd82fpl8E=,iv:9okoJsp26FH3LviU8nKwERyV8niUQhgp7+dzDZPZnuY=,tag:VizUhIEToBmWBcURIY0EEg==,type:str]
    cloudflare-tunnel-name: ENC[AES256_GCM,data:oC8PSXcnVEapUQ==,iv:FfCrrOTe8TEutimz4wPLc4BgNsz5b1ohuD+Dy29AFFA=,tag:SMbt1fWmoCQJbFqJOM98Lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndXBwVlBvY0NiNG5WZlRH
            WllQOWZ5dXZHNnUzUExnbFdURnp2MnhiWFVrClRzemVKNmcxdlRKSSt4US82a3py
            SjJ6a1IweGM3M3Z3anR6UFNOLy85blkKLS0tIGhQYWlid1d3b1p1WU9xSEpNUGhI
            V1FnTy9JelV4SExKUUY5VGlFY0oyYVkKvM+I+Ube8bUi+ya3mHjKAxtpV024ZCd0
            sgtJFS6XYBcop/z0DBE28V0ivmrzrAfPkFzza1d9/KwwxRRPyZ5ECw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-24T23:08:00Z"
    mac: ENC[AES256_GCM,data:GKt7kjUAIZqTJGPz/XC5vB0uHH6phl3FA2OS61a6IASz6AZ7ErE7FC+iQUb8TLLpzeTyByQGyMHMe3imM3DAZhAekxSvsssavvmowUrdOo8snZxxlnyuTDC1ib0ZDHIX9GfaXJKnFCDSNltWU6bKi1s5CyxRM5c9zApbsa3ZyXw=,iv:LqCjaXi1kc4vBv0LjsE0yo4mXMsXuRkls0I4mEBjh7M=,tag:Lf6KInMtV7D2oCxsIHtG9Q==,type:str]
    version: 3.13.1
