apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
type: Opaque
stringData:
    cloudflare-account-id: ENC[AES256_GCM,data:5/1TzPcKCljn9vEDXlXMmXySTiDjqxYOxJ4FE5F26/U=,iv:Rp5FjKciwY5IYxnXiTXcL9otPaXZMOkPfiEI2NBgRvk=,tag:Q6A0DTnxe9L7uGKgeX6N7g==,type:str]
    cloudflare-api-token: ENC[AES256_GCM,data:BEcMk9aBvnFEO9n081bWPWtJJmRtGbuNloQnRvB2XJvZz9EHZZEJLd5IE0E2pInNn9BIEnI=,iv:udunHT54VFFROUlFgkobziiuI1Zu7GFj5qWSJfDMyxs=,tag:My15CYPrl0QFoqYZ7Mmruw==,type:str]
    cloudflare-tunnel-name: ENC[AES256_GCM,data:uZLHHdQbcQ25roqGnPXyJiVG7jU0fHs=,iv:LAyFrWsJ9mYQxosWl/LsB2fsJ/Qdhd0uWS87SdtTOms=,tag:LDIbQZJ194MzHySZX2bHlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZHdqTTBlMER4OTcxRVBX
            T2xtL0dNT0EyTXBvWEJTZGlMSlpGZzhUNFJRClJJSmg0YXZ1TjVVRURqQ0FQdGhy
            dkxaM0twOVVIUFlsenJLQTQyNUxFRzAKLS0tIDlTSml4Q1k1QUFpMm5Ob1l2UkZx
            aWRvQ0lWZXRucE5WL05KQThzZjlkMTQK/rWo5ssIxqSr0zKiNHT8Raaj/q/FHigB
            z1CcendW0gJgdyqYxA6zEIEZcpqBMC2xIAcwM43iIZoLe5VDVaFVjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-24T23:29:00Z"
    mac: ENC[AES256_GCM,data:6iIMU/FQRZIh3OiWzJgY8f7BT1NAzUaA5gC4rKebMPbGFXJ4ZneQApEsxAhrOFIqJgKpgc4xqhRYjXBwEtNgBB5Yr29Jt64M58fWJWtBpsdRcgIElUiBH/MQNzzay+7sf7IV2ASafTKa0aJuYYEhvw21HYH8giJQ4aBWXc4wF3I=,iv:DyLxmKWBW/503bkxr9TwCTwGwjuUtgvoumDDz0WISo8=,tag:M0f/njaTlTtVvGn8XXuerA==,type:str]
    version: 3.13.1
