apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
type: Opaque
stringData:
    cloudflare-account-id: ENC[AES256_GCM,data:a0cckEpfA7KhJMx3WFTCTNCldSIY98nLh6XOsINpImQ=,iv:4nDKEa6QksQps/08TAgDlbNBB3NunPVlcmAHHu3ATh8=,tag:WiwVrNHxFqbcFJpFkcgHuA==,type:str]
    cloudflare-api-token: ENC[AES256_GCM,data:AASEc7C4yrWuW/VLhTL3JLvm4BvyqyQ4coFXnYK0dJr+EJQ30W/+you+AXNN7fEJYrUIfFs=,iv:anemG2p53VrmBSSdul9AeBAE62+jUPdn4CeMxrr7+TM=,tag:9TYpihRWlAWz1oPnxMUmgg==,type:str]
    cloudflare-tunnel-name: ENC[AES256_GCM,data:COp1SQzO4tmmKw==,iv:GpyMzgL8uu4m7K3Jr65JlVsKJT4IEQ2mfgww3rScT24=,tag:JA3l9Vltpr7uIkc4V7JG1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTVhxUG1GaWgybTdCUlU2
            eWFmdmM3S29xUzFoTGF3ZjVCTzdYUEI2S1JFCkkwYlhRNzBhYVJ5YmtubW5VSFVD
            YlRIeWpHNjRkR290bVRCd2hqdDh6VXMKLS0tIGRUbDNHaEdyajh4V2JjZGhHVyt3
            OUVGWHBBRmJaNmdlNWNWdkxIZkFReEUKCcFzlGzEB7k4b5vfe7AhNwVHYgJGJiIP
            ZaUucc78xET3h7VpGq1+pY/pwaIQDXfGG4e+wd+wWHlCdTWP81XxRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-28T04:23:41Z"
    mac: ENC[AES256_GCM,data:GIMIH+9JMIGT/HSNywK0dPt7lUYc3noA8TTFcrt4K1zHzywIJhPmLw4+8etv2PPzC/2EDNUVXSCF7KKW/a1Gz8FEqFqk9XEqAC5HN55p2adUgSC485ewffN/hiNY6Lllg7G3EoHG9ARtUIQyia8KviACjjeYHHnq6CjBDD8sVRQ=,iv:Dk1oGzqqwkyRNEexfko6rs1Hr+Uf876EHGwpuDji6rg=,tag:4KN+MW6HTrEyYiFMK0cdLw==,type:str]
    version: 3.13.1
