apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      containers:
        - name: calibre-web
          image: lscr.io/linuxserver/calibre-web:latest
          env:
            - name: PUID
              value: "1037"
            - name: PGID
              value: "100"
            - name: TZ
              value: America/Denver
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-calibre
          ports:
            - name: http
              containerPort: 8083
          volumeMounts:
            - name: config
              mountPath: /config
            - name: books
              mountPath: /books
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: calibre-web-config
        - name: books
          persistentVolumeClaim:
            claimName: media
