apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: calibre-web
  namespace: media
  annotations:
    gethomepage.dev/href: "https://calibre-web.${cluster_domain}"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Ebook library and reader
    gethomepage.dev/group: Media
    gethomepage.dev/icon: calibre-web.png
    gethomepage.dev/name: Calibre-Web
    gethomepage.dev/app: calibre-web
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`calibre-web.${cluster_domain}`)
      kind: Rule
      services:
        - name: calibre-web
          port: 8083
