apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui-settings
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: qui-settings
    creationPolicy: Owner
  data:
    - secretKey: config.toml
      remoteRef:
        key: qui
        property: config.toml
