apiVersion: v1
kind: Secret
metadata:
    name: qui-secret
    namespace: media
stringData:
    QUI__DATABASE_ENGINE: ENC[AES256_GCM,data:bWwztokyX8Y=,iv:bthx4ccTCo8Q0lJplhfSRTdDO1k0isBFT8HzLuqKwAU=,tag:Gg3GBys71wzG0pxMpe3csg==,type:str]
    QUI__DATABASE_HOST: ENC[AES256_GCM,data:mzrFdJceo6WxBkuZ6J+Eup5g9CirTc7i9SC3l++P8tW6rXJOSLJJgoGuPWBB8N0=,iv:PTPjKt7kWOZmxJljMDzerclmMwx3p5+5jU3EqhXrP50=,tag:5pSun34kIAlDwR5xrJuTnQ==,type:str]
    QUI__DATABASE_PORT: ENC[AES256_GCM,data:Ol/HJA==,iv:UumZROoSeOSTjMQCnDi5Fa4+ne7ZyI83PMFw8QzEzb4=,tag:tnvvDWwZurnbdVDB6d7Tvg==,type:str]
    QUI__DATABASE_USER: ENC[AES256_GCM,data:h+56,iv:cNMzpJvI5M3VaXd022YrrSLwuLuX/rvR2EjH16Wq/mQ=,tag:xY8MdIdQfBIEaBVlpL31iw==,type:str]
    QUI__DATABASE_PASSWORD: ENC[AES256_GCM,data:TjQCD4XH3X88vey3JR/IrKI9MD1Z8/tLmvQMHYkVpSDBtaRx/B9XfpVjMg==,iv:XH4gNIYa0tPoNJ7GwUOKZuutK7GDAZc5GltSN7YdDjw=,tag:MqISsyggX/c/JWeDlAhxAw==,type:str]
    QUI__DATABASE_NAME: ENC[AES256_GCM,data:rlA3,iv:ptiW8E5up7HY/XhPNbtqQLBJ2C/mGVXv5n5tLMWMdiw=,tag:isoVOnRtGKMVZ7oxHDybvw==,type:str]
    QUI__DATABASE_SSL_MODE: ENC[AES256_GCM,data:PZsb4unXmw==,iv:jhuIn2dTdcwpgpYXHaJ8OJRZFzzrsM8Wm/EUHONhjeI=,tag:7oMhzZseQL0CdsEdeTvCwA==,type:str]
    QUI__SESSION_SECRET: ENC[AES256_GCM,data:q9YcYT8GpSoYhhCvfpGcJhRimMiGIcS0LWDV3YDOtXyBLvP4b61FSgNr4UU=,iv:ocKB6W6h3FAYKWZxJmp/QxeBgN0y7XlaJKHFdZ/R9Bc=,tag:1dwMlnaOsC9meTKDmFDVyg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcnQ2TWJTcUJFTlQvT1J5
            OWR5Z0hvSHZjdkpTSnF1K1U2VE02czg1NkgwCjlyZzF5TEo1OEtJQkxyb3BKMVoz
            QUNJcXY5MjhtRGNOenNxbWpnWjJmZXMKLS0tIGl6UUU2S3c3M0VwaG00T0xNcHBr
            NWtGY0dSakpCR0krOXFoUVhCMGJqUzgK+ELTqG47WaE6+baVEe4APM/xEvqCyRv1
            P88lzYZeJubmD5HSQWG8+XkLl69vljkXj54E+98GvTMXTlVKRr8jFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T23:18:13Z"
    mac: ENC[AES256_GCM,data:kOssvR8EZ5emGT60O8AjqBIkucLod5YKh7FlXiXwSBPMRYAXFfYt2HlrjtWbvc8GOtExryTyz2B1Fj4Oxz4JA9ENcryKJsEBtgoeRaiM/V4XT1dU+xKL2g9BEifOyTF1Tg2NrO4cuAwFidaM/PUR3pmg0pRcqiCV3iYHyw1jZmg=,iv:JiKpPquh0wKdFRJsJYM58C3reX5Lh1x44uc2umyPWYA=,tag:slG6RX/z4pOaZKS3sIY0YA==,type:str]
    version: 3.13.1
