apiVersion: v1
kind: Secret
metadata:
    name: qui-secret
    namespace: media
stringData:
    QUI__DATABASE_HOST: ENC[AES256_GCM,data:h8tNmUB1CtPNBaPYjQMN,iv:PCgKEf2KEWiaCNBErHYjRBXlGvqqmBO5Dokvoeli0gc=,tag:QnL5/vkKBXmM8MaLrcs7tg==,type:str]
    QUI__DATABASE_PORT: ENC[AES256_GCM,data:Fs4z/ZEyGjPDYxOKhB3W,iv:fYLJo7JAKXarCf9bb0+A2Dp3PIKWgSEYiPfG0JqIuiE=,tag:3gQt8+XwzwUIXKdQ5hxbzQ==,type:str]
    QUI__DATABASE_ENGINE: ENC[AES256_GCM,data:/kaaFaGdzqc=,iv:KtpEPzZwsVnZjRQ/UE0IaOoFYLN4yTc9Bl29Wtaif68=,tag:zicAJJ390V0HVlDfZ+njcQ==,type:str]
    QUI__DATABASE_USER: ENC[AES256_GCM,data:bb91,iv:FwPctz/dWazGVOHmTEXuSq1IqHcXwtC3pS8dKe+5yPg=,tag:1FVRJemqUn8BfTTGk1OMlw==,type:str]
    QUI__DATABASE_PASSWORD: ENC[AES256_GCM,data:ltIEK4tB+/2fF8gVBnJgwPnLeyWG0lDvuwRTEy9DJ4Tzrq9CdQp47LWA2g==,iv:moqjbGVAG63aeXhCuhNO28swz95Olj+muFdl51gor8I=,tag:ONpgi01g5QrfPM4K2TJGyg==,type:str]
    QUI__DATABASE_NAME: ENC[AES256_GCM,data:L3ag,iv:6KQEfyiubpsm4pxuJ5PHOf5ZhRwdeZTQ4L8NY1mn/uU=,tag:JoIGn+TJSUlr/F4gmoJ8iA==,type:str]
    QUI__DATABASE_SSL_MODE: ENC[AES256_GCM,data:bd9GjwCn+A==,iv:JX4S8qbydH2I3mqB+12H3SSKgIv+SgrB0OYa8J7PKBI=,tag:CDT0UVsD4yNDNiZbHEFtcA==,type:str]
    QUI__SESSION_SECRET: ENC[AES256_GCM,data:bZK3BcMmpSDQiKu0yEdnmRY754IAmsMpbhD92D0Dl7lbg/jxCtgAnfZq0/I=,iv:1M8Bf4Lfk6GaFmZD/W8fOY+apjwxjrNJHiQ4ksG2CvU=,tag:aZER/YcRHJ5abHtr6fnyiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQWVMaWlGSXUyL3pJaER4
            KzNWcVFHV3RsSU9McW9TbjZ5UW9BcUU5OVY4CkR6UWJJZVJiMFBXZkhVaWwvdXNV
            VkJ1VnVsVWJmb3kxZWMxSjhpT1JrbmcKLS0tIEhGRnJHRmtqbmVQSnhFNnJobXpE
            WXhPaXkwUkFyWTVIeWVGQllDU3NHaEUKwtpl3gpMNaUqLbte2lJTVttdqQ4Tm+t0
            YWUpfpi4rN4kekeutAac6UrkovkqB2/B5X19FwAxVlSZiePMWQA1kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-01T02:47:46Z"
    mac: ENC[AES256_GCM,data:UfpWvzblH8Oxy9QBqgBP8yKs14f2fOaQP+Dr8cikezT058v7KcA5+tQ8EwI1uZH3pY+Kbe9EJaV8/+/4OIUJLW+rJX2MC8RBDyCV9X70wA7eta8Sfkir2V9lQXDO/PhkABmDWFr25Jpa9lK5Vxgd6DqZ2N0oCFPT9rt9jZr8Wog=,iv:ck7AOJZVAFj0Fzu+eYScqxV1I4NJuiwHLo9j0ll+Rjg=,tag:mG8f7lgE41xdFzKTPp8HfA==,type:str]
    version: 3.13.1
