apiVersion: v1
kind: Secret
metadata:
    name: qui-secret
    namespace: media
stringData:
    QUI__DATABASE_ENGINE: ENC[AES256_GCM,data:hDxaougI0mU=,iv:bysLpdccQNKy1V8+Y6F3Bbvt43s0XusQYvVKboCiEdw=,tag:37kK9NhwE71OyT3hkmqcsg==,type:str]
    QUI__DATABASE_USER: ENC[AES256_GCM,data:MGUv,iv:QacA3/rVbJTv/v482Zr4/8RdZiUbZ8Ar9ZWVTYEmplw=,tag:KK5Hqqt0AF0WC1qDj4DPZw==,type:str]
    QUI__DATABASE_PASSWORD: ENC[AES256_GCM,data:6A/uCf/45MIODDJUHBZX3s7lOA5xdlqyDOrAznaRDvNvZaICcwgk+8TjOw==,iv:eDMeFD1NEm6m3Lu2dP6XEPfOc3Gz1nBt9180axeT6+0=,tag:WlM3nwsB7NyVhZZmv8bcHg==,type:str]
    QUI__DATABASE_NAME: ENC[AES256_GCM,data:QPGi,iv:j7nrsx2qJr2V4MXWEDss6ePGRi7jryQL4VL71szpMSc=,tag:dn+6xZW41OfrnBjSIPGhFQ==,type:str]
    QUI__DATABASE_SSL_MODE: ENC[AES256_GCM,data:aZDZomQ9+g==,iv:0HUIRm7fm3q/RnOzdAhHS8g7i+xp3egV+B/jJAvktsg=,tag:klNNoILtfW3CHMJ3K5mCRA==,type:str]
    QUI__SESSION_SECRET: ENC[AES256_GCM,data:bwmquWoJfsmyl4ap/WMeQBtAI5Spnaos3bdjBFUlMlsCXhing/7Eb+T7TcY=,iv:rC3WpuIxum2IBfRM95s8gcuayrpeVg3FW3ImmNNSG8A=,tag:Hdk8dBZPL5fBqRQi3GlPxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdHlOcENpejdRVnlxUk5k
            SGlzSEJzbU80d3FXYWFvWUQzdnJ2UmdROWxZCnpJN3poWnpNekxIRW90R2h3elF5
            UnQ0TVkwTjFqWVB2UnJYQkYxWFRYeWcKLS0tIFZVRDRKa1NRY0pHdDVsK1U2ZnBu
            Ry9oVlZVT1c1ZEdlcVBBTTVEd1RESUkKYXMApL6nKGH45GDBcZP4v9KL7tT9wSE9
            Kgx2DJ2b0gx7cUMZAAqP94g5C8DG6nFoWk2zZWnY6L1jR69jMIeJkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T23:22:36Z"
    mac: ENC[AES256_GCM,data:4LfQAROTy1D4ADOYu/iSMWFl5DcW7jlTx8eeUAetK94DK20ebBOnX9SZzQSiAsRULgzdaGQDKX0kHokBHbvYF9EOcGbKQi6HW+f8TeBBFeQi2uuKLnJNyGkPhFPDavlDRj9smIDX5kGsQJUKCRcs28/e7bEFMctgTrDj+vID3Hw=,iv:haD+rpB2GKyd6vS+LvGQoFuT2rji7wqObXYkN4+PDXw=,tag:rGOQF71+H62byV/E5QVbTQ==,type:str]
    version: 3.13.1
