apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: op-secret-store
spec:
  provider:
    onepasswordSDK:
      vault: s7byntc5csbmb6xuout4hkkipm
      auth:
        serviceAccountSecretRef:
          name: op-token
          key: token
          namespace: external-secrets
