apiVersion: v1
kind: Secret
metadata:
    name: homepage-credentials
type: Opaque
stringData:
    PROXMOX_URL: ENC[AES256_GCM,data:2waLaxnBcoAemqKKgUcAAsUgSSsZfZHeY4TR7k5JI0zDbLNpvaE=,iv:olw1C1IFz0b9NqnQtawHWedtOEAAoB+j6Yyt8Pu4ens=,tag:Hbor1u3JhVHFKqLLFylUCg==,type:str]
    PROXMOX_TOKEN: ENC[AES256_GCM,data:Qln8wA/JW7HcAQMDwxVBMeA=,iv:7ZvxAxRgrZZmp3B47reKaFYzpzctRelw3MHyeQIraDY=,tag:Kfl9UZCbddEtOoCdRJ5D7w==,type:str]
    PROXMOX_SECRET: ENC[AES256_GCM,data:s2efSUk6JUclBM+BYdxg2VKIzfBzo1R+e9u1DQNrvcoEqdao,iv:1JeVDkIc8jA/uj0Gv9+jmrqrFVaYUVySHC58AMSq800=,tag:Imum12z1I1Pu/r9Svc8RGA==,type:str]
    RADARR_API: ENC[AES256_GCM,data:HAkRu190IEs2lNgRRyjSvu8gOOfexyzTaVs5OZjC1k8=,iv:Zxxp/Jh6vSNYFqb669qKuSFn8mvpcEuL2U1+BoPn7WY=,tag:lNaSmwH17cqZk9weSzJCnQ==,type:str]
    READARR_API: ENC[AES256_GCM,data:aqV9UBpkcPkO/dpLajMHW+uqn7WjooJ3H9RgWn7iHj4=,iv:dCMAoj8WjX2SF9lZYhkrk24d+eXB3zWq7zuj2BxA91M=,tag:Pr4YWugf+mAJG4YgSSYnfQ==,type:str]
    SONARR_API: ENC[AES256_GCM,data:rp5yciCwp6Q8Ye/KK8rdsZpVKSJ8ncFgbFoh1i+4jvI=,iv:KTJyKbNBaLF5pk9VnE9vAr+ERGGNN1nGTkFn/5QNqQw=,tag:W+qcGgTuYGNniCHUA/cR8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTU1RdEYxYWpIOTNJNllG
            L3ZOak5pQUtORVRIdkw5SjRzeWVxV1JYTEZRCmltMnl1L041L094SE9jaWFWOVlG
            UHlnaEFkRU1zVUZ3V0JoOVVGcU9RdWsKLS0tIDNpRFZ4SDV1akRGbSswSVl6VGE0
            M3NyZUs4M1RtSytGV1U0bVl5UkdGNXcKV9Yb7jPzZTjweV0icRo3Cyn3ge9b0W4V
            gvhr0GIDmIGKfWk+l2SMAxWkd2lMuVkAmugXZ0CQ7RNlmAVDdSDyig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-19T06:21:05Z"
    mac: ENC[AES256_GCM,data:Xgj55Ol4Tws/006UtZ2BrQX2XuVaDyhi0YGOCKOl/8Wg2GQ8iBiZmCBHu37IGdP4rfUa+/+qwMsgZnQfBayyhf3mcK+RiFr6U83ACxrL9+gyoiVZzYg5bpLic5au/mFjcy5DG2xrkQtqA6W581DIcZPtmtqTOnSpcAi0sZhZPUw=,iv:iqzPQfwgPkszuTCLm3IKr/hOpu3+UQxyEFEEVH7/4gk=,tag:/DkZlr9NIRlhXBfFQQTguw==,type:str]
    version: 3.13.1
