apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-external-secret
  namespace: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: mealie
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mealie
