apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mealie
  name: mealie-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 2Gi
