[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs
[BitTorrent]
Session\AddTorrentStopped=false
Session\DefaultSavePath=/media/torrents
Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false
Session\ExcludedFileNames=
Session\Port=53289
Session\QueueingSystemEnabled=true
Session\SSL\Port=1472
Session\ShareLimitAction=Stop
[Core]
AutoDeleteAddedTorrentFile=IfAdded
[LegalNotice]
Accepted=true
[Meta]
MigrationVersion=8
[Network]
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true
[Preferences]
Downloads\SavePath=/data/
General\Locale=en
General\StatusbarExternalIPDisplayed=true
MailNotification\req_auth=true
WebUI\APIKey="{{ .QBITTORRENT_API_KEY }}"
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\Password_PBKDF2="{{ .QBITTORRENT_PASSWORD_PBKDF2 }}"
WebUI\Port=8080
