apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin4-servers
  namespace: data
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "apps-cluster",
          "Group": "Servers",
          "Host": "apps-cluster-rw.cnpg-apps.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "verify-full",
          "SSLCert": "/home/pgadmin/.postgresql-certs/apps-cluster/postgresql.crt",
          "SSLKey": "/home/pgadmin/.postgresql-certs/apps-cluster/postgresql.key",
          "SSLRootCert": "/home/pgadmin/.postgresql-certs/apps-cluster/root.crt"
        },
        "2": {
          "Name": "data-cluster",
          "Group": "Servers",
          "Host": "data-cluster-rw.data.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "verify-full",
          "SSLCert": "/home/pgadmin/.postgresql-certs/data-cluster/postgresql.crt",
          "SSLKey": "/home/pgadmin/.postgresql-certs/data-cluster/postgresql.key",
          "SSLRootCert": "/home/pgadmin/.postgresql-certs/data-cluster/root.crt"
        }
      }
    }
