apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin4-external-secret
  namespace: data
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: pgadmin4
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: pgadmin4
  refreshInterval: 6h
