apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin4-data
  namespace: data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 5Gi
