apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-pgpass
    namespace: data
type: Opaque
stringData:
    pgpassfile: ENC[AES256_GCM,data:01Yc1slFGld+HaLuuDRHhmO6nKRSXwAAtz2Qgu0TT91aN+lmanC/oSp/U/IzVnC6Wrb2dYatSl9H5QcXM+w9CZHG5adrRmCOve8WyupZaOdghKF1vynFH5pZC4G7FnIXFX6YlZ9uQ8qXgt0Fk3vxy72odOXCwZ0yE33ZWsv7oRSxU/TOyCU53ups60nmzjTiyCwFNxlfqz2uaOlah1WnJmKCebHsS+nwxx6JFaEl/xRYklGU8cq9Om9LYnAGzZQjr+FBqC+r6G32KlzkjpU/ylhLRCba9i3Ptg==,iv:hBZnUf2z+Y7+jPS3GQxX0L9u24kEV0fhNu9G0olvvzI=,tag:SggW/lcIL6NMbkN6meO/BQ==,type:str]
    pgadmin_password: ENC[AES256_GCM,data:YVaEPmigEPcLyv93Qn94jHvwzY2fi1FBArWdBrkdWgqCwqiIRX42ARsY,iv:nSqQFtLjpYeYn23cu8+GE+JjwpaWkDVCxgtYp4wuRu0=,tag:35Llzx/5oF3gBlZZVJn0rA==,type:str]
    postgres_password: ENC[AES256_GCM,data:9nu6IJxiD8NLNcUItMxExaoGFkO0bILwUYuUcgS4G0bJ3/VQ+ixFaPG3PDeAcaLETuU=,iv:dXeIHvBfOJsvdjkJBiJUNEtUUNjURde0LxGHTcKNqeM=,tag:EaCDWcTu06jyfumQVynzTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTTREOTVnUTVSS0NzYmpk
            NUYvRTV2K2c3YzlBZGtqanRmSXd3b0E3bFFjCm9iNEV4ejZrdVFVMjdXaDVlZDEy
            VGQ3cWREaGM4aTl0RGJHM0tCT2RvZEEKLS0tIDJrZU1yZG9IZUprOHhBREtqa0VW
            Tyt0Tmo0M1VncDhpZmJaU0M0TTJHQUkKkD9v7TXG9oD9v4e+iO2IkHs/DuOu/51V
            /BEgpU0eLZMpTNNOzdPesttHrtOmtO3WHAfs9z2FXoaVFuS30y6wGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-09T02:58:37Z"
    mac: ENC[AES256_GCM,data:AvFCsi318eaMpX/gZnCh/UwMo5pUQIHBXRjIPZfR9qOTGSP5ymHjeiLuNPQ5NHrHkROyFN2g7c4FEpfxM5bhTBNgs+ehvONivkJYwPIelpXWmCyV2QgNJhWo68m6b0aBvn90Xflb3e730NErBPm/OKp1PvWpL2XoQu5rERmw+C4=,iv:uPRts6XEuCUPpO0K1mzjLERn+oOQ9yvrjW3txVXNYbI=,tag:UX4wavN5FkHLm/XGtRn2Pg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-oauth
    namespace: cloudnative-pg
type: Opaque
stringData:
    PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:ycFciLf9EMunmL6CX3ekbEGqmLpUaw==,iv:ZYZAXYHd94hXYoGtFHfjx3kdeQ9xv4c//ghpAKzbBKw=,tag:nu4s8J8k523IUXJX7lj7kw==,type:str]
    PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER: ENC[AES256_GCM,data:UaGwbg==,iv:3blrFy2KAnu3SGfAvcybLBKOWRLMGPU0VOoWQEjcg/Y=,tag:jV7Nxr5SeMw9aHuwNptSJg==,type:str]
    PGADMIN_CONFIG_OAUTH2_CONFIG: ENC[AES256_GCM,data:oQwWC3RjY1mvArfgsO6lUhTr2K7aENH4FPdj+QH64OCA6WtpMdos4ygO9YyUQ2Jbr84hTblDj6vkCjtbBvKFcE/N/yJSY0kSZ6ETRflzfIIAsIQy8U4nhtZmgyyBNsRBt6m8dfFs5lEVABQfk3bTuwbD/Vy9w6kSZQqFyD5aYMSH5M/Unsa3lxtX3BsppehkM5OCEO8vxO9rab2UniEBKJLdUv7nY69U7Ryi5ruPEiH/XWPwMh86nOqI3yzpqqgwCxxIYfaxzyjTVq08NVX+ESuZMWsZtrXKpBu+uMYYGhb62Q119nTjE11CN7j7IkGeWA0nprOpPVLkWFJJTFGmx4fPcxw7Ag/iUM1MdeNLNj03qcIyo7UTpFxZm+N8bIzacEu8RQeLntJG/LGycmSCqiIgIbIPHNUlEYvBc1fPyciTLlyyq1IfaIkxyf+rszzYUhH9VtYbVgAypQY1bAJmP8RrV8odnE6oJIHZ2EpWJAmjM3QJb/XITSxs56cxu5/8xwHBmrepZKVFfxzTktFi2PjDPZAftfRY7soZKuMq5UfzGSBZfmES4GrW5N4E1eCswmH1klZDoijEsCP+tdRwmERfJcjGmiiLbSZK5W/GdoLjFXtMZxJ+6/2Ul381eRHAEdk7Y82JuKXQpuMjXv+oUca2r2aoitmseVPad+/D7APl6HZAy3Ce7I0qoDpCf6e+/CYL9qjAh/qyKHCQBCYZwif1NaAxrpiDeRXlTMAmhT1IPjtIT3Bdj9bnsOJX+0S64u3M1sBRFKimldKsx+TsjiuRU/9RoWDf0MHbw3rw/7oVCjcIuVZlskvwN0L9hnG6eBO9uiCiTS+uQ8lND8EHdIX3hWBUUH5tgpOBct5G1hIUS0XuWJU5zLtEH2L9ckQJAOhmENI0Aj8tMJueG5H4W6q6PYgxrqf2YzCrWAortkwj+v09QBzj9cqRI+3Qn1ZiMtTA7VKDrbqx6K+J6Rzq94Qm0ldorARQ7WtDX49Qtl6DTMHyMl6ma/dvaoc/64cIogLj5vmoAwKNLHUszwmIMAYiRxKaKobyELbpXefIAlq6Lw4NscDwdM/p0mA54Fal/uDD,iv:xWf0NEzkYYufD9UpXb1CdmAmlI09eAKwMjL5THkVGME=,tag:z6cfCabnMJNN3CFYyMLxvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTTREOTVnUTVSS0NzYmpk
            NUYvRTV2K2c3YzlBZGtqanRmSXd3b0E3bFFjCm9iNEV4ejZrdVFVMjdXaDVlZDEy
            VGQ3cWREaGM4aTl0RGJHM0tCT2RvZEEKLS0tIDJrZU1yZG9IZUprOHhBREtqa0VW
            Tyt0Tmo0M1VncDhpZmJaU0M0TTJHQUkKkD9v7TXG9oD9v4e+iO2IkHs/DuOu/51V
            /BEgpU0eLZMpTNNOzdPesttHrtOmtO3WHAfs9z2FXoaVFuS30y6wGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-09T02:58:37Z"
    mac: ENC[AES256_GCM,data:AvFCsi318eaMpX/gZnCh/UwMo5pUQIHBXRjIPZfR9qOTGSP5ymHjeiLuNPQ5NHrHkROyFN2g7c4FEpfxM5bhTBNgs+ehvONivkJYwPIelpXWmCyV2QgNJhWo68m6b0aBvn90Xflb3e730NErBPm/OKp1PvWpL2XoQu5rERmw+C4=,iv:uPRts6XEuCUPpO0K1mzjLERn+oOQ9yvrjW3txVXNYbI=,tag:UX4wavN5FkHLm/XGtRn2Pg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-env
    namespace: data
type: Opaque
stringData:
    PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:Z/ehD8s=,iv:VNPSQ1HOlZjW3zYjDnU/3i9NhnRQ0YdTAnDIk+DQly4=,tag:G2U08xFN20dCqrW8NSVPdw==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:mznGeCsHlpc=,iv:CSwwmMigfKbvtM/nVF4aLSb6iJm8uvishCvaGXN+fdA=,tag:z0/h4m73X584phkWw6cimw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:U72lWFq7d8qq0yk535uQM05C/LB9pkVXuqtJyZENPSLbjPsDYxJ7T7QBufy0zOkjEOM=,iv:/p1YoVCy5H1KhK3/BkwozmSWyFiXvPHUJrCmpNpou4k=,tag:m01x+KhU0ua60NmsQdGD5g==,type:str]
    PGPASSFILE: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTTREOTVnUTVSS0NzYmpk
            NUYvRTV2K2c3YzlBZGtqanRmSXd3b0E3bFFjCm9iNEV4ejZrdVFVMjdXaDVlZDEy
            VGQ3cWREaGM4aTl0RGJHM0tCT2RvZEEKLS0tIDJrZU1yZG9IZUprOHhBREtqa0VW
            Tyt0Tmo0M1VncDhpZmJaU0M0TTJHQUkKkD9v7TXG9oD9v4e+iO2IkHs/DuOu/51V
            /BEgpU0eLZMpTNNOzdPesttHrtOmtO3WHAfs9z2FXoaVFuS30y6wGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-09T02:58:37Z"
    mac: ENC[AES256_GCM,data:AvFCsi318eaMpX/gZnCh/UwMo5pUQIHBXRjIPZfR9qOTGSP5ymHjeiLuNPQ5NHrHkROyFN2g7c4FEpfxM5bhTBNgs+ehvONivkJYwPIelpXWmCyV2QgNJhWo68m6b0aBvn90Xflb3e730NErBPm/OKp1PvWpL2XoQu5rERmw+C4=,iv:uPRts6XEuCUPpO0K1mzjLERn+oOQ9yvrjW3txVXNYbI=,tag:UX4wavN5FkHLm/XGtRn2Pg==,type:str]
    version: 3.13.2
