apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-pgpass
    namespace: data
type: Opaque
stringData:
    pgpassfile: ENC[AES256_GCM,data:gS5fsNDMc1ZxLWgiqdb4Ae4fvcnNG5tNmiy7KERtGwFMGiegxcxaHuDn7ULobrUkkAtMzp3VXrPo6Vz2LVuQqmNOcJLYXdC+5bKG04o3p/EebOdPpvt2n/b0N7rzMC+mjPnVOiCTcedGwEEst7w0IhdNrArS/ULPtEx0I4c9tVrkNfl0Hr41ufZdYqrtFbri551G+ONqYw7gG1mo0mD0+94faTYMjZvKHqhyoy+tQxAx4e2njqLOgCWGTIOByOxyTjuvXyCALC0r3GyjdQG7xPVNchc+tGYzLg==,iv:SZBTGW3nTB1I1d3yG6lPFp6exXzRepD8KnJfKFjVI4s=,tag:MbqLtspymt3/QJ/Hzd9rZw==,type:str]
    pgadmin_password: ENC[AES256_GCM,data:+kbhb/iW5EvvzrMf3NGm9nkKFjQj/SHEGsMrhyLq8RKRLgM6G9Py3LA7,iv:iYun/D1ERXUhmSV8HPnIJE4iPCjQ6OAtVe1aZF2xwv0=,tag:JWClsVsxAHIuXFJsQ6IpyQ==,type:str]
    postgres_password: ENC[AES256_GCM,data:+w3rZKBEoneQL1XV4yUJZp2TM5tdVSkUV7wNDy4GA2P9rwIUk6yCwRflFsKBj6L5RU0=,iv:r3NWa28VWI8kx26W+Fc9ObqbOFTl8QmdWm/HQ1KHjh8=,tag:YrJ/sG7rnkrt1vmwpA/qSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVHJ4OTRVQk1NaXpjN00x
            b1crTXdjNTZyYllFbVhDeGRTSG1PU2pZV0FJCmhEUStpR2hZZ3FWMnRDMzg0RWpE
            V2JRaENXRXZCWUs3NTR3UkxtYVVJVmMKLS0tIFdhdy9SUVRIYXRYQlFibHhtTUZG
            dThVYmRkVUgxME9VM0crc0k0SEswZ2sKYmxumLubuWO37GOkTXa0z8fALB9K++JV
            cedWRLRGAur65OA7i/anSApKVd17ce/HZ0pPrTpKIomXc0nhGELSJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-12T18:03:17Z"
    mac: ENC[AES256_GCM,data:ZDXQvKyn8pGTbr/AKbiwr1lpPebr9pV/o2SE3S69UgdnpjsEtusjUS5h+YE/qnmzD/VYAeuDncLtElFXfAngBu7El18BjW9wouZ8287wSQkGji/zOfGcedSb7YoiOfR5zkjpS3j+Wnl5cwW9y2bPVuCZ771fxcXiKGBpJBGzzZo=,iv:l0yz7rSIVboVV99hPJITAeOpOSMUElRNzZO/vH17b+U=,tag:vTr1i653qfiRINRuNgfQZw==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-oauth
    namespace: cloudnative-pg
type: Opaque
stringData:
    PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:wCvX0x4RPXQ1K0f9hN+q+8doobMY/A==,iv:uGeEdct29qDdjTZ5c4BNGTuXPfnQgY807alb82ZeEFo=,tag:PHRJYkh0X9k2aWl+9++uJg==,type:str]
    PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER: ENC[AES256_GCM,data:KcrX2g==,iv:Tn+GYiysGTosYtwIpUF20Gcs5X8X70lHjTBW1ahAJ5Q=,tag:1jCQOmt04a967ksoyWZn0A==,type:str]
    PGADMIN_CONFIG_OAUTH2_CONFIG: ENC[AES256_GCM,data:mzUpVo19tQv8d4erOEJ0VqX8jDVdPmRFqQofbzXDTjhcydq+rI0SrQE6S/ZZlO7FN9SurujsFTivSadYcOj1+rgy/qwNjUop8txucUGm3H1qIZv91hLC2HNuIkAyBibF3o1mmsmixirGb6QEdvNR3QAFFQgNTtnd1cFQVmyK4Lc1dMe0bUoatpIhveEwnr27/vAGxJ3frA2NaxgxxAprNL5fLcALflVrLCmu2yfpUfZnWXXdsQqlc2Z0biGWtxsqEpKBm39QFJlJj5zJn+JjqyXhAKS+HCvEUNletuMDI1pIEEXoStemlGFdgOIkc7nmXI65CxDqzRZfD76vum1AvC+9rZmTpIGUKuvmAfeyBVmv2oukFeqh/Oegp17HQgvICtVhLTpMRomTZz5rPLDQTThDLxY4Ju9zuraNcQuQBqvj+TbKaTz5CgcBjbemVKa7+/dZh5nDyjL9xbpTB2mbS4eGGIuFBbIWK74l8YV4dR/4l00OqtVVdOZwrplMKyY4Sxu9HjTJqoNoiiyCY0GhL9/YJ9aslDFcmkp2kss4H2h2eLIZbYgyN14zxLfsoz0uVW5E0GaTu0Jgm3tyUkU9HmCIlvn4l3kmkbewzchvtR7XK9EgeRMIY/bctXaNCj/NGxrlQQ6PiGv69xwuapDTmDHgKtFDRyNkyRRcDzFCo4Jqu4f8F+HhquKoWLfLkmqwBnGAH9syJV32IU3yxmufW4tejYMl31QedyuO2wvQpXw5K+LTH2RElMyqm8cpgx3QpNYCkqblAti9HcAAtkUg0ZqjYYEV8ZY1vR+z+e72MTXnFAhhtTiM+cVdCwp22VW8PJqlE2jNZm6GipvLniIsGr+QcJPclKleP8yG9gwm1pK+5esPy72LUikCYwGQgwk/XJShU/LqUX0FjSOCSXv72U6IBnLkLLqnIG8pmLQhk9rhJCgE13JNSh1rt6AlQSjPuPQ3U9JJX4Bxd8tV2WzaqSMaVozCeDToki7DpgueKJmduoYwxngvII3ygzQ8r9Vcq+reaCTVxv9JpxmlGfZM7exdDvEpuF47Nw7c0wypflrariK0a5NLFvHCBt6MJPVkW3SC,iv:QERu/ksDf5r1qgAzyxJqMBbkjTeIxe6USmGG7G6P4UU=,tag:4HBl04N6BkUmtTol21ThzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVHJ4OTRVQk1NaXpjN00x
            b1crTXdjNTZyYllFbVhDeGRTSG1PU2pZV0FJCmhEUStpR2hZZ3FWMnRDMzg0RWpE
            V2JRaENXRXZCWUs3NTR3UkxtYVVJVmMKLS0tIFdhdy9SUVRIYXRYQlFibHhtTUZG
            dThVYmRkVUgxME9VM0crc0k0SEswZ2sKYmxumLubuWO37GOkTXa0z8fALB9K++JV
            cedWRLRGAur65OA7i/anSApKVd17ce/HZ0pPrTpKIomXc0nhGELSJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-12T18:03:17Z"
    mac: ENC[AES256_GCM,data:ZDXQvKyn8pGTbr/AKbiwr1lpPebr9pV/o2SE3S69UgdnpjsEtusjUS5h+YE/qnmzD/VYAeuDncLtElFXfAngBu7El18BjW9wouZ8287wSQkGji/zOfGcedSb7YoiOfR5zkjpS3j+Wnl5cwW9y2bPVuCZ771fxcXiKGBpJBGzzZo=,iv:l0yz7rSIVboVV99hPJITAeOpOSMUElRNzZO/vH17b+U=,tag:vTr1i653qfiRINRuNgfQZw==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-env
    namespace: data
type: Opaque
stringData:
    PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:qFpZZxI=,iv:xEZXqDJ3RcJvULJ7XoD+K1I1PjVwRwNMCJgAaWEt1s0=,tag:ta+uDiJIgfm9eKeoI2webw==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:6oDZccBZbxg=,iv:KYZ9xIPpi/GrHQeNnN7r9E6VDe+CPJ3/flLDbStR6C0=,tag:YTjGJZ0BJy6i1tDHG7XL8Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:wbLK6NeacBaNX4GWmuUoh2C6EGA6FhtwMzx3VcJRVNZ9QTWxtFRNNjtXnYFgObnkzXo=,iv:731UODV0EApvkrLEa2RqHj50dH9wfGmaukOmao0qflw=,tag:H5j9Nz1WSpu9NGjeJ94Q3A==,type:str]
    PGPASSFILE: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVHJ4OTRVQk1NaXpjN00x
            b1crTXdjNTZyYllFbVhDeGRTSG1PU2pZV0FJCmhEUStpR2hZZ3FWMnRDMzg0RWpE
            V2JRaENXRXZCWUs3NTR3UkxtYVVJVmMKLS0tIFdhdy9SUVRIYXRYQlFibHhtTUZG
            dThVYmRkVUgxME9VM0crc0k0SEswZ2sKYmxumLubuWO37GOkTXa0z8fALB9K++JV
            cedWRLRGAur65OA7i/anSApKVd17ce/HZ0pPrTpKIomXc0nhGELSJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-12T18:03:17Z"
    mac: ENC[AES256_GCM,data:ZDXQvKyn8pGTbr/AKbiwr1lpPebr9pV/o2SE3S69UgdnpjsEtusjUS5h+YE/qnmzD/VYAeuDncLtElFXfAngBu7El18BjW9wouZ8287wSQkGji/zOfGcedSb7YoiOfR5zkjpS3j+Wnl5cwW9y2bPVuCZ771fxcXiKGBpJBGzzZo=,iv:l0yz7rSIVboVV99hPJITAeOpOSMUElRNzZO/vH17b+U=,tag:vTr1i653qfiRINRuNgfQZw==,type:str]
    version: 3.13.2
