apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-pgpass
  namespace: cloudnative-pg
type: Opaque
stringData:
  pgpassfile: ENC[AES256_GCM,data:z+F5El/Nke7GbT1rz6TdtGtrwD/Hsf4qpsv8aSz/fUy3auYb7llIvwY850q96HeT4scaXYfVd5hMfAF6F/jT7hSGNWuieYqCKBxwAMmEf5MuIe+twp8/P8ac6QUMXA/8IswLDwjydR4PQ8bCNfh8audfMZ3I8xVLQY3qFbnM1+LgafEvHPQuaydSwIqTVOOIEBCLIuaJ9H0ZsYdCGlNYEYjqcpa84eyWW4TgqC0A9+Jc/zUhgDaLhv9taxWVvsnvJSe7e65OtBKFyYcNsTe1CO1+rcgVXDQ0mA==,iv:bl0uQsLmk7BNHoUNsWKXHTTI2vi/Dv1U5gIf2zim9kk=,tag:w8Z5YtZax1dO7f7VKO1mMw==,type:str]
  pgadmin_password: ENC[AES256_GCM,data:YTQCnhCsZ778Io1RTMiuAq8gYSI2g52Nchtj1g3wSUGeayfmGmEk2n57,iv:GV6i2R1s20xVJFoGbwECjOwEn5BMRpkAckS4rqKdiDw=,tag:6rm3f0pb1O/iXzc+yVA+Yg==,type:str]
  postgres_password: ENC[AES256_GCM,data:AfuwYrd/kTw/j0qWePLAqtUp+ggZ/nlVXjA5M3RLxbwFmVDWlRd4W5PXlIkcwmAChz0=,iv:6GVI1DJtefK1SF+nEQfNvGRaAvzPQc5d7yC9mpCmqr0=,tag:bPT5IDTaID1uKopxEyzmDQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOGoySWdDSGhNTElCdzRO
        cy95dlhmdFFjM21oZWovNllkSlp6a0lwUG5RCmsyTk1nNk9wN0tKaU9LMnFvSnRl
        OEd3VitFYUcycjlvMlJlN1ZBeHJrbzgKLS0tIEdiSEdLZ1VyRkFaSTF3MHJhQ3J1
        VEhhL2JQVUNXaVVISkhQWWRUa3BkTzAKriyCU1tNZVeHVK/riyXaTnMqUMH3xntD
        kcLIAqxVKAXKx3pVmWCbbYLHvtAMehwYlvt1CIXve1ZmIjTiRtRnnQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-07-09T02:23:34Z"
  mac: ENC[AES256_GCM,data:otDRtWn9P/zpsqUUNnI+S+PIwvEbvp+WWkM80vehlaUya5XuM0zoYPHZyjVwiyq/8kXHajrrf1obFo5GWBSRDTS608R01c8OgcfNiMEblc2WXZjHkfToC+YODMGFABW89dxe0/viNIOvKBUIRLup+leYJAD6L2ljJVTq6kOyGig=,iv:KBNQgRT3Qg5IclVAWvOWqTSynuRvH82+qxpzFjAboGM=,tag:7Fp8Ydeyo9+ZWiHRsQVYmQ==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-oauth
  namespace: cloudnative-pg
type: Opaque
stringData:
  PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:vYFwASY7zJfqBSRONV0OH2HbWITdUw==,iv:B7WAUVlo8jvnCzm/0zLH1zKyr2AS9jS/7BgyWRbhq2I=,tag:Ke8nTCldPp6ApUtQco4uFA==,type:str]
  PGADMIN_CONFIG_OAUTH2_AUTO_CREATE_USER: ENC[AES256_GCM,data:VdLb4w==,iv:OyFE3XLcjT2wmtEHNdn+9Ax/2BPmm1qrMu0+NRC8hxg=,tag:/von0s5vOM1NbImBUsQbfg==,type:str]
  PGADMIN_CONFIG_OAUTH2_CONFIG: ENC[AES256_GCM,data:7+b3ZiPP4R49hS0XYL3cuowEL/fwUXw6LEM8kS5TGZleqMPa737uMKRFNRo9yM/GX4FKEi92EMNWqPsD96GWUjDAmUFpOZD47H3UAt3hPt38TuU5BZsZQQ/GEOl89GB9xdKOmIL2EH6yDaf99M8+ZbF2TJkv0ZVBcsefEKFG0Q3CND4CKKO28C66OypOtYRR/060fMjg3eLquq7tHf8rQk9ifECxfNOQVkAG+wx6CUHVT1nkvL0ySqp1reu7mP3VqqV+TPz7LppEAl95NVlHl7mvAc3CNeVOvzFsNP5Ny/GNcPgr+BS2sQyVA3ZCMK3d+5jw9NKyRrvqqoszmfoUrb2ItTPBrLua89vLGu7HCAmytTgFa6WY4hkhcnZn89oNLt+bRKDEM9BQQ/4d21xrQP3AdbU0A/6lfkW3EWTcnamB0buxUIVYNFsMD/EfIFiwnW2hLU1C7JCfG0S2Ki/LhhmUfVO5SEhuZY+i+MQMvbTkbwtM6DIHWUm4D+uqAsc6rinKJjxpJCoGINlzuVIa9qBpyhpTmh1m5OBh6vqmJceOeN+6ZSFwAhKYvzC0GnH3HjrUbODN3/kLfiU+cEoTY0y/Rff042/4ppJeBMGsAUQvo0LhbE2X94U+jHCYI2nPlQm6zKvjN4Lbgo1A/9dx8lq0UOssdGahplvgui1AZmzw2m32+1MhweedWV/lii9jV5ZHv1uaGI+0r3eIEXtg50TdSCxgpL2Sit3w6ZvH87XmKR4YOQf79W4Q06G0VzxgCmQPZhG/Ww1Z7C4+w5OBr9u6UBo5d0hvj00p32bONpKiBJ3yQnf5HKIh1K4Yi6fbfjdkIZhau/Y+Ci1C4gWtz44bKs5EX0htBvRnyxqxgjmLoBOuJ+bbTbijJztWKoed3DXIETGAAxILMM5sPDqIPDtFvzxskcy1R+gm3qooFgEEbYp0xfwHMI5k4aobkVqyqspTA67G2W7z56e5WyfsF08aANt2oMPmUaJNu4oVfFNeLB6gKYqJLUg88nrJYBdd3fxop5EZ5qgE1A7+rSb4kjwiUI58S6tEFGXZjL/Z7lw2SR9iMh153y9ECLhEZluaj8RR,iv:BnS7HnWPWaB2weK/QCLvLpbGLPaqKN1kN6bTeSDra4E=,tag:aPWWW90KO6jFGkp9gRhZug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOGoySWdDSGhNTElCdzRO
        cy95dlhmdFFjM21oZWovNllkSlp6a0lwUG5RCmsyTk1nNk9wN0tKaU9LMnFvSnRl
        OEd3VitFYUcycjlvMlJlN1ZBeHJrbzgKLS0tIEdiSEdLZ1VyRkFaSTF3MHJhQ3J1
        VEhhL2JQVUNXaVVISkhQWWRUa3BkTzAKriyCU1tNZVeHVK/riyXaTnMqUMH3xntD
        kcLIAqxVKAXKx3pVmWCbbYLHvtAMehwYlvt1CIXve1ZmIjTiRtRnnQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-07-09T02:23:34Z"
  mac: ENC[AES256_GCM,data:otDRtWn9P/zpsqUUNnI+S+PIwvEbvp+WWkM80vehlaUya5XuM0zoYPHZyjVwiyq/8kXHajrrf1obFo5GWBSRDTS608R01c8OgcfNiMEblc2WXZjHkfToC+YODMGFABW89dxe0/viNIOvKBUIRLup+leYJAD6L2ljJVTq6kOyGig=,iv:KBNQgRT3Qg5IclVAWvOWqTSynuRvH82+qxpzFjAboGM=,tag:7Fp8Ydeyo9+ZWiHRsQVYmQ==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-env
  namespace: cloudnative-pg
type: Opaque
stringData:
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:1+Xgd/c=,iv:EJxaoBDhT0hl47rDeNiD3QkyeSXJ9e2iiPE9uTD/23c=,tag:V9pjootm6cte9lTk6VTk2A==,type:str]
  POSTGRES_USERNAME: ENC[AES256_GCM,data:DhtchTh8jeo=,iv:sy5yuyPDJyNUDrnW9WmPW66SP9P4thw72D6CmkeMHCE=,tag:3XYHxXY9XPkAD18rfNqDYQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:0CEoY7ncjYzpFM2lwz58EaZuXSabBDJvj7sYW4MT9TZQdQu79ZQog3W8F9S7ViBLgrM=,iv:4SXz3LRFOyOagBojv44ipcp8hDx4Yqtt3aNY03TFkGA=,tag:odqxpEkpXyxQTtqLX269Lw==,type:str]
  PGPASSFILE: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOGoySWdDSGhNTElCdzRO
        cy95dlhmdFFjM21oZWovNllkSlp6a0lwUG5RCmsyTk1nNk9wN0tKaU9LMnFvSnRl
        OEd3VitFYUcycjlvMlJlN1ZBeHJrbzgKLS0tIEdiSEdLZ1VyRkFaSTF3MHJhQ3J1
        VEhhL2JQVUNXaVVISkhQWWRUa3BkTzAKriyCU1tNZVeHVK/riyXaTnMqUMH3xntD
        kcLIAqxVKAXKx3pVmWCbbYLHvtAMehwYlvt1CIXve1ZmIjTiRtRnnQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-07-09T02:23:34Z"
  mac: ENC[AES256_GCM,data:otDRtWn9P/zpsqUUNnI+S+PIwvEbvp+WWkM80vehlaUya5XuM0zoYPHZyjVwiyq/8kXHajrrf1obFo5GWBSRDTS608R01c8OgcfNiMEblc2WXZjHkfToC+YODMGFABW89dxe0/viNIOvKBUIRLup+leYJAD6L2ljJVTq6kOyGig=,iv:KBNQgRT3Qg5IclVAWvOWqTSynuRvH82+qxpzFjAboGM=,tag:7Fp8Ydeyo9+ZWiHRsQVYmQ==,type:str]
  version: 3.13.2
