apiVersion: v1
kind: Secret
metadata:
    name: semaphore
stringData:
    client_id: ENC[AES256_GCM,data:AmMM/LYlavo3rYt8zJJztcBtmHb2+KAqwxyM4iq90vKJv9GleTfIcw==,iv:sp3/yIZuJykZltjl0eDz3q9cHcpRSI+E1ctCXT+X0rI=,tag:3zNsoV7VaM8KwtXEUANYcA==,type:str]
    client_secret: ENC[AES256_GCM,data:acpCzpPajokFr04dYLEUjBCrBdGNZiRp7qEA29DV03I9cj+5Lj06YMCVeWhXRzNYZ1UHB1brX1EVBdJ+nalZ+obs5eF+iRkSrhi4D+5EnBI3Y9KQK7YfJnAEecLdrOMIrOSh+Xftz7OpoWF3RqIkqYGxtPGBIVl7NBGP8/DZIAo=,iv:R1U/7CcstPad5W1IRnVQnBkpJlqgZm5DSuTq2eoxw9U=,tag:KsZKO36LO8roPBXB/2vymw==,type:str]
    admin_username: ENC[AES256_GCM,data:tvDQRsQ=,iv:dEEw2b5z9dMLdJYWDEa0jKemctDbY5VD/ePrmchD3Yk=,tag:tr5GUCOVDeI1hYXwnKhE/A==,type:str]
    admin_full_name: ENC[AES256_GCM,data:Nf5i/jDS8axYTS3F,iv:uDiRNkaEzd+U5BCV5tfbxVsBaO2y+4wRBeYX3hDlByc=,tag:bp9BRw+hwoQJC5DNrfcxaw==,type:str]
    admin_password: ENC[AES256_GCM,data:08rBO1hxgUBR4aTtPRKpxpKr3bkCN6zaKIb78ENFZ9CAasHeRSdJM8+uhCQ=,iv:wvtteLCi9OgUqpm3sp7Q6SI7t9x2TLMi9crVLtXUyWA=,tag:QAvLwjqhdei86wJRuND/LQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUitiTEFzbTVTTWlNZVVG
            NXBVS2NaUU12TmpyRnVRY2Y3QU0wVDdvclJNCndyQmhuK3FpcDNtNWVuUEJiZ0p1
            SDlUUUpTd3FJTWlveDBkYmN2RzdzL0UKLS0tIFFOb1Q2eTRYUnRGMFl2SHdWRFRC
            NnFOblpqTTlEaGdETTkwWmRYaXl2T00KXZUkdpQyHFWfDcq1xK9TvvRgdrCDoS6B
            VQ7mnenJYp8rRkyU1/f0V53JbQaAxdMVPZbc2I4WzACEhzxtPG2uBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-09T01:51:21Z"
    mac: ENC[AES256_GCM,data:bFCCvfbae0eH1ORKOyHsqAKP5BH0d0kzRNkMFb4TE47xnJ5Dbrp32JtimK5yJstEEBPDiFPOWMU+lXRRwbFHAfjRjuNFRbcQaatChfY4WYLz3a0Mm8dP519AkVCP0+7g5oWkrlwDF1tHlGCqOqjg/dFBNPD0Jb5T0sionxNYN8k=,iv:PSt35DWHQrWDyHlGFgtFgHRsGLqjRZPSDRLKkGJQozU=,tag:46rUB7PCDVUMLag36poFqg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: semaphore-postgres
stringData:
    username: ENC[AES256_GCM,data:OiGUZ1e7LDs8,iv:lkfDnvDaX2dmuluihf/pD3Bv09iyYGqweVOarUK5IdA=,tag:ioNCP5o26gInpkF7HHemdA==,type:str]
    password: ENC[AES256_GCM,data:t0MS/ZLOJaVo5Je/R46ju2hsoNzfTgIDRJYm9yOQG37jEQzkCyQbRhus42HOv8U=,iv:PwuYwBqyfX0hNn0V5XNVzAgH2uRvZSX2T79nz1meNdw=,tag:wC11wJXKkBnyR7n7Kr+Rhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUitiTEFzbTVTTWlNZVVG
            NXBVS2NaUU12TmpyRnVRY2Y3QU0wVDdvclJNCndyQmhuK3FpcDNtNWVuUEJiZ0p1
            SDlUUUpTd3FJTWlveDBkYmN2RzdzL0UKLS0tIFFOb1Q2eTRYUnRGMFl2SHdWRFRC
            NnFOblpqTTlEaGdETTkwWmRYaXl2T00KXZUkdpQyHFWfDcq1xK9TvvRgdrCDoS6B
            VQ7mnenJYp8rRkyU1/f0V53JbQaAxdMVPZbc2I4WzACEhzxtPG2uBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-09T01:51:21Z"
    mac: ENC[AES256_GCM,data:bFCCvfbae0eH1ORKOyHsqAKP5BH0d0kzRNkMFb4TE47xnJ5Dbrp32JtimK5yJstEEBPDiFPOWMU+lXRRwbFHAfjRjuNFRbcQaatChfY4WYLz3a0Mm8dP519AkVCP0+7g5oWkrlwDF1tHlGCqOqjg/dFBNPD0Jb5T0sionxNYN8k=,iv:PSt35DWHQrWDyHlGFgtFgHRsGLqjRZPSDRLKkGJQozU=,tag:46rUB7PCDVUMLag36poFqg==,type:str]
    version: 3.13.2
