apiVersion: v1
kind: Secret
metadata:
    name: semaphore
stringData:
    client_id: ENC[AES256_GCM,data:XO3c2OHcW89MkMoFVrWRlsQ7a0zSUgM43zdNw+eOd3ej5JjlCJriXw==,iv:Gi5cZjv3D8TvCiXH6QW6aoRGmaRb89L4Qur/J8Qgc9c=,tag:1to9HqN+zt5xToVN9Az2jQ==,type:str]
    client_secret: ENC[AES256_GCM,data:AiF9hDl2M9IstqShOglz7vYaM24I2FFBW3xqg5m0/QELWrqDLdELUfzr0GVRSJMs/XRDXOtqMIcV17OvUKOwYKgJjBcL484/wBhk0YbA6f4bIEAvvfx5BEVv3R7eyJaQJQ2yb1rEQ92tct0CbBPcndTO9+2KJuOyEOSUxwk/Dek=,iv:sjq2seP79m5nJOsMQgr4ruFPAmK+f3gadhVkKczvAEU=,tag:ag2PbBZ+92FVP1xJEsCLjw==,type:str]
    admin_username: ENC[AES256_GCM,data:VWR+LR4=,iv:xeKc2JibOpRfLx1JtpI4KcgDw2rPKPYapqBqVYTXvgY=,tag:NeiGQIcnJurESrPPS4vI1A==,type:str]
    admin_full_name: ENC[AES256_GCM,data:HJwz7WlD/3zoiH5P,iv:khrJwLh1+xbKFRRCUVOEA5M1IEV0rUCSLuKATzsaiaE=,tag:CKDg5KQJu4+AoSBmRyNobw==,type:str]
    admin_password: ENC[AES256_GCM,data:Kq2WdK64HdKvQ1P1baYjhi7IcmaAtvYTp8Zh0SWBDRV11XZilaszX5NaT50=,iv:jaXi1GaMRjCLmjkRXCBzU2gT6LZo3LFmWyRCGhIFsDk=,tag:LhB7nXCL/frsZpsg0rxVBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOER0THk1ZnY0UTdIWFpl
            Q25PSDB6dStldmpBcDZvZkQ4VnJnL3VJOUJvCjE5ZFZBdUVUdld4V1NSS3pna0tT
            bkVOM2xPOVhRQnltT0kxWjdyVW5qZkEKLS0tIG16dkhWSm1pN3pENWJDTmd1NHY1
            aldIa1NCNW9iV0RFQU9PazJ4M0VzZ0UKK2t0jqKQ9z6uUC8J6HQLWznSy8+iog0E
            Pnnri2QHJiSgujJInfYDGc8uEP2Ji3RWIIO3rwe0GIkOVPDMpXiFEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T03:03:50Z"
    mac: ENC[AES256_GCM,data:V9UoJQC8uBrgETFH3MiwbQoJl5G7z/GKZT8kNBdl8A2z7keyGc1fST5IBl34lg3tD/sIHikPehG6EGWFWOlseF1jJ7wuqH1qkpbaU+6wWJVVdrH05G3z2To8cjUgYUGOYTUhIETwBZitdU0ArZb6H/FMzIvdRggD5XC6b5MuqZI=,iv:70rt/quc6PFds2ZdxdLAKPQ6A/7GrcNgc98c1Nwr7EA=,tag:9WUHaQLq6DuvLPf2A1ToTA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: semaphore-postgres
stringData:
    username: ENC[AES256_GCM,data:h1w1WrLhVNNk,iv:7i6PZx2hagdlIF56ckVUdV7yfU09SnyDfcn7WzMmQBw=,tag:5R+cFvdzLsyYzJvAXy4mIw==,type:str]
    password: ENC[AES256_GCM,data:3ne0d0Qam4mM3ug5OShChJ5c35hVXOk4vxuCsoGFxymxE1xbeJATa+fNhy7lXy0=,iv:yd/UP2i5NDw+3OiIINDIq0GIpzKelPpKSvCiHnnh+H8=,tag:sN2W/n+nw6Daz0f2Z500KA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOER0THk1ZnY0UTdIWFpl
            Q25PSDB6dStldmpBcDZvZkQ4VnJnL3VJOUJvCjE5ZFZBdUVUdld4V1NSS3pna0tT
            bkVOM2xPOVhRQnltT0kxWjdyVW5qZkEKLS0tIG16dkhWSm1pN3pENWJDTmd1NHY1
            aldIa1NCNW9iV0RFQU9PazJ4M0VzZ0UKK2t0jqKQ9z6uUC8J6HQLWznSy8+iog0E
            Pnnri2QHJiSgujJInfYDGc8uEP2Ji3RWIIO3rwe0GIkOVPDMpXiFEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T03:03:50Z"
    mac: ENC[AES256_GCM,data:V9UoJQC8uBrgETFH3MiwbQoJl5G7z/GKZT8kNBdl8A2z7keyGc1fST5IBl34lg3tD/sIHikPehG6EGWFWOlseF1jJ7wuqH1qkpbaU+6wWJVVdrH05G3z2To8cjUgYUGOYTUhIETwBZitdU0ArZb6H/FMzIvdRggD5XC6b5MuqZI=,iv:70rt/quc6PFds2ZdxdLAKPQ6A/7GrcNgc98c1Nwr7EA=,tag:9WUHaQLq6DuvLPf2A1ToTA==,type:str]
    version: 3.13.1
