apiVersion: v1
kind: Secret
metadata:
    name: semaphore
stringData:
    client_id: ENC[AES256_GCM,data:T85chz6HIMKefOXwyQJanUfpBy04S8xo3C+PTvyM1xf8T3LyjSoO1A==,iv:Y801tU9Vk6k0tHxHcEIrgPlri1iUXnO55X9gVtud9Gw=,tag:ECMJ4zMB+8T/PJ+rkZI9Mg==,type:str]
    client_secret: ENC[AES256_GCM,data:Ui0OKsrwgjjx8PbQq/hlT5qg4zJ2faLrab2TO6nWOYTYTKQC2GeOGDK3uLLGrJO8L1tiEBHjCz6UlHOxJSyIcGnjIhxWebKwEsZlHXb+mz7RmGAFP0ROSVHnBQDISh4occOYukkOgczbhYG34fGl95H0SLaXz6Uq0SnN3K0ZvMc=,iv:yJi4CTe3c8lghek5gpn1ynTg0/q74OlvwRFFnY27yt8=,tag:WEIiFa6MN4xSMiD17eBn8w==,type:str]
    admin_username: ENC[AES256_GCM,data:qZ4/PKo=,iv:FpA5YnCVWegfQgmVuUuumB942pY9sg2h20y4xTSdo44=,tag:7ZAcgl7TJcF3LFljDjNsIA==,type:str]
    admin_full_name: ENC[AES256_GCM,data:dtDxYjU8Jj5BscDU,iv:3I4uGZ6pKZjSnCF/FR5GtTSXtASE0cupxmvJ7UU0ZOQ=,tag:gKxV3RvbNPSW+IuuHySHfw==,type:str]
    admin_password: ENC[AES256_GCM,data:ke1bug/GnKsXurlf16o12JKgp9fkEbdNIt/ZQ6V3oKBU8J/JBTqqtgNh0S4=,iv:h1CvrDyVG2ZyjLl3eyIif0hiKrarF7rCJpZXPcT8Ij4=,tag:vqnpLm0bM9WaofHW+mPzkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZXYzRWF2UTE4SVFOSTRX
            U0xPdmhMWE0yYW9MREZxTkFFbU9PbTdDNDFzCm91WWF1KzBDMURSYVlrRmdzSnBt
            MTRyZG8wTzNWM0p0a1NMQUtkcGsvVVkKLS0tIEJBVUlOajRKVFh4U2NLMFpDR1lS
            RHZWSlk3R01lRms0VmowOEZDTjQ3L00KEDePpEtCeVjOUAAudW2EFQ47VruM3Cfe
            JEebr91F7UD9/rwpyMME/lodIjyyES+F+tA6m5iUiFD57K9/iZkFYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-07T00:37:59Z"
    mac: ENC[AES256_GCM,data:kEOMECWIrTv5fq+SLde5w+01vf5JAsjwo39MLjlLFOs/dovvhovB3biMbIJ9sg769MvfqC2mTeIbH1jraOF912gM0fT1+q92tMXDsQ33OzzXCYlaF9vtq51pvfmw/RoYh2kAf1XvtlOgWP51WgsSrPzmML7QP6rc02Eijd9M0hw=,iv:dL617QICQuLOuBMCXeoB18WLj+J/lt+kvF3ggo8UE8k=,tag:JYx+m2ncQn1enq6GFm7nnw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: semaphore-postgres
stringData:
    username: ENC[AES256_GCM,data:4qo7ggRD8KKl,iv:8R96Sxgk/WP0JNJATPu/yrhPT9ij8n4Jz8wCXoJMReo=,tag:n8r1HjqWAb5gmF7uEAmvJg==,type:str]
    password: ENC[AES256_GCM,data:3eWir/CDx0vI6fLjmn62s6h0J0HLzJCDXKX2ML7dFQL/yId7pXnoU4uhFv8hy/s=,iv:JFcyc6dlMZObfVGASgiQAuUMrJy/Fx9EeAUiAomEkEU=,tag:0it0h9t5q5sUM5ocSY1Y8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZXYzRWF2UTE4SVFOSTRX
            U0xPdmhMWE0yYW9MREZxTkFFbU9PbTdDNDFzCm91WWF1KzBDMURSYVlrRmdzSnBt
            MTRyZG8wTzNWM0p0a1NMQUtkcGsvVVkKLS0tIEJBVUlOajRKVFh4U2NLMFpDR1lS
            RHZWSlk3R01lRms0VmowOEZDTjQ3L00KEDePpEtCeVjOUAAudW2EFQ47VruM3Cfe
            JEebr91F7UD9/rwpyMME/lodIjyyES+F+tA6m5iUiFD57K9/iZkFYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-07T00:37:59Z"
    mac: ENC[AES256_GCM,data:kEOMECWIrTv5fq+SLde5w+01vf5JAsjwo39MLjlLFOs/dovvhovB3biMbIJ9sg769MvfqC2mTeIbH1jraOF912gM0fT1+q92tMXDsQ33OzzXCYlaF9vtq51pvfmw/RoYh2kAf1XvtlOgWP51WgsSrPzmML7QP6rc02Eijd9M0hw=,iv:dL617QICQuLOuBMCXeoB18WLj+J/lt+kvF3ggo8UE8k=,tag:JYx+m2ncQn1enq6GFm7nnw==,type:str]
    version: 3.13.1
