- name: install prereqs on rocky
  become: true
  ansible.builtin.package:
    name:
      - bash
      - curl
      - tar
      - gzip
      - ca-certificates
      - python3-pip
    state: present

- name: install kubernetes python library
  ansible.builtin.pip:
    name: kubernetes
    state: present
    extra_args: --break-system-packages
  become: true
