apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-credentials
stringData:
    password: ENC[AES256_GCM,data:CkCqFp7k3W2DGW2tBjCu/xSN3j5zlBqFaKJl6WtzszYPW6y4qA==,iv:eggjtHxzfPJ47ZAlM3VRRCljIxlT3O3+4oLXlrII9lc=,tag:+QIaPhloRGBv8plg2cMAWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbkVodGdSZVdmbndYK1Nj
            TUpaYWtreEE0dFV0SytNcHdpcHhsYU9WM21BCmpKMmY2bVBJYXVwSGxyWngzOFVZ
            ZXdMYStWVUFkbDFZb2hqUXA0OFFaMGMKLS0tIFZPdkF2ZFRGYll3WHNodkd1REI1
            NFZIMlhDWE0wcGViUURnL0kydkU0UjgKEuMjGQkGXKp6idwcL5tQg4JkcTgEHitW
            11zGA7omEmNVqXRJ5HIl9ZzvKE8gpYBI/momwgvcxsMNTBsIhAGP2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-19T20:33:24Z"
    mac: ENC[AES256_GCM,data:8O4YSH0+IzOJUvTzFdQLGtw9oALExx/NYqIOcbhaRz1PzWU7lwckZkdMAkOMnFIX+qC8Z+pSXA8StcbC5Y2tqqC9TVJXaVUCrT/P1+qX2LovBZjtL2YSTTvk3HlAaSRc8YjMu0znEjRNGgf9HadrHu9S/8nvmMDSn2PeW8UdVRE=,iv:jDg0nxGGBtVOlPMz3OA1L3gEENVkedpKP1OrZu/FwI4=,tag:IPDYfhQJMIxVsT6qWUeFFw==,type:str]
    version: 3.13.1
