apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-vars-secret-external-secret
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: cluster-vars-secret
    creationPolicy: Owner
  data:
    - secretKey: hidden_domain
      remoteRef:
        key: cloudflare/hidden_domain
  refreshInterval: 6h
