apiVersion: v1
kind: Secret
metadata:
    name: kasm-brave
type: Opaque
stringData:
    vnc_password: ENC[AES256_GCM,data:rGdmr4oYDH3qJDEB6mmxa1NnYGrZqQg5AnxhdcueVpqQPPbdEOwH,iv:4BEK6DnnuWV3AZHg1WYTI5DhMVQGwg8vWn1bUW0zPio=,tag:HO9Hy5vxL1a7ghjwCmhG3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUGNSMW11QmdaVnVsanNR
            YTAxa1pBU1VJUW83T2N0byszZWZ2TitDK0RZCjFmTW1LTXhzTlpiMWZ0V0JaYWps
            R1crRG1PcWtBR2JzVnBvUzRoLzB5U2cKLS0tIDYzVTJJVFhDc29wdzFTbHN1aFMr
            NGsrWDdMS3ZFb3Ayd0NNeGUyNGhLMlUK4i5QBW1S52KhsB/Lf1AImv94el3AQPAm
            tVg4ORDL1UPda/uxkM09vVIPiVkLmh5nyO+RUh2st8JkKOdMBY80GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-12T02:03:03Z"
    mac: ENC[AES256_GCM,data:4TOQV2I+2n4IkqjNmQ8uOH/gp2SB72lhipYYL6W6OIm8tltjxhPyqSuNIoB54Jrb0xlufhQGeMcNmQrSbRbDX3lMUS+Ov18LdNeYnLqvEjnksPngpLkJ1J3zZevk6rk2gRLcYgCw88NlKk1Lqp+4vRPt/wNG7MMpzPaogTx/3nU=,iv:lV9Zr0tTD4Lx0wFhv0kjPMgMOfJHo8oqrVG+35xDDqQ=,tag:YFlPvJGTVEgeFx+Sd/ROlw==,type:str]
    version: 3.13.1
