apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-external-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: prowlarr
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prowlarr
  refreshInterval: 6h
