apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
    namespace: media
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:0V5UyMALG8fG4ugRyY9cjZhqVtgMPu6IxJIbw5Mb9mM=,iv:BUR6XDQOzNmQ+N286BmtJX0O3dPFCej0ifsi0porWVI=,tag:2HsqxyTEI8Tiy2LB+EeYZA==,type:str]
    PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:ZTKE1CI/uWmIPYS18xUwRnJ2anE7WDcNg+jF2LJPfb5FQz1ukUmGD3tXGa6Sulc=,iv:Ufkt+l6ykr4ExVkdA2eL5ZlVgJJ49c/dcQGJcNSrj4U=,tag:IcpYTIB2wA+26MMyF72hYg==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:VD3157HhYmw=,iv:L16qahDJOUVfPAy++zAWnKpXZ3C3frAxVOHM0ku8Ixo=,tag:LzcXonxO0YzaWudrWEftfA==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:47qorJ7fCnEKg0MPWtXvT2hTxcr5wZ3fyKypvKLc+GYiX9GNIn6gY83XGWk=,iv:f+RctEDt+51QpkXiZxWLNNh7eLcD0+4GHEbTEHkFo0Q=,tag:+Gj9XVtd91m+O3Q8zZPZ2w==,type:str]
    PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:473XtPzW6D4=,iv:koDO0r3Ow7NnaG0C4CgvCA7nJNtWO3GrdRdEM++zsIo=,tag:oAX8pp9IjabjeMWD1xTArg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMVBSampPNEZMOFdkWmtq
            RkU5MzVTQkltbVp5eXhHMmhKNHJNei9meFFnCmIrKzZNZ0V4d2J1UTZYT1g3bTRo
            ZTc0bGh0SVRkd0N6cTFWWXNlREVZZGcKLS0tIExhUnhVS3NsMXE2d0w2Q2Rsc3o1
            dFZrMmY2OUhVdGJCNkY1aEk0MTN5d00KLVpH2HNz/rpKcqFfTLq9xROK3xgOqf5d
            l07nZwYiJkpN8xRKrz54LtUQpsdsYtwDBms8RV4YTx7acXl6RyCXRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T11:23:06Z"
    mac: ENC[AES256_GCM,data:LXCwW+tIQ2s/bTekCieQXn3hQqGRqvcsAVD/umref0mRz6cX0LYWD1e3b3Ans6Jmm29dRcYp+gqyw9NGjq0qJQGd6smLn33wsAYU0S0NfpxAwLqTuE1fHHhjLKF1w0W4dfAEvsZkidN68veKbgDQ5YO1+fibql4l3tj9DyjRrrM=,iv:TH63n9Y0rFST2OMdxTgB4sCRoJZ207WPNxzqxuHiZvE=,tag:lqGeiyqXf2/5FO/8wmN/oQ==,type:str]
    version: 3.13.1
