apiVersion: v1
kind: Secret
metadata:
    name: firefox
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:WeIEZcQq,iv:04apXqfG8/pCUqojX73CSyd2uKizibiXSGSy70zrRR4=,tag:C4SulmWVTUfejUa1kbSN8g==,type:str]
    password: ENC[AES256_GCM,data:E9OE1p61hyIQhkepf//znEcBwBH8ZKq4J8yUsbUVn7jY4yQiiVa6,iv:OHFJYTDJqfndWqZnRbPjWBQXezuzYBLBzmTCrR7iICo=,tag:D5Eu77KZ3Rxadfeagvzr8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZzdLQVBVRHcvZVNvZVkr
            SGdtMDU3cTNYbC9xUnNRUWpNY2R3VkwyR3lVCll5WENmOE4rZUx4WDZoRkovcG8x
            QldGWFRtNDRzOUZzZGYzNGtEYUUxdkEKLS0tIGF3VTVQRUkxd3NlUmJnQ0ZvaVBU
            QlJKcDRoVHNaTE1KZFU3RGhkMERPWXMKbtC3RHewLYS0aqlzrgnNY44dWCcmI3X6
            MWZF4TtOHI1Z5oTQezRJKC7KJOGlghnXfyNEk4OS3Li8YNCXta9T6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-12T02:05:01Z"
    mac: ENC[AES256_GCM,data:lEfyEnVTODevFBIR4h+JLoM6xMX/5GHFL9lpZ+GgQGo+1msjiJCUK0W4Xog0oWU/1QlBFBqrBu2Hi24qvY3NGs60cVumhdgJ/FkjIdsFsqHZlGWL3BU5e6OJyXmlj5T8dO1FjmNQhr6x+FMdWZZdNG7DlB6GAciiX0gnCf+R4OI=,iv:RT+xBwpnFG6GmPVcI2k3bosv/Xvj32M7QLpLD33p65A=,tag:1g8KBJmZlKRsnuSZv+jBUg==,type:str]
    version: 3.13.1
