apiVersion: v1
kind: Secret
metadata:
    name: firefox
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:/45dThwW,iv:T+TIAvplbiDgMiWGgDwgZnQ9edVbWU8RNyOTV71QDCQ=,tag:bbyj/g9RvvLbxj9IpTzX4A==,type:str]
    password: ENC[AES256_GCM,data:p3oUx8/5jCXE0TmFKJVTDYEd8KIaQfoWZTJ95SDoRiXS2gYkef/2,iv:Tfi+I7ZU1+qsVgWquxuV4yPWVz317yeyzcMDW+tcwyo=,tag:tgsWnwavZzEMVDtKwiZjNA==,type:str]
    users: ENC[AES256_GCM,data:Ncqt2kHWT1FU07dXffLIlUDYlmDV2CsnBA44U/nm2ztnAw85gFlqaGhcSniH9jjIUvh9WZuaaMShVwJR,iv:vXfXWnfwvNMD5ZPvrUiSBfDZmVwVgGkxqbX1MKNAvvQ=,tag:+gi3qZvdPQixbkIFXdKyPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WldLakNVZlkxSzl3eXFn
            VWhWZDY2czlHbmwwcEFwajlNTEw4d0l0clhJCkhERjZHZyszUzVvYy9SM1YxYkY2
            STg2dzlLYTJhaHk2VVVnTXVNSnZBWncKLS0tIEhDYVZ5cTlBRW5LcDFFelZrZFN5
            TzB2QnZ4aVBWQ3hMblBCOHNMTXo3dlkKPvcom10jG2RIWm+PLvlQWD7wd8fZuyB6
            kWkyE7vkxR9faWRIlZxjlyNtzYp2gxBgfN1JOqEf9Zoy4lbpNQ2rdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-08-16T01:40:04Z"
    mac: ENC[AES256_GCM,data:EmmwOCnzblVY4A0oKR9LB+j46VgehV3GGC6ebAJEx85+8W2xluTmdCtgP6AVT4j36mo8l9KYePNSdhtZPAEi4NHBzDvBclnpQpqskPJHJhGxWddjcl7WdSi/4tZ/9wIKv3tvUrJTuRuIsksiPn1xWqJ7f1IGoanhFbDwsmqayvs=,iv:kMsEPxL4hNtQgxqHVsmeL7eym2UpEGmaMDTWO+RV57g=,tag:VU2f5LJjrwiGqoAU1zoU7Q==,type:str]
    version: 3.13.3
