all:
  children:
    cloud:
      hosts:
        kubernetes-server-01:
          ansible_host: "{{ lookup('community.general.onepassword', 'netcup', field='wg_ip_address', vault='the-white-lodge') }}"
          ansible_become_user: "{{ lookup('community.general.onepassword', 'ansible', field='become_user', vault='the-white-lodge') }}"
          ansible_become_password: "{{ lookup('community.general.onepassword', 'ansible', field='password', vault='the-white-lodge') }}"
