apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-db-agent
spec:
  interval: 1h
  chart:
    spec:
      chart: teleport-kube-agent
      version: "18.8.3"
      sourceRef:
        kind: HelmRepository
        name: teleport
  values:
    persistence:
      enabled: false
    proxyAddr: teleport.${personal_domain}:443
    insecureSkipProxyTLSVerify: true
    joinParams:
      method: kubernetes
      tokenName: db-agent-token
    roles: db
    databases:
      - name: apps-cluster-rw
        protocol: postgres
        uri: apps-cluster-rw.cnpg-apps.svc.cluster.local:5432
        tls:
          mode: verify-ca
          ca_cert_file: "/etc/teleport-tls-db/apps-cluster/ca.crt"
        static_labels:
          env: homelab
      - name: data-cluster-rw
        protocol: postgres
        uri: data-cluster-rw.data.svc.cluster.local:5432
        tls:
          mode: verify-ca
          ca_cert_file: "/etc/teleport-tls-db/data-cluster/ca.crt"
        static_labels:
          env: homelab
    extraVolumes:
      - name: app-db-ca
        secret:
          secretName: apps-cluster-application-cert
      - name: data-db-ca
        secret:
          secretName: data-cluster-application-cert
    extraVolumeMounts:
      - name: app-db-ca
        mountPath: /etc/teleport-tls-db/apps-cluster
        readOnly: true
      - name: data-db-ca
        mountPath: /etc/teleport-tls-db/data-cluster
        readOnly: true
