apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport
spec:
  install:
    createNamespace: true
  interval: 1h
  chart:
    spec:
      chart: teleport-cluster
      version: 18.8.3
      sourceRef:
        kind: HelmRepository
        name: teleport
  values:
    operator:
      enabled: true
    chartMode: standalone
    clusterName: teleport.${personal_domain}
    proxyListenerMode: "multiplex"
    authentication:
      type: 'github'
    extraArgs:
      - "--insecure"
    auth:
      teleportConfig:
        teleport:
          log:
            output: stderr
            severity: DEBUG
        auth_service:
          enabled: true
          listen_addr: 0.0.0.0:3025
          public_addr: teleport.${personal_domain}:3025
          web_idle_timeout: 1h
          authentication:
            locking_mode: best_effort
    proxy:
      teleportConfig:
        teleport:
          log:
            output: stderr
            severity: DEBUG
        proxy_service:
          enabled: true
          web_listen_addr: 0.0.0.0:3080
          public_addr: teleport.${personal_domain}:443
          https_keypairs_reload_interval: 12h
    podSecurityPolicy:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-db-agent
spec:
  interval: 1h
  chart:
    spec:
      chart: teleport-kube-agent
      version: "18.8.3"
      sourceRef:
        kind: HelmRepository
        name: teleport
  values:
    persistence:
      enabled: true
      existingClaim: teleport-auth-data
    proxyAddr: teleport.${personal_domain}:443
    joinParams:
      method: kubernetes
      tokenName: db-agent-token
    roles: db
    databases:
      - name: apps-cluster-rw
        protocol: postgres
        uri: apps-cluster-rw.cnpg-apps.svc.cluster.local:5432
        tls:
          mode: verify-ca
          ca_cert_file: "/etc/teleport-tls-db/apps-cluster/ca.crt"
        static_labels:
          env: homelab
      - name: data-cluster-rw
        protocol: postgres
        uri: data-cluster-rw.data.svc.cluster.local:5432
        tls:
          mode: verify-ca
          ca_cert_file: "/etc/teleport-tls-db/data-cluster/ca.crt"
        static_labels:
          env: homelab
    extraVolumes:
      - name: app-db-ca
        secret:
          secretName: apps-cluster-application-cert
      - name: data-db-ca
        secret:
          secretName: data-cluster-application-cert
    extraVolumeMounts:
      - name: app-db-ca
        mountPath: /etc/teleport-tls-db/apps-cluster
        readOnly: true
      - name: data-db-ca
        mountPath: /etc/teleport-tls-db/data-cluster
        readOnly: true
