apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: teleport
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:ixgVP41cHmPYN9nkiQrx81QkXQKeDxIORWv7/PswG6iTPP0R,iv:ekP2kcZqsDie+dxbNa0ZkRRTewEWsBIRYG3gqzbQhzg=,tag:reXrnOxLQ0E3ZswyEQlzTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0c3J1Y2JrNnhubUtFYUd4
            S2FwZUsvcXpNNi93RC9ySlE4Q1ppSUJmRjJzCmp0ZW5nbC9xS0ROUVZwVWFUZHMw
            WndPS0VyVTlvWk96TDZMNGFoclg4aUkKLS0tIHRjZFRHMTZKMUZrMnZtYVkyR3c3
            bzl2WjRvVTVWS3Awem9CenUrQ3lndGcKR+Hkb2rp+luSR4asm1q+K5d5aFraElS8
            jTIgs75sZbwTgZPHQMHo7Hpp9VjHvfRg2ZhLskHDXIlj1wviz1EeJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-08-16T01:48:18Z"
    mac: ENC[AES256_GCM,data:EFzh6kKDbLkGa9lBDPT/14biSjYq/XoGQR4lDsd9bMxZIqTMG+AOYc58mXd/pCRWKOtA4eeb200ldh642MnCxKQMcgKcLx7ULET3+Wy6akgngFAAWDlNSWuabc1zHbGyk1MbeuZL7khItaGvB+GNCWSUIPTfScty3IrdhQyJss8=,iv:ub4Wa0Ia+fY1+WAOgkGTEY6PB6mNEp+Hw3/HghswjG0=,tag:MGzZuUiNIpg7HMQ9SRpbjA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: app-cluster-server-ca
    namespace: teleport
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:Tyu7ou+/lHIUdcacvcEWEwDc/AF2FwRMuydx2ke2Q6QlPhWXQZrcB26MgvBetluWgT+O43UbhQPz9q47lYA7c2JqIpET7BLpscmn9YWJ0/zqP9Arox6hK6UQVNYeKUh3M3CYp2jDJ2JOlIXO5fVHLBduw05+Y1A3nS2ScGFBhqKeFLuVtVq1XSrGN4orZZ7P81wa9YpwVSlirJ5sDLdStQIWegm9uq3akY/XNExSvAuK+eoMi7ovT0q0T4Ttm/lXZMAyJR3JIHJuwalThDGJpg60o9onp0tFYNpouW9kDgcAlVMV+wimsrRmP5nxX8dyMfVNyDbzSAL75i/BghasRSgTsCCi77rPSQMfaznokVsTypO+S+JqjBOAg/TAPiEHyOp90TpbW8DthpaDWwVl2lBdDh4K1bWgPRFWL77Rnx3GhAVT+xvQpuYWmT30ZmoV4oQu45lyEZJZfzSB4FEXe7g5xIgzg/5bz3sZTUFXQpWJ4z4sXGf+43b8ICuAyRgIAuO7HOKidDnlgXm9HnxVcRFsj/lZxOoI/SCJKrkGVjmaxP1ewW8Pkkf1nwBo93FeLTcoSLzEIWYvezoj3ii2uambL2qocWsiN46RdUwK61hzv8+VSbPPHQLBh099W/90ANZDJiT2c+bJFqZqZ3rwm+telU3XRlT54707VF5NYlVYr2gNeKIewPGqhhtD/XgDCCFjXhRyGkCniVAxYhcTNyaRbjufO9/odyNUyNFSeUxPMgKw2Xv70iXFOOiUiwXhqKxhJAA/eUnfiZ6Wa6+EMReQZJpk4C5AkCsxart7YsanC0IyFUTS5xoAkziaALc=,iv:qjsReqvSlWjTPbL+uhhIGlyPRA4KRCddmWNEXZ2E9gI=,tag:VXQXmhSWefcOROkAUIgaJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0c3J1Y2JrNnhubUtFYUd4
            S2FwZUsvcXpNNi93RC9ySlE4Q1ppSUJmRjJzCmp0ZW5nbC9xS0ROUVZwVWFUZHMw
            WndPS0VyVTlvWk96TDZMNGFoclg4aUkKLS0tIHRjZFRHMTZKMUZrMnZtYVkyR3c3
            bzl2WjRvVTVWS3Awem9CenUrQ3lndGcKR+Hkb2rp+luSR4asm1q+K5d5aFraElS8
            jTIgs75sZbwTgZPHQMHo7Hpp9VjHvfRg2ZhLskHDXIlj1wviz1EeJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-08-16T01:48:18Z"
    mac: ENC[AES256_GCM,data:EFzh6kKDbLkGa9lBDPT/14biSjYq/XoGQR4lDsd9bMxZIqTMG+AOYc58mXd/pCRWKOtA4eeb200ldh642MnCxKQMcgKcLx7ULET3+Wy6akgngFAAWDlNSWuabc1zHbGyk1MbeuZL7khItaGvB+GNCWSUIPTfScty3IrdhQyJss8=,iv:ub4Wa0Ia+fY1+WAOgkGTEY6PB6mNEp+Hw3/HghswjG0=,tag:MGzZuUiNIpg7HMQ9SRpbjA==,type:str]
    version: 3.13.3
