- name: Wireguard
  ansible.builtin.import_playbook: wireguard.yml
- name: Firewall
  ansible.builtin.import_playbook: firewall.yml
- name: Kubernetes
  ansible.builtin.import_playbook: kubernetes.yml
