apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport
spec:
  install:
    createNamespace: true
  interval: 1h
  chart:
    spec:
      chart: teleport-cluster
      version: 18.8.3
      sourceRef:
        kind: HelmRepository
        name: teleport
  values:
    operator:
      enabled: true
    chartMode: standalone
    clusterName: teleport.theblacklodge.dev
    proxyListenerMode: "multiplex"
    authentication:
      type: 'github'
    extraArgs:
      - "--insecure"
    auth:
      teleportConfig:
        teleport:
          log:
            output: stderr
            severity: DEBUG
        auth_service:
          enabled: true
          listen_addr: 0.0.0.0:3025
          public_addr: teleport.theblacklodge.dev:3025
          web_idle_timeout: 1h
          authentication:
            locking_mode: best_effort

    proxy:
      teleportConfig:
        teleport:
          log:
            output: stderr
            severity: DEBUG

        proxy_service:
          enabled: true
          web_listen_addr: 0.0.0.0:3080
          public_addr: teleport.theblacklodge.dev:443
          https_keypairs_reload_interval: 12h

    podSecurityPolicy:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-db-agent
spec:
  interval: 1h
  chart:
    spec:
      chart: teleport-kube-agent
      version: "18.8.3"
      sourceRef:
        kind: HelmRepository
        name: teleport
  values:
    persistence:
      enabled: true
      existingClaim: teleport-auth-data
    proxyAddr: teleport.theblacklodge.dev:443
    joinParams:
      method: kubernetes
      tokenName: db-agent-token
    roles: db
    databases:
      - name: app-cluster-rw
        protocol: postgres
        uri: app-cluster-rw.cloudnative-pg.svc.cluster.local:5432
        tls:
          mode: verify-ca
          ca_cert_file: "/etc/teleport-tls-db/db-ca/ca.crt"
        static_labels:
          env: homelab
    extraVolumes:
      - name: db-ca
        secret:
          secretName: app-cluster-server-ca
    extraVolumeMounts:
      - name: db-ca
        mountPath: /etc/teleport-tls-db/db-ca
        readOnly: true
