apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleport-auth-data
  namespace: teleport
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
