apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:L5k27gkMO4ulaztIhOO4oEgV2HolKacTUaCJ0j8tIAdW3ID+,iv:gB6p3dP30wmY/c7aHs+2W24S8+zzaGeCQs6nGsF8eAw=,tag:oMhCzGf8+hgs69LokVl3HQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudE5TQ0ZaMTVEZ0RHaCth
            OU12dXBwVmVNMTY3SVVJU09aQXpkTFgyK1VZCjFTREplT2pVbVJlWHorSzBUZnZN
            bTBNbHVhUWh5V1FSSjlYbFoyOXkweWcKLS0tIHZySktoc21sNE83YkN1dTdUWTJY
            R0tnSVl1UXRoZ1dGM3VaaWVKSlB2Z0EKqPgiqwtIrdB/A0WMGnenz8AerrJBy5VY
            tbvTihoMYiwcGMqaaEgq8NyZcpjBpT6u61RVZtkGS4GaQIUyQdxtug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-17T03:20:07Z"
    mac: ENC[AES256_GCM,data:VBkf6kFLe0TiEwtUeInh7oTufkXjS2exFp5P3mdvSfbxicJgxz1dG3UGsHNZU8u9OBTcxsrYcYTjsMIG4B2xOsDPprx0d81shMzDfRcktarub38jd9sjc/QKGvj/mGXl2b1AfDzwh7xMXwMFFJUQUYb9ivEGADVJ3mlJaWyDFWc=,iv:KsG9b+C5DAy+WWMa2CRlxy98ZW9IPZwXGGmRxtR/54s=,tag:mwatpOQsFRphipXAp0Kzbg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: app-cluster-server-ca
type: Opaque
stringData:
    ca.crt: ENC[AES256_GCM,data:5+Jawyu5AGMAZ+KHqunBA+I1J3+A3cUOrlxAylKRGbeUku1sgdMTavfYihTeP7VaMPIcYCwhkJTBL7HJX35DyX2ptIqxsKkREaHzWCHfDsO6HVPws8FAXhbviazqi3O6QEhzy/IWcKrxfWXe6Z87iFZ9yZevoRf6EyW8ZO2jq4iOkkp2O0Zw+9sPErOFLjZGj5w6UXOPmXqxeSLYzWY7HDuXUCRqA7p2ekaby5DCC8bzchupDByDpxsyJPmxg2tJs+iGm8cq4OR2nrTKy+fclalt1q7SpjqRESF5i9X81ucv/iB5+0w0BtC0zXk/SJjtyQu29rt6ohSDD4V/fDseH3Ne3cLLSvdi5TL6ZKZ5rI1PKsb/Hjz5OlwXaQ/hdK4pYMIeqpINFqYINAjHb3eKM5toFR0ZZhmKBcu/Y3adJCT+6j5cFpH3c7+I5Vy072FdFuUy9R84eYmhH6VtHwuzcOKpULxg0Qy/TyckoXozuqeb5CKwnWIVRfnR+z4Bn2/zURG0K2CB68jfbyukaRrcUKZGD4b7CuwLk5pVn18r6hIkhx5ryx1lJFRJMSZO9QSt0QdVwbp2VFJzmOPPHaKdJB4Qt8v0XwUSSttEae4DOb2A/DJIM6j6IkWHhadMECtSwCenuzHILAcCLV7CxCgn1VTnd569jK6t0jkb6IqtQVXB0c/rT+VvUh1EgDei3ck/jWhP+PEKhw+Fk78bhgqgjYihEqEJ/xZFaMKf2/+jcWE3F0Kqkz8aTsdZfgzwIPrpNVnbXuUivDlexSbrE2vFPwZ1bFbzmBGx8nf3cd4PM01gze+ybh5a5k9P646Otrc=,iv:rquX5RqMka0bM7rbjlQhSKw7Z3P8olCIZZ3pGtqzdqQ=,tag:lPyXtZNf3wtd8vXnRdMowg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudE5TQ0ZaMTVEZ0RHaCth
            OU12dXBwVmVNMTY3SVVJU09aQXpkTFgyK1VZCjFTREplT2pVbVJlWHorSzBUZnZN
            bTBNbHVhUWh5V1FSSjlYbFoyOXkweWcKLS0tIHZySktoc21sNE83YkN1dTdUWTJY
            R0tnSVl1UXRoZ1dGM3VaaWVKSlB2Z0EKqPgiqwtIrdB/A0WMGnenz8AerrJBy5VY
            tbvTihoMYiwcGMqaaEgq8NyZcpjBpT6u61RVZtkGS4GaQIUyQdxtug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-17T03:20:07Z"
    mac: ENC[AES256_GCM,data:VBkf6kFLe0TiEwtUeInh7oTufkXjS2exFp5P3mdvSfbxicJgxz1dG3UGsHNZU8u9OBTcxsrYcYTjsMIG4B2xOsDPprx0d81shMzDfRcktarub38jd9sjc/QKGvj/mGXl2b1AfDzwh7xMXwMFFJUQUYb9ivEGADVJ3mlJaWyDFWc=,iv:KsG9b+C5DAy+WWMa2CRlxy98ZW9IPZwXGGmRxtR/54s=,tag:mwatpOQsFRphipXAp0Kzbg==,type:str]
    version: 3.13.1
