apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickstack-external-secret
  namespace: data
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: clickstack-secret
    creationPolicy: Owner
  data:
    - secretKey: express_session_secret
      remoteRef:
        key: clickstack/express_session_secret
  refreshInterval: 6h
