apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: clickstack
  namespace: data
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`clickstack.${cluster_domain}`)
      services:
        - kind: Service
          name: clickstack-hyperdx
          port: 3000
