apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data

resources:
  - clickstack-operators-helm-release.yaml
  - middleware.yaml
  - service.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - secret.yaml
  - ingress-route.yaml
