apiVersion: v1
kind: Secret
metadata:
    name: clickstack-secrets
    namespace: data
stringData:
    values.yaml: ENC[AES256_GCM,data:Yjrnrx2Omhhf8QEzdUpmTpT2ji/yG6xBkQ+5GxQek0edWOYY9n2xKgprUjnWIzjfyVFhuR3hhXUhnUfSNi/O/jhm4n/A9Sj6JzKz3vbDrAMF7jpvCuvggD/FZbdje/+JEnONulz1WmVpfvPy6Mivh2k0zmJZquW5o7lwXFWdem9mD6WQfRxMbLIRYzpm0BEDIZJsS2QIYKaFYhQih7iqL3Kvm46bNSi9jUD3Jj04tFBFZgbI2Da3SVStim+ArU1qKBCe3wrNX+UILOoIGHrLkP0HCgVoqYqRra3RIroBWj9wbMacwJLmmcqlTvBcZtNKwTtQHNzRuHM359+JuTZASVZThNqwlqV9B5iFnzmcP6VdNZnJfs3YPgGk+C4tdaEpmbJXAFGdHLyU/kfm,iv:4JGxDTqe8zphuqLcaF4g/vhQsx+ow5P1JDqajPoqwMQ=,tag:PHLp/y0ETcUL5GYDaPTL2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtenJtZWd5Z3VKc1I1SERh
            cmFMditEMnZ6ZXZrVXlQcWtXMUUwY1Q0Y0Q0CjVMNTZLa05LaCtkMGRQc1FVK2hP
            RXA0RWt0clhXaTlhejFMTmJkSU03KzgKLS0tIDRkTzFEVW1ENDg1RU5aNi91YjhR
            dGxoNU5ETStSaXZLU1g0cTlwUWt5K2MK8Ss4wGnMIWKQCh9ASQXzg6yKbwBR7Cml
            A1Iv4q0/EwVbh106gHo/PeJQ4camVtab6DoMD382p4gX8rWbS+fu3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-14T02:35:29Z"
    mac: ENC[AES256_GCM,data:P4qDK/sPOMYcEHxRjBNSsRnJNuM5ZyIiw3Z0889Ln4ywpZOlQoukVrhUU0s2o9eu4+1I7/MQzWF1ypK5/AecrsAkZN3vdM5gLDKArawTBhxF6tSI4d9cx30XUAFM3YPLVvk1Zej4IPHYiZH98gq9ZRiqgeTLYAD6doEbzrI48mI=,iv:a23vKvTCPY9+vsGqQpVWjfZ6NDByB8leDIvo/WJI+XU=,tag:C7qETyIdwX/X8ku3nVBQOg==,type:str]
    version: 3.13.2
