apiVersion: v1
kind: Secret
metadata:
    name: clickstack-secrets
stringData:
    values.yaml: ENC[AES256_GCM,data:Mcip1bkhbi6xprEZpwWcR7oCyFpto9TX50hvqzH3/tqpiR4QrG7kbDUjGDnxEDVf75RZJawpr39vWQkDzh7MxnfuZiUtddkGlqg5+hOY5m1Kr408X/yz+zwjHXkjqbjlktwM+xXbcf+WH6bJe6/ll8ZZ1FgMEFiptJ2Ok30oaooSEV1lP0tRoIEplIhHYvGpOBwSsBuXJ0Zp9jdF4eTZjvxihPt7FjnWWmHLgD0oRiTueINNIwnwI6/hhNLtIPhgYCogPw0b90xWATPXEEi0gKDNiW6I6Gn0I90JtVmkAydZMYHGRDHkfZ9or2zQB4fmpzbdI+Xf6/juD6HcYH13pPXAZ2u6Pp/lPkpv1urS+Vp3LKHJE2VOkx80HK2IC/GCmwIs7I9xNyMSnPJt,iv:OcLNjvBcEaLtxIWCu7l1b5b9QKj09K4znUeIKDQDam4=,tag:a5WAkWabXk4t5+ClZ7/vVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQk91MGJqZTlOQmJKME55
            YmdWWGNnai9vTThmYkd1NTVMajh0VHJ5aUFNCjljYVRGR2E4dkJKdHhMK0pyemQx
            UU15Wm8rUTVqejRpMVVLNU02QWg3Tk0KLS0tIHY5U2NwbjkyZHJGVkZOOEJMLzBq
            d0I0Z0ZwUVV1TEdNQ2NORkkvU25mVmMK9kr3Pd3cg04D8EVe2yYia+1kWfNmt444
            rr2VvHZj07vmn7kX7Z7EKVl5aBEcyVkB4pzhHqsm3UxdgjGrhe12VA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-19T21:33:34Z"
    mac: ENC[AES256_GCM,data:6xsiG47MkBHln5gbY2H7vJWPLgwu40V+s1QaOPMdsBH8VcLK2oKARRva41mXdIpTTRRTe9JFaz/riU2V5Vre5oX2LUjNFzbZXsN1UqBwNP14xWhiqTr6ppDNdwZDbrJK6zk9NuDmaAYhsiZzLeSw2F6RNkeM9Bfgn9sGYts4nhM=,iv:vckPGuqkIcrRBKOMiHAu2my4V978C6Rdol4heiyPQCA=,tag:x08eq3OBHhpKDZAfEvzNtQ==,type:str]
    version: 3.13.1
