apiVersion: v1
kind: Secret
metadata:
    name: clickstack-secrets
    namespace: data
stringData:
    values.yaml: ENC[AES256_GCM,data:YQx31+VLvPmD4kxcVSpVj2f/B5AEo4SS3JA0pDScRwjEhy34oSDxH9j0ZYdyZKyjZVCngPYN/OOOxn3IDPS5a+NM0rOahKFXd8oy91L0Ka1LutFKxzgrVBVaSGJnQssZEAjtkffKO1TPYjKkJBZIvf5RzyzqqvHnNigrAUFg/zrP5tkjv63yQiItzl5vdNwLYCjNEp3r6vx5A+n8ZSvCLQDQoC06nFMUUunXDw9YsaDDrjQEN653TMs5qb3UsT3EL4eEQRpgm6Bm2fdAlRmI6uzJ27RQ7XcLQwSYSbbNbed8H9P84qBAzKDrSBKoQeskQ0ORQaQCqcc4THE8/YDKZoMiGVTa8YaVi2bqQWVkL8FAEm5B0xenMDo08C37lh621mQ9K6C3/TXcoY0zxlTt6xgprV9DfJyKMGPg1EHzbNbFW9IStplgYAoakz0emQw+j9iBWzXBsavYWRBe5L0oyDbiOw==,iv:J3TDc9knSyyw/k7FPSsJ7D0jq4DQMpWYKJ8iAntXQbg=,tag:WtlQWBgDjzPCP5HSQ3b1lQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMTlwVEo2aUlrd3RDaDZr
            WS92ZHZNa0lGWUdKTEZ0YnBRTGlnQWZ2VEhRCm1BYVFmcWNVT3FNc21rb1g2RVZa
            Y0dCeEZPWXplNjlIaGJVSlpGL3NzVzgKLS0tIEhGNEZCZStITHhyaGxuUy9JbVRi
            MkZwTmo5ak00SHRpV04zb1NDMEpHZjQKACDhu5J2VlrQ+BEzKQGL4s5/RCda1s8K
            dT+QEvNkHbKHK9qKyzrocHFS/yfY9gZ4c9GjEzy7sP0X7jLIi7ihNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-26T19:57:46Z"
    mac: ENC[AES256_GCM,data:S/ltOKSSYe3J2P66YQ0XuLgPtPge6JMQtXVj7/jDwvxZ0cP1Zv66HluOpbk9m6Qx3g5SJrna2vBZif+Tu1XpBB81GgXMXc3fLaeVDPAzea72N95sdX1dsefKEmoqh5nSkh3NsxCdHWEFIWW9MSfDni+olwBU40iy/8+/4Lx6PEI=,iv:xD5ze1mP6rMDMf4g6nrIZQNrNOONn51N9o8jk/ygctM=,tag:dMhi0m6ogodUP+N2R+ZYCw==,type:str]
    version: 3.13.2
