apiVersion: v1
kind: Service
metadata:
  name: clickstack-clickhouse-lb
  namespace: data
  annotations:
    metallb.io/loadBalancerIPs: 10.10.10.10
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: clickstack-clickhouse-clickhouse
    app.kubernetes.io/name: clickhouse-server
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: native
      port: 9000
      targetPort: 9000
