apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: data-cluster-server-cert
  namespace: data
spec:
  secretName: data-cluster-server-cert
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  duration: 2160h
  renewBefore: 360h
  usages:
    - server auth
  dnsNames:
    - data-cluster-rw
    - data-cluster-ro
    - data-cluster-r
    - data-cluster-rw.data.svc
    - data-cluster-ro.data.svc
    - data-cluster-r.data.svc
    - data-cluster-rw.data.svc.cluster.local
    - data-cluster-ro.data.svc.cluster.local
    - data-cluster-r.data.svc.cluster.local
  ipAddresses:
    - 10.10.10.4
  issuerRef:
    name: data-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: data-cluster-client-cert
  namespace: data
spec:
  secretName: data-cluster-client-cert
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  duration: 2160h
  renewBefore: 360h
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: data-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: data-cluster-user-cert
  namespace: data
spec:
  secretName: data-cluster-user-cert
  duration: 2160h
  renewBefore: 360h
  commonName: postgres
  usages:
    - client auth
  issuerRef:
    name: data-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
