apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: data-cluster
  namespace: data
spec:
  instances: 3
  enableSuperuserAccess: true
  certificates:
    serverTLSSecret: data-cluster-server-cert
    serverCASecret: data-cluster-server-cert
    clientCASecret: data-cluster-client-cert
    replicationTLSSecret: data-cluster-client-cert
  postgresql:
    pg_hba:
      - hostssl all all all cert
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "data-cluster-lb"
              annotations:
                metallb.io/loadBalancerIPs: 192.168.100.210
            spec:
              type: LoadBalancer
  bootstrap:
    initdb:
      database: app
      owner: data
      secret:
        name: data-db-secret
  storage:
    size: 15Gi
