apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-data-external-secret
  namespace: data
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: data-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: data-lakehouse-cnpg
  refreshInterval: 6h
