apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: data-cluster-postgres-cert
  namespace: data
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: op-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: data-cluster-postgres-cert
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: data-cluster-postgres-cert
          property: cert
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: data-cluster-postgres-cert
          property: key
