apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  - ./pvc-config.yaml
  - ./ingressroute.yaml
  - ./deployment.yaml
  - ./service.yaml

helmCharts:
  - name: audiobookshelf
    repo: https://geek-cookbook.github.io/charts/
    version: 1.2.2
    releaseName: audiobookshelf
    namespace: media
    valuesFile: values.yaml
    kubeVersion: v1.36.1
