apiVersion: v1
kind: Secret
metadata:
    name: op-token
    namespace: external-secrets
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:FOuTPXPQXmnJ/ElMDuaBGOu31CRoFsimjh7LCpyDAxnE3K4VOQK3vc4B9kUY7GlEwddaSWSvnxqnPBvdZHaoYAhVYlzhNiGhEfao8s6eUsdZ0WEVq72ZXUDy1s/3f7pqPEzAawlNAPMm74qWzaPZ6xIn3MytDfr2vK15ze/Tf5v7iavXSIi8OvPGEvTjpldVUEpshtfYPeISruaXj2mK6Ym2DJNm9516eO5wZrr5UoyJ2tXGmvskVsoaAxljH6HgigwVmDFrj17JsKXvJelioaAXYoto6g3NAhmnN3nqg7qLWie0wRMC57LJQEk8qRpUiLp6AN17vNZUGSAbd712ZhB/SkCMCgIel4kIyTawso9BY641v77A/gCckxmttIme7OU9sDYrJpY3uIXxDBiv1h0GwGHCQPniLz7KAzWoujQF64kYPpNVGr1V79Wjwxu5M3u3/kMCsHQJ8e9kWOaO3ERbU7zV719RWKoqiY3rsALrO7WTtrHUOYyZhA7qIxRKrJdI+GxzcGyZ9GO4nnDVCf2rdmF/c6ucVoiT4OlOheIADv9PH/OSLtoAqC4B9EovpbUX+uopHJ5x2Dwl5L2dEt5RsU+UYmoaFk0OdDKDt8552ag+b8isucyb9BFT1CvB2yx08yRJUYq9ka6CoIPoYPaUkp0XD8J5yggtsJJ938UulZgt/cKDYtRmJ+ADhZn/teRMYaIwmtYS/UzVwJC8yAsWhetHyEhPuaCUMMNkx5IgKua+iqsUmXAeQP5UYQXbRyMWljejf8GD9JsZoe6T0HGC3NslnqDEIRtAe36avLWKDCn7uXrM8JU8MYlwp0iKKCaxA6UqrqNe47wcaONF/5BLhxD7/xXi8zED6fc1kQQyxpUlHDzTHyzBHZYPP3ebIrWBRSUh6XHIhHJTZu1T8MEhrWlUnQaAGkgLp3JTEIdeASwde+m8LRVauvMp5eVFPbROBurtyA7J8a63sHPP7xA2j9ra9hAUQSlsCZgKXfX6MylVIj6JWWLeyezNGuJbVyeEjrv0fikluhlr5bp1SZwKdYuwGlL6fYs9BoWMcnfN9fnESZUaFHQQcEMCHWF6sMJ4RB8aQhafJDq2Y389a1nMBKfWltDu9cIcw9+LPpQlKz1e,iv:pR195bOb/ty1YsHrIAEVjN1gG0ParqRaOVQBwvABDg0=,tag:dC9wyCrsSw+9ETMRboME+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NmIxK3JMbnRLZ09IWHB2
            cTVjSHhtY2ZsRWVSNlZrWTM5QVRCL3lDd1VNCjZGN0g5ai9NQkNGVlN6VjJ2M2gz
            RGRQNG4vNUZyZFhhdHJBOHpCUWtjN2MKLS0tIHhCS01WUU45c3o2TTROY1N0V1JX
            SVo1SDZ3R0hnc2phSytmckpMM1IvSFEKa/hkALBylaMDbajKYHHbXQQOfIC08WNB
            TWhqcyu2fe4gcnXUccvEZ82NuI1PJ74eBEnMnOihSY1ymG6zebFGnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T11:54:22Z"
    mac: ENC[AES256_GCM,data:3+/quhB4uZMJJumNgvLgqySTYMcrGcXohq9dBmiKnIMsRs3lo8Dzx2ha1hMRrj1U84+JC1D5LQ7T4Qv92BVf3aAXks+dCWy5BwGG7ZHFEwfiit7crVOvMbhP1UxzUHb+OSFY3gLt5SA5NkQ8Tlti5Bitca5zVRzuD/pcyYj/+Ns=,iv:08p+GLqRapEtoA7RxCnxE2pon2ricYltTCY6+An4iEY=,tag:4Bs2UlrpphqMyG66Nob9Xw==,type:str]
    version: 3.13.1
