apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: media
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:D2V0rE3VDFciKE5wXIsakkQslR25Ydx9KlE=,iv:FM92wnEHROxRCAN2wFePpTvHIIN7muuh9fSyeW8/8Zk=,tag:lIwlGtAtYMB568nYEX1Wfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYnhwbVZiVHYrWkFTTHFQ
            bzJpZmRNWVRoZnVMQ0x1dVdYZ3pvdWZJUW4wCnBEM0NKS1M1ZU50c2JZWkdQM3VV
            eHIzd2poS1ArYVJ3NDc1dVlQR2xoMFEKLS0tIFNNaDZiblZwSHJLVDhpRnkyMFhj
            ODJGOFROakdYOElvUDNRbGtLeTBzeTQKlnO1FFSXmb+EigwQarT6lHhYgc8LV6cy
            uiMnkzqNLI52hkfBqRBTSsJ2rgpJGdliZho/P5dPrmtUsWiMgSbYJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-15T03:31:40Z"
    mac: ENC[AES256_GCM,data:4wQzSiBxvm3J6yRdzpq9FzkwiTl76SQk5aU+Tifh/Hc+0W+JGe/AqDnujPBQ1nJwqGC/OQZEm6HCXXQPZ2Tfc80HYM0Wr46sKlGAouJ3JqnHY+xQN6iQbm6Du2hu8a2iZa3K/pBwK8t/FJ4SoUsR7M9FSWYGtIxj7tTJqxMyeHY=,iv:do8kjOgLsroXLuLZGLAz6hrsKNrQIfUWWBeWMX9d0ZM=,tag:anZtOFM1cbO/0JInQgT8jQ==,type:str]
    version: 3.13.1
