apiVersion: v1
kind: Service
metadata:
  name: plex-lb
  namespace: media
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: plex
    app.kubernetes.io/instance: plex
  ports:
    - name: http
      port: 32400
      targetPort: 32400
  loadBalancerIP: 192.168.100.202
