apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
type: Opaque
stringData:
    cloudflare-account-id: ENC[AES256_GCM,data:rZ71RyZmdOg8sGEb0zgqZPP9O2/EDa8EKAV2/IMR898=,iv:WWJ2ypuUa5LBCsz13MI3AWKvmmcjVe1d+6WFJB3kKcc=,tag:vNnun+NHfCXasjmCVBre1Q==,type:str]
    cloudflare-api-token: ENC[AES256_GCM,data:uoWHPncOYBVL3HK6RsXhMd/BE2v49S8E1fLM3OiYLufxk7vjEe0g9ZpBZXckd06mYy2phYc=,iv:NgzdMC+82CJXtzjNWQgjv8zdzzT9SYPlxcFl5Jv6x5Q=,tag:Mdk9k4ugu0j5or/JPkgR5Q==,type:str]
    cloudflare-tunnel-name: ENC[AES256_GCM,data:yB6IfzUE0LXoD7MqDlFQk58ycsMJfwkT3p16l3k=,iv:BI8WKivhLKGoP4qFyux3OhebvBP8y/nr8B1rJVxGUgM=,tag:1RjuuYS9N6AUkrrQFCAR2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNUJ3L2Z0UmZmUWJwUXQv
            UHNFQ21jVGVZaWRLNDFQcFR3a0ovRjQxNmpzCm9wM2FOYTFYL2VCaXQ3cmJwazhy
            Mi80cUR2VlZnMTF4S1F0U0dMbEJweFkKLS0tIDhBVm84SWJsb0xvYTBJby94cndR
            LzFxSHJOczBPMTFnQmpZekRydjd4WncKHKmTSGpM1OI002bF8bxBCw14hfUOf/vC
            AE4bzPfrgW94oi5kf/AfxwITIwmDxfopTU5lvTBfAOCJIRTSrpC8Xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-24T23:37:18Z"
    mac: ENC[AES256_GCM,data:cFlLBr8Ow0CScOShTd+bNSyI8hKnCNcgblsqSj7EN/F62YIC2FEkR+wmFKUxr+SSLKZQPnEqC9abnlNWk2YWJMnXZ8QitjVQqMb6xBiEk6IduvbUeOcVmLlLyyjmG+wK0pAgTmz2nxfWq6BBPE1Y8AN1DACB54Q9OsqYU8bVQHc=,iv:x6QpeO3sVQ0vXzbWuLi/DK44p8k3rIXtoC/WAcQuB/o=,tag:l0DTNqTUEUdCep4WCblmYQ==,type:str]
    version: 3.13.1
