apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare-tunnel
type: Opaque
stringData:
  cloudflare-account-id: ENC[AES256_GCM,data:4KsWwVYDuzFHf3EcVhlioYbJ6kwVtJvaKHgTmq5QEM4=,iv:EgSRVyqW26P5dyszhV5yjbchvT1sIxnz0dIzXUxc7ag=,tag:RKOU6d3bAxUw54ywdZlNsA==,type:str]
  cloudflare-api-token: ENC[AES256_GCM,data:WMO/vVcAluRWCa6dl/jtSSZrvHj0cDrx7ww91KkfmgvGFbiKNYZ246RYxpHldrRWLdiobck=,iv:8zikScs6CjqCO2O/q0yJf2ohIrnDTkF8na8hDwf/QRw=,tag:4c8P6eAkZcGUT/mGcfSjSQ==,type:str]
  cloudflare-tunnel-name: ENC[AES256_GCM,data:GunWePQZpwaKnhjtaR4p+YfB3fnsij4QE/sjvNo=,iv:NPauvVgc3kS6cKPya4Bug3ESLJz8UsKfNdO7smLDQYs=,tag:hQ7ArQ4Sllr9N4Xda7OUCg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZjY3TW4wY1JEWGxYeWFC
        NDVmYkp6LzkvQkhOdTdDSkZ2RisrbjkyekNFCkN5amhaMlI1aENmOGlBbk93dnRF
        ek8zUTAwbHlaYXdWbk4vYktsRU10TzAKLS0tIEx0eGV0UHRpWlBkb3NPSXN5b1Zl
        WnBUMWt4UE41TWlaakQzK3d6cFpDS1kKeQnVjR8wJE4nVHk2WKxfDDuOGLUeRWR0
        BaJP5EZ74pyQoyL+SQQoyWZVye7kZeU7zzh9XLY5ECL9sLcAahFWqw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
  encrypted_regex: ^(data|stringData|spec)$
  lastmodified: "2026-06-24T23:34:49Z"
  mac: ENC[AES256_GCM,data:wI6te138NEsSrPL87pRcrvGCzswIGC13oNmNpWDLzDC5YjMQPBSn3fsG0PrE530t0iMZ+d/bQ8oI4JSDwpkQs7+fvZOtzQbjE3hr0l9YVGloOpfP2sawmHNG7LU7hxsro6F6NzKXoON5GrF4VUVFuidt797trfcuwtuzcpJ31BA=,iv:y7Sf+KmL9CHXPau8Hoqch7euCPKA1m0ube9ZCojBurc=,tag:TOhEz3Of0pfhu2gmuD+Amw==,type:str]
  version: 3.13.1
