apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    cloudflare-account-id: ENC[AES256_GCM,data:yyj8cpAPWB4c5U0XTTRTe8n8/Scb9GwWVwpYGGUDk3E=,iv:mnyJVaxG31ADy3kO9DjmxjcdV0txRAxc7P9nf24m5n0=,tag:Zf0vM5j2rvGaeKux4inmnQ==,type:str]
    cloudflare-api-token: ENC[AES256_GCM,data:uy2/HF2COrHzYOQGjQhi/3XxxAeisC5qhHqau2OosmiRIk1arxg95CbyJnN2zVG52zzZCVc=,iv:wDbPIydrJ3+d/PYHDvIRiCCdr9gfyCLmiRsHPDYfgGM=,tag:GCEZ44Hmfh9PhE5VJ/BKOQ==,type:str]
    cloudflare-tunnel-name: ENC[AES256_GCM,data:guVrBkc6fzeme2V2RZPtrzQn2Q/7akan1HnuGZg=,iv:H7cu85OH7TJ+vC2v+1Xp260WlAjuOAnG4yECZVPfAZc=,tag:2K79bYKjIfmWDczfXlb2QA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdTgwU2s4aGpCTjZlWXpR
            SFIrYUhvejVrTVlkdmUvUUc5L1dLY2R4T2pBCm9mZFJVYy90SlBodVlHQW1ISDFi
            NUtkV2hDdHI0YzZucDdFTTJpTGRZS0kKLS0tIG9GLzUxa2MzSlltMkhBUkwraGhr
            cm04aDFXN2RWUlFQcXMyV0ZqRWVCT2cKX1aFOnhdTAuQ8jF5Fmqn28Wc2cn1UT0q
            CvptrlMsuMrPKy47YTZfG/aZT8gj7nv5xvPhjCyhG4CfEZ/G3kNdOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-24T23:42:37Z"
    mac: ENC[AES256_GCM,data:DyZt08w91oQ8BDs+rcjLdUlpdNk3jZ31yPAa5PnNLit8JvLbUqu3HNwhndYvO4e2fUWWm5CqeeOd2jSebIMpgoNzJOh9JvgASHgF7m2FhYmx3BpJJcm0tjMQacb5toPZw7KjaQtbBr9wkGw+12c/EqKnzS1PffO+asJZ05BESbg=,iv:cpZdFrV4afF5Yc/dtD5JpVCnsR9drSj3FwjfTako2+4=,tag:9HUxsjKOqfr1Ui/ChHB6GA==,type:str]
    version: 3.13.1
