apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-external-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: gluetun
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: gluetun
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-config-files
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: op-secret-store
    kind: ClusterSecretStore
  target:
    name: qbittorrent-config-files
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: qbittorrent-config-files
            items:
              - key: qBittorrent.conf
  dataFrom:
    - extract:
        key: qbittorrent
