apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent-vpn
spec:
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 1h
  chart:
    spec:
      chart: qbittorrent-vpn
      version: 0.7.4
      sourceRef:
        kind: HelmRepository
        name: qbittorrent-vpn
  values:
    strategy:
      type: Recreate
    qbittorrent:
      env:
        TZ: ${timezone}
        PUID: "1037"
        PGID: "100"
      config:
        bootstrap:
          enabled: true
          existingConfig:
            type: secret
            name: qbittorrent-config-files
            key: qBittorrent.conf
      persistence:
        data:
          enabled: true
          existingClaim: media
          mountPath: /media
      volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: qbittorrent-configs
          mountPath: /config/qBittorrent/categories.json
          subPath: categories.json
          readOnly: true


    gluetun:
      startupProbe:
        httpGet:
          path: /v1/openvpn/status
          port: 8000
        periodSeconds: 5
        failureThreshold: 60
      env:
        VPN_SERVICE_PROVIDER: protonvpn
        VPN_TYPE: wireguard
        SERVER_COUNTRIES: United States
        VPN_INTERFACE: wg0
        DOT: "off"
        DNS_KEEP_NAMESERVER: "on"
        DNS_UPSTREAM_RESOLVER_TYPE: doh
        DNS_UPSTREAM_RESOLVERS: cloudflare
        VPN_PORT_FORWARDING: "on"
        VPN_PORT_FORWARDING_PROVIDER: protonvpn
        SERVER_FEATURES: p2p
      envFrom:
        - secretRef:
            name: gluetun

    volumes:
      - name: tmp
        emptyDir: {}
      - name: qbittorrent-configs
        configMap:
          name: qbittorrent-config-files
