apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-config
    namespace: media
stringData:
    qBittorrent.conf: ENC[AES256_GCM,data:8xx1LBaMMhwzPYUMJDQWMtXwToS1Jaglgr1tIjPr65/ETvvLGAl4DCjqdXTmSLox24ro/64NziVkms0Jqp7Va605rPyXOn2e2zuKKrTYgzyi4nTAazutPUxoUfCJcmxWgKO2JIW/vy+Hqzkf71vMgNAOqk8KRXtNJfYiGW5r59fZ//APjB3mP/jBDJpWmeq7MW5WQ2CWy/dL8vdNy63I7NvxIH978E5K1imZCvafMuFbNLVhDN16ewjPKXfnNnRVR/qksTER4kmnRJQ0UqUMk/mvuwN1prqKW0rw9KAeotk6JiG/cpossMAigPCI/gV0Mn4UDEZAdZK4vv5VT9UyYy1RSjPoIIPi8Slq7390TJyxqlwaE+cKtyQW1GmXihK0eebga4cfSiA0xZs/r2bPO742YB2edBJNjP9Yf8G3ruMePkYua9S+qQa8v0qb+6J5U8QH3Uz4MDHCNi1Yj4RhiSssv0ek3txfGXQPPLCSCqPV,iv:LlwiGpy61zArGmF+nq20CWzypj9P+JJxSn7fIpBi4dY=,tag:aTQraFeXAYg9X6CCZAZJag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcVY1cnozbjNSeUJKUmxs
            NjBuS01YZFdlRC9QdFpxNnJDemd0M0krTUdFCmZEbXBqUVQxdGxzZ2ZUWHlZcm1T
            aWw1S3NOQ09aUGdpcGJNVGcxblNtSWcKLS0tIFhUVzNYRmp3REl6K2NxYVdpWUFR
            R2lHcWtrWkQwOFJoRDQ1cE1yNUc3UlEKAXsvXO6wgntNo/sPqpCbzNuuTqYoKV8p
            xMaEfnOxpbAc0gZlmxwzZ1z3G9dSeFv/zlLlCwz4A5bQPeSJ5ibDNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-01T02:34:18Z"
    mac: ENC[AES256_GCM,data:i5XblRQAep6ty34E59VkZ+6I8zuGrqfEcdg1RD7ipAsjlyOHOKmxWUSD9L5NyqsvPatcrlb5wd4kyiqsL6Emcu4W3sMfOj4mYkuGazvdACCWahfIX1YoNM57d7ojlp3ZUcP2gR7sApvIjH5cjbhTOlrfw/EZ9jg8pc9+2i8Tzak=,iv:H0uw+a3wibaKqbAY6TsUU1mLpMi0jBPykP1z+36u2rw=,tag:5GbARlJ3Lcw1VE+cBUv2hw==,type:str]
    version: 3.13.1
---
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcVY1cnozbjNSeUJKUmxs
            NjBuS01YZFdlRC9QdFpxNnJDemd0M0krTUdFCmZEbXBqUVQxdGxzZ2ZUWHlZcm1T
            aWw1S3NOQ09aUGdpcGJNVGcxblNtSWcKLS0tIFhUVzNYRmp3REl6K2NxYVdpWUFR
            R2lHcWtrWkQwOFJoRDQ1cE1yNUc3UlEKAXsvXO6wgntNo/sPqpCbzNuuTqYoKV8p
            xMaEfnOxpbAc0gZlmxwzZ1z3G9dSeFv/zlLlCwz4A5bQPeSJ5ibDNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-01T02:34:18Z"
    mac: ENC[AES256_GCM,data:i5XblRQAep6ty34E59VkZ+6I8zuGrqfEcdg1RD7ipAsjlyOHOKmxWUSD9L5NyqsvPatcrlb5wd4kyiqsL6Emcu4W3sMfOj4mYkuGazvdACCWahfIX1YoNM57d7ojlp3ZUcP2gR7sApvIjH5cjbhTOlrfw/EZ9jg8pc9+2i8Tzak=,iv:H0uw+a3wibaKqbAY6TsUU1mLpMi0jBPykP1z+36u2rw=,tag:5GbARlJ3Lcw1VE+cBUv2hw==,type:str]
    version: 3.13.1
