apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-config
stringData:
    qBittorrent.conf: ENC[AES256_GCM,data:IPBDOx8Gkrq6iA1XByBCvUNMzrz7zK6vRHrVf8ZTBKXSP0eQF11YjoNcXp6tg9MHmMvLqH88Bk2EiJDIlm55LOLh3iF1ZTALAeP7kSKszMU2+9MnslGlop84GxsnusKuLiSvhHLdbnXvA/hvxK6E68h10dBi8anXqYKI7FrjtGh1XMm5YNzTMa7o3TmCwAGG5Pm1OEjI8fyv8gFV83JiyGPuR4523Asphg9IoTCxM0BJvQAjcMVh4sI/DRCGExL5nXJ0ZMsWj7o5rUZjdrxO8SGo9P3+qBPXXVjLw2rOMh2C9Gauoy3ZwKg5oxG7NmV2XKRp3poPQCLDy0JYx9xedwY/ykLhbCHgUVYtPYE8UA1A+jpjKylr3N++3lNIA29AM6FpeWziuB/7XGZH4p19Wp4DMZrR0523S8/5saJdRI2DQaGCdApLkRVeVy8UFERvsqEH2sHbq2ahC/RaSSfOLjBOIeXACGMwWIqZk2Kl/oFp,iv:LtcKltR88deoKvdbnN62+/gE+MBPBPSvCJ6eZoclIDA=,tag:pO/3hyOvesZX+BAdSyQ9hA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYmJWSzlKanJTaEplQlBD
            OVhZc2JyV2wxRENZcU5nUkY2SmVMVjZKQVJBCkgxY0YveENmV3NRaEZuZjQ0MzJm
            SDZ2dGlFQW1sZjZhYm9ZaFd3QS9xZmsKLS0tIHlBT3N0R3RHdlZmeElGSjVXZTc4
            aDlmN0RqZDhBQlhlRUprb1puUU85Q2MKmVasHO5IY5jAhLPt8S2cq2c0Cd+EONry
            NDqTAAL96kziFDpdjU5FGLIstt6dx6qeTH6iTpAVjeDTI6r8wkwFTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-17T00:15:48Z"
    mac: ENC[AES256_GCM,data:O4hfjynENFdcD/mWvuJyXIf4BKS+N21ttuSDGJA2Y8P+gfhTF7O+qhd3HMaAL+Nk/0OJnfKn3MiIWHRQjJExc/LAvXN3nzqxKwpq2ALWofn681tlHKncTfL5eCRtyRECRKwatqBv0MrkSSNFYEZyn7mMSBOJYPWAsSyFXrVWdhw=,iv:zbX0BU12NiwAGA0tj0BHWAAeQPoM8DPp/knWRDhoE2Q=,tag:1vCv6ppGiNG82ou2DulA0A==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-env
stringData:
    TZ: ENC[AES256_GCM,data:WQZcApMeyuyai5fKr08=,iv:F1aNJ/xvOJ5YyQHXiF3HbuC2ylf7v6A99jNMR/t+/zs=,tag:GA9wciEbeHCHUlT8+3mktw==,type:str]
    PUID: ENC[AES256_GCM,data:M5MH+A==,iv:ClCFZZw/0v6oyQFhgTGf7asDJgc2Gcd4JpJmXsMTogk=,tag:OX0SbfHcCO+dUmdlKZpWdw==,type:str]
    PGID: ENC[AES256_GCM,data:yN0emQ==,iv:LPgP2JmqaD/YH0wg+CAtmDy4+1ZkOu+CgmgBzxX5CrE=,tag:lUitWdgX5aoe68aRsgUy9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYmJWSzlKanJTaEplQlBD
            OVhZc2JyV2wxRENZcU5nUkY2SmVMVjZKQVJBCkgxY0YveENmV3NRaEZuZjQ0MzJm
            SDZ2dGlFQW1sZjZhYm9ZaFd3QS9xZmsKLS0tIHlBT3N0R3RHdlZmeElGSjVXZTc4
            aDlmN0RqZDhBQlhlRUprb1puUU85Q2MKmVasHO5IY5jAhLPt8S2cq2c0Cd+EONry
            NDqTAAL96kziFDpdjU5FGLIstt6dx6qeTH6iTpAVjeDTI6r8wkwFTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-17T00:15:48Z"
    mac: ENC[AES256_GCM,data:O4hfjynENFdcD/mWvuJyXIf4BKS+N21ttuSDGJA2Y8P+gfhTF7O+qhd3HMaAL+Nk/0OJnfKn3MiIWHRQjJExc/LAvXN3nzqxKwpq2ALWofn681tlHKncTfL5eCRtyRECRKwatqBv0MrkSSNFYEZyn7mMSBOJYPWAsSyFXrVWdhw=,iv:zbX0BU12NiwAGA0tj0BHWAAeQPoM8DPp/knWRDhoE2Q=,tag:1vCv6ppGiNG82ou2DulA0A==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun-env
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:AYCF7dCAcKor,iv:HVpPJwhU6c/ifuCbFH1V124G6B3ZS5L9UrWa5iko4mY=,tag:Pp3wTr3uRbHxenRzRV1xMQ==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:G92bZD3LMasV,iv:u8De2adiDSGIMYyHCJ8WM1KJg2Pt8aLYpfn/sGKteUI=,tag:b9bckjEG91hv3L/b+IqBZQ==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:C7c638Jmm4GkpG0PPA==,iv:Jx0ZwbMhzMYdJu46rF8kg+guT3/JJThlQpmDzyyukaQ=,tag:WMF+dFJY1n7mj/18SXgwNw==,type:str]
    VPN_INTERFACE: ENC[AES256_GCM,data:MjQf,iv:QQABNyWdi0aL9tVExDoyTSYNZk8HMYSo8kw8KnjOr7g=,tag:FtmLEcJ7B1IwYZ+r/bREtw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Zchh0juyMpmcC+k4oFbIRse5mF7BCzPWkcZAtmgfTw==,iv:wOGSoY1LzhhggmNW9heK1WQGfYy52tiRTJxIPB+Bunw=,tag:pFxpnmBndr2oLHcpCHNNnw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:E2NU/4ktt7dNbGFaM1FDXisUVOnfR+CjXSpKjdEBW+VdshmiAhaDx6gWZIs=,iv:EEROJFfmXq9SllQwtsg8xHLj5/6FP2S64FbAQbFqKOY=,tag:3wgxb/VdLRWmDVWDPUW3ig==,type:str]
    DOT: ENC[AES256_GCM,data:dFyw,iv:m141PoZZ9FlV7jAedVkEuaTda9CK1wN4S+Tdzds6INE=,tag:7zhVTJUTGuRrHgbr3Vg0KA==,type:str]
    DNS_KEEP_NAMESERVER: ENC[AES256_GCM,data:vVo=,iv:i1KEbIxztNvhRdWSJoSrs/Wkx+EA2PIw8ePfIF7TlSw=,tag:FiOU2AFUADzwUOx5N0calg==,type:str]
    DNS_UPSTREAM_RESOLVER_TYPE: ENC[AES256_GCM,data:ryXe,iv:SlNGjU3WSDIO2782aF0xGA7EF55WQgrCXHjhlz+CzL8=,tag:4bscmlgCOnkLxHmjUAkOeA==,type:str]
    DNS_UPSTREAM_RESOLVERS: ENC[AES256_GCM,data:3SuVAuliVuhMdQ==,iv:qOqCNh2r9GONPkirES6shu4wR3V47AI/GYqQcvtJex0=,tag:cLjDdrCN5JFLIxgUfbpqTw==,type:str]
    FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:eoSzNJ8gOx5ZQFUeIiIo7a6jZPQPVJzD1Q==,iv:9RZv85w9Y63Sdd2z6Q2Bcu2GtOKVgqNX3o+Yztd0dBc=,tag:XR0+4nbAJoy/GMAegVxZAA==,type:str]
    VPN_PORT_FORWARDING: ENC[AES256_GCM,data:vFc=,iv:h4/KGpXnZemdpSRv70tD5M6nL1tC3univGplitE9ZHA=,tag:Ya5EnCrTH5QvD71xFnorIg==,type:str]
    VPN_PORT_FORWARDING_PROVIDER: ENC[AES256_GCM,data:deNAHTHO0xZE,iv:kR8hkLawxVFcEe6Jp6Q7GGzzIrjzDN69u+HNbp2z9eQ=,tag:WXNhbN28xmsJMYOEZ17kMQ==,type:str]
    SERVER_FEATURES: ENC[AES256_GCM,data:Wpwy,iv:j8ju8FLVQ3CVf8eMchmwtsOMK4ZYmRINUCyZKYi+j3E=,tag:WUTnG7USlDQ+PnR/EhASCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYmJWSzlKanJTaEplQlBD
            OVhZc2JyV2wxRENZcU5nUkY2SmVMVjZKQVJBCkgxY0YveENmV3NRaEZuZjQ0MzJm
            SDZ2dGlFQW1sZjZhYm9ZaFd3QS9xZmsKLS0tIHlBT3N0R3RHdlZmeElGSjVXZTc4
            aDlmN0RqZDhBQlhlRUprb1puUU85Q2MKmVasHO5IY5jAhLPt8S2cq2c0Cd+EONry
            NDqTAAL96kziFDpdjU5FGLIstt6dx6qeTH6iTpAVjeDTI6r8wkwFTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-17T00:15:48Z"
    mac: ENC[AES256_GCM,data:O4hfjynENFdcD/mWvuJyXIf4BKS+N21ttuSDGJA2Y8P+gfhTF7O+qhd3HMaAL+Nk/0OJnfKn3MiIWHRQjJExc/LAvXN3nzqxKwpq2ALWofn681tlHKncTfL5eCRtyRECRKwatqBv0MrkSSNFYEZyn7mMSBOJYPWAsSyFXrVWdhw=,iv:zbX0BU12NiwAGA0tj0BHWAAeQPoM8DPp/knWRDhoE2Q=,tag:1vCv6ppGiNG82ou2DulA0A==,type:str]
    version: 3.13.1
