apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-config
    namespace: media
stringData:
    qBittorrent.conf: ENC[AES256_GCM,data:DGhJxN4H4KWJ0bZwakysfxhDWKInTmMMh8sAMjDPHBAz4wyU+YPIy5q9NlyxeCLsaXnY/rIPuB5bBrRiaFzPYwITOkR+8dsFAdoaMHrXY8hlFy4ZjKK2KI1IlMwcrRzF+LDhX7/uYO30SFrApDza0IkgYpE8qHRRD22bxSGLwrtW6CDmfYeqtLttZpjn7uLn0BNjBWLRHE4PnsTpr+FTJEtkgiJ6IWHG0q1AMp4BvemFtAcm9OHnav5LQnFUYVGf0d+TpaiVw6IiUr1DgL0l92gtlFjdBGriwgMHN2O7cieUx8sGhzTz3Sop2h8Ey4+SkEPEYIgAypegPrBEdMVW6I5bJhye8rvTH+SRtp0K8S9MoknrX8zVaZjoNuWaICRKWoPKC5F+21t63HDdpYzKWqgfexJ6BxecWuoGBA11WqCTqJ8LTx9aWPV8SaiY63ifIpoxzDlfn76vLPWo011VFfePJJ1ORD1PgRl0uH4rpnRY,iv:KXgMjsVTuytnS+PpJmVeeMIRYtrt45y0Pycyc87QmvQ=,tag:U5aMqWtDOqUrzhlK8Ga/gA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQmhNZWJFTC9PejVvT2hI
            VGhNVlVKVFJlT0RFamorS0tCU3JNcVZObnc4CmI2Yk1sRzhrdWQvRVM5ZWZGVTdL
            OXVoYmxIbFhRMExvUFlwSTlzanlISDAKLS0tIENDMzdPUS9MRGFxS1UzVHFBa3Ux
            MUlaNkpRMHg5QlN2VnVFdU5FUnNaNGcKJPqVdmyGzNvf1FKh5QTEnOdpdcfW0zBJ
            bVgdtxOrD93obQ+g+fjgkNRI+WUUrL26mf3zZ/uFkhWcwDa3DaBBcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-02T00:28:53Z"
    mac: ENC[AES256_GCM,data:VnWCHz0nu6bxD/UhCD5H4j2g351bjc3yAxa5S/BfX7djfZuFdCeI4zwnpHMcdxAST9RKVi9WVs7sd0pWBH+c4AsIO5oNeAx22xJuizikjRX1XSBzXTLXz2Cj7tnorKgLhrCMGIcIUGnnMyeeo0Th1X+12b2SPmUV6Cm72XV4MX4=,iv:NVRq08EV8zHJYa9/6cHYVr33+IXgKzFCWd4BN1KfOS0=,tag:T+4H8F0r2MiKsZXYMStaJA==,type:str]
    version: 3.13.1
