apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: configarr-sonarr-external-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: configarr-sonarr
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: sonarr
  refreshInterval: 6h
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: configarr-radarr-external-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: configarr-radarr
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: radarr
  refreshInterval: 6h
