apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-proxy-auth-external-secret
  namespace: gh-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: gh-proxy-auth
    creationPolicy: Owner
  data:
    - secretKey: users
      remoteRef:
        key: gh-proxy/htpasswd
  refreshInterval: 6h
