apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gh-proxy
spec:
  chartRef:
    kind: OCIRepository
    name: bjw-s-labs
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      gh-proxy:
        containers:
          app:
            image:
              repository: hunsh/gh-proxy-py
              tag: latest
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        ports:
          http:
            port: 80
    ingress:
      app:
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: gh-proxy-gh-proxy-auth@kubernetescrd
        hosts:
          - host: resources.${hidden_domain}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
