apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: kube-prometheus-stack-credentials
  data:
    - secretKey: username
      remoteRef:
        key: monitoring/username
    - secretKey: password
      remoteRef:
        key: monitoring/password
