apiVersion: resources.teleport.dev/v3
kind: TeleportGithubConnector
metadata:
    name: github
    namespace: teleport
spec:
    display: ENC[AES256_GCM,data:CThBTsXm,iv:b9qY2zkb9U6a/oRQI7tpjYy3ZNZ4Hparq5FN9kCtGmc=,tag:OyHdyi5QEKfSIBSD/8HpPQ==,type:str]
    client_id: ENC[AES256_GCM,data:rrvEeecKnj2D/15nkTuwDwvwxhs=,iv:HVS6sE8evDRNYb5hxcleYy1mlbR/ps74Z/KCmGBKThE=,tag:Y7VYku9qffb0bLJiBUzJmQ==,type:str]
    client_secret: ENC[AES256_GCM,data:fyuOe6rntEghg3yRTC0+BXtsfcCTN/OrSoQaGsSnm+1KIKjsm1PfSQ==,iv:8XwmSgx3lKwxNEoX/nV7YUVUVTthg3fbZ6f0TgFFvTw=,tag:2D3rUTDOSyUUDqOKWQtuMQ==,type:str]
    redirect_url: ENC[AES256_GCM,data:21sIRDXVy19mmXVOPpQve1UWUcMaUfXOFm2IueRKk6P+jJLfQNgasT/ggSKSpr4MJ+dhOoEso71986kT,iv:Tn6VXT7AVMuycvajEvFRqBTb2XT13PE1Af4HuEMZIM8=,tag:5okEEBpe0Xlz2h0DBqfHnQ==,type:str]
    teams_to_roles:
        - organization: ENC[AES256_GCM,data:kFb/Tu/4hg8gxItCYfh/Jutiq3huDuQLEZg=,iv:juKiS+TVb1cVB3H0PC4FYctefK0WkYNhKVo9VS91G4E=,tag:W3ze/Q/84JtsTRapPnq6rQ==,type:str]
          team: ENC[AES256_GCM,data:532V6s0edxGUf6e0pfMJ,iv:sjwqNDGW5W7IjoyuOIX3UNP/hlyO8ZAxMDpESVl33c4=,tag:7pjgmKgjKW33Dxkh6ceq7Q==,type:str]
          roles:
            - ENC[AES256_GCM,data:ac/Hz1cr,iv:+GNxFWbKc4TxcKc4jQtgT2HHERPFBb92f3Ms/AZ2Tq8=,tag:LTK7TYb48AdS3q8J3JGrcw==,type:str]
            - ENC[AES256_GCM,data:YJKMfhFE,iv:uPAZaaFGRUQrk5X1RjbIupRsSzj9+hWGmHtPnHQPjo0=,tag:+uFid0EMXAGmypeeSZPjAw==,type:str]
            - ENC[AES256_GCM,data:9Je4qE7Pq5C7,iv:UpjR8CWVqYxikziaqyCj36QPmdez7BmSkkgSldCIv4c=,tag:BUtmxaKvC9qYZg6O950i6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Uks3d1BaZ2ppcnhQVStB
            UXN0dUZQTytqUkdGQnRINEFiZm5FTWZGMUVNCmE1SFlhUnBPVjdtZWZXV1NaanU2
            TlNORzRuN2wzcEVySlVXTVBLT0lGd0EKLS0tIEJ6ZzBLQ1B0cmJ3Zm5keE1rcUxL
            WmN4QjhLM3I5bUNxeVZIcFlhV2NlME0KEr9tRyHJztne5J2knwYHFlFLDin5b7/K
            dicrryRMXWTCI3DtCc/o5iyrsvAZ89ITpJla63qn7Z/lW8ykcBLu4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-08-16T01:46:38Z"
    mac: ENC[AES256_GCM,data:Ks/SuEDQEJpBsTFAknWcCfhEtMCmRDTfCr4sLCsAh44L8O2wstCClWapCR9BEnfxpZmZ94FRlULx9hsdIzaGpY7CgpNFc9oawfgwY6527itXOfjEtEhrDoZ6y1LAE3fMjop/9MMpDLGhTWt04Fg6dk+S/YhVgL9dTDTVY9peqgQ=,iv:s+jimR2QR8v/tSY0tjcrBOmvYany3zt2rN3M7tXTsts=,tag:QK+wrFSW3WCQbG71Z7NJrw==,type:str]
    version: 3.13.3
