apiVersion: v1
kind: Secret
metadata:
    name: neko-secrets
type: Opaque
stringData:
    NEKO_MEMBER_MULTIUSER_USER_PASSWORD: ENC[AES256_GCM,data:t1MkTg==,iv:uqf8aXwb+cbQvleHYQKClOA2+QYWZqNUicmUeH+btKs=,tag:/+fSCuj+jEgd0KJrxzde+w==,type:str]
    NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: ENC[AES256_GCM,data:O83pTtxU/+lfMK8kpmIVXliAGljW+bZRSmXOmbgLikqWnl47oFQBVGwf,iv:D0590Ar/7nOeDdW3BvzhAaR8Jgtxres4A3zoEXWafMw=,tag:3lEw7SHmggyaxW364duUKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUWoxSGhVL3MwNko2QUlT
            c2R6ck0zbVlnS0E5cWtRN29GN0ROYjRHRHpzCkNyMFlLZXpQZXMwR0wrU0RVc3dm
            eHpyMWZNcGVwWFJNYzNQQU93elBmOU0KLS0tIE9NS3FETmd1TnpXSXpmL1RUSjQ4
            YkZObXM5Lzl6cXIwRDBYejl5YXoxZEUKTTwrU36QUI33QCosiae+WHv/4viLE6z6
            /RoRbeoCJlSoBdFoRFyyd7AT9pnD6tupJYUVg85MuvdxVwuhaZpScw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-11T03:57:43Z"
    mac: ENC[AES256_GCM,data:yx49juNvyxE9vsCKYLcdxumRbNfVOG+feckejCPyjbzg2quG/qHTsj/CjIAg6GSUL1sNjtNZAKtdKSTO4DHyL0ogGkIGmMN6+D7yy7b4a0CiOLXijLsJUqZi0fiGZdZGiPQxVL31NHqXuUl/qVRs+gCflCjRG23sSy9Q46FCESI=,iv:HCV7+QAXCmxerFSgU4ibM1HsQhKcejhwZ/LNSuk4htU=,tag:fzxwi9oFWN/1ZoygVekJ6w==,type:str]
    version: 3.13.1
