apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: atlas-schema
  namespace: atlas-system
spec:
  credentials:
    scheme: postgres
    host: data-cluster-rw.cloudnative-pg.svc.cluster.local
    user: test # or use usernameFrom if supported
    passwordFrom:
      secretKeyRef:
        name: data-db-secret
        key: password
    database: test
    port: 5432
    parameters:
      sslmode: disable
  schema:
    sql: |
      create table t1 (
        id int,
        test_col varchar(256)
      );
