apiVersion: v1
kind: Secret
metadata:
    name: test-credentials
    namespace: atlas
stringData:
    username: ENC[AES256_GCM,data:Kk6O9A==,iv:7gU0TNYXEp0nKjeB8Ck/HhgyQAQuJ0q3PeJjQlM1ClY=,tag:fapTQVXa9o3ZzgyzKZUJEw==,type:str]
    password: ENC[AES256_GCM,data:DYPTP9UMGfjDTR58S9ZOxsZ7up4KNmlPJJIF5xPxo8ljL5AezL8W2HkyK4YYTXE=,iv:SgIrfTr/92wuHwHNvKTw2rNyEOYfP2RzHdB+DyPGL9k=,tag:1zkHRwgaDsCFrTB6km6gAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZjhLdmx1YlJZWHhONjkv
            U3VqdGNyV25DQVRFN1lhUzNFNnRabFRIZjJjClNmKzJydU0rdmgwMWcrUkwvRk5N
            OEFaclp3MFNuaGhucFY4SU5YaWhHdVkKLS0tIHJaRk45cFBPdlhnUmJyRGwwMUxT
            cEtCdjVrWndDcDhwUDF3eFdLTk9SelUKI/0QeeoQfHwKzJn7wBgmtMn6qpye84WW
            AatY7xP4rUkWc44LK+81rdJaQT4VbETyLAso/GZS3KhJr/6foSrNKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-20T01:54:07Z"
    mac: ENC[AES256_GCM,data:0t+WA1usW2ZvZz20tACT6kIyuDfNCIaRTUmxTLE5cg6V0Yuzbsn4/k0QNFIYaVORPRHH8g1aLRU/hp8if6TX0intpH6R+ErG9WVM25dP9FwfLd83ltvDX+3IaTpV3Kh7+tgd3xi9YAcc6pAbkHAGXfU/7C3FPHDZgdmTnrs8bJY=,iv:VbvH6gCf/mD8WaqUiErkq4QDZs7c/wvJTsrnWvJvs4Q=,tag:XTmYcB+ofiFHZbhgha90RQ==,type:str]
    version: 3.13.1
