- Network:
    - Traefik:
        href: https://traefik.thewhitelodge.org/dashboard/
        icon: traefik
        target: _blank
        namespace: traefik
        app: traefik

- Media:
    - Plex: &media_defaults
        target: _blank
        namespace: media
        icon: plex
        href: https://plex.thewhitelodge.org
        app: plex
    - Sonarr:
        !!merge <<: *media_defaults
        icon: sonarr
        href: https://sonarr.thewhitelodge.org
        app: sonarr
    - Radarr:
        !!merge <<: *media_defaults
        icon: radarr
        href: https://radarr.thewhitelodge.org
        app: radarr
    - Overseerr:
        !!merge <<: *media_defaults
        icon: overseerr
        href: https://overseerr.thewhitelodge.org
        app: overseerr
    - Bazarr:
        !!merge <<: *media_defaults
        icon: bazarr
        href: https://bazarr.thewhitelodge.org
        app: bazarr
    - Cleanuparr:
        !!merge <<: *media_defaults
        icon: cleanuperr
        href: https://cleanuparr.thewhitelodge.org
        app: cleanuparr
    - Huntarr:
        !!merge <<: *media_defaults
        icon: huntarr
        href: https://huntarr.thewhitelodge.org
        app: huntarr
    - Lidarr:
        !!merge <<: *media_defaults
        icon: lidarr
        href: https://lidarr.thewhitelodge.org
        app: lidarr
    - Maintainerr:
        !!merge <<: *media_defaults
        icon: maintainerr
        href: https://maintainerr.thewhitelodge.org
        app: maintainerr
    - Prowlarr:
        !!merge <<: *media_defaults
        icon: prowlarr
        href: https://prowlarr.thewhitelodge.org
        app: prowlarr
    - qBittorrent:
        !!merge <<: *media_defaults
        icon: qbittorrent
        href: https://torrent.thewhitelodge.org
        app: qbittorrent
    - Tdarr:
        !!merge <<: *media_defaults
        icon: tdarr
        href: https://tdarr.thewhitelodge.org
        app: tdarr
    - Wizarr:
        !!merge <<: *media_defaults
        icon: wizarr
        href: https://wizarr.thewhitelodge.org
        app: wizarr
    - Audiobookshelf:
        !!merge <<: *media_defaults
        icon: audiobookshelf
        href: https://audiobookshelf.thewhitelodge.org
        app: audiobookshelf
    - Autobrr:
        !!merge <<: *media_defaults
        icon: autobrr
        href: https://autobrr.thewhitelodge.org
        app: autobrr
    - Readarr:
        !!merge <<: *media_defaults
        icon: readarr
        href: https://readarr.thewhitelodge.org
        app: readarr

- Requests:
    - Sonarr:
        href: https://sonarr.thewhitelodge.org
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: "3691aeb2af194dc49c5c0bdf3f3c2b6f"
    - Radarr:
        href: https://radarr.thewhitelodge.org
        widget:
          type: radarr
          url: http://radarr:7878
          key: "54b95e46541b48958655464cb04f6c1a"
    - SABnzbd:
        href: https://sabnzbd.thewhitelodge.org
        widget:
          type: sabnzbd
          url: http://sabnzbd:8080
          key: "2ed6202e6fc04cc7a0afd1307834bf61"
    - qBittorrent:
        href: https://torrent.thewhitelodge.org
        widget:
          type: qbittorrent
          url: http://192.168.1.26:8080
          username: qbittorrent
          password: Perm3-Esteemed5-Gigabyte8-Bauble6-Unfocused0
          enableLeechProgress: true
          enableLeechSize: true
    - Zammad:
        href: https://zammad.thewhitelodge.org
        icon: zammad
        target: _blank
        namespace: zammad
        app: zammad-railserver

- Data Lakehouse:
    - Airbyte: &lakehouse_defaults
        target: _blank
        namespace: data
        icon: airbyte
        href: https://airbyte.thewhitelodge.org
        app: airbyte
    - Jupyterlab:
        !!merge <<: *lakehouse_defaults
        icon: jupyter
        href: https://jupyter.thewhitelodge.org
        app: jupyterlab
    - pgAdmin4:
        !!merge <<: *lakehouse_defaults
        icon: pgadmin
        href: https://pgadmin4.thewhitelodge.org
        app: pgadmin4
    - RustFS:
        !!merge <<: *lakehouse_defaults
        icon: rustfs
        href: https://rustfs.thewhitelodge.org
        app: rustfs-server

- My Calendar Group:
    - Family:
    - Calendar:
        widget:
          type: calendar
          view: monthly
          integrations:
            - type: sonarr
              service_group: Requests
              service_name: Sonarr
            - type: radarr
              service_group: Requests
              service_name: Radarr
            - type: ical
              name: Google Calendar
              url: "https://calendar.google.com/calendar/ical/6j2kv9b45jg5afaapdcd5deenc%40group.calendar.google.com/private-c8c466b1dfe46f7fdd1ae2fb6c31286d/basic.ics"
              color: zinc
              params:
                showName: true

- Services:
    - Mealie: &services_defaults
        target: _blank
        namespace: mealie
        icon: mealie
        href: https://mealie.thewhitelodge.org
        app: mealie
    - Immich:
        !!merge <<: *services_defaults
        icon: immich
        namespace: immich
        href: https://immich.thewhitelodge.org
        app: immich_server
    - Nextcloud:
        !!merge <<: *services_defaults
        icon: nextcloud
        namespace: nextcloud
        href: https://nextcloud.thewhitelodge.org
        app: nextcloud
    - HomeAssistant:
        icon: home-assistant.png
        href: https://homeassistant.thewhitelodge.org/
        description: Home automation
        proxmoxNode: proxmox
        proxmoxVMID: 101
    - Pihole:
        icon: pi-hole.png
        href: https://pihole.thewhitelodge.org/admin
        proxmoxNode: proxmox
        proxmoxVMID: 103
        proxmoxType: lxc
    - Semaphore:
        icon: semaphore.png
        href: https://semaphore.thewhitelodge.org/
        proxmoxNode: proxmox
        proxmoxVMID: 105
        proxmoxType: lxc
    - RustDesk:
        icon: rustdesk.png
        href: https://rustdesk.thewhitelodge.org/
        proxmoxNode: proxmox
        proxmoxVMID: 110
        proxmoxType: lxc
    - Netbox:
        icon: netbox.png
        href: https://netbox.thewhitelodge.org/
        proxmoxNode: proxmox
        proxmoxVMID: 113
        proxmoxType: lxc
    - Proxmox Backup Server:
        icon: proxmox.png
        href: https://pbs.thewhitelodge.org/
        proxmoxNode: proxmox
        proxmoxVMID: 106
    - FreeIPA:
        icon: freeipa.png
        href: https://ipa.thewhitelodge.org/
        proxmoxNode: proxmox
        proxmoxVMID: 109
    - Jupyterlab:
        !!merge <<: *services_defaults
        icon: jupyter
        namespace: default
        href: https://jupyterlab.thewhitelodge.org
        app: jupyterlab
    - pgAdmin4:
        !!merge <<: *services_defaults
        icon: pgadmin
        namespace: default
        href: https://pgadmin4.thewhitelodge.org
        app: pgadmin4
