apiVersion: v1
kind: Service
metadata:
  name: cockpit
  namespace: cockpit
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cockpit
  namespace: cockpit
subsets:
  - addresses:
      - ip: 152.53.52.163
    ports:
      - port: 9090
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cockpit
  namespace: cockpit
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`cockpit.${cluster_domain}`)
      kind: Rule
      services:
        - name: cockpit
          port: 9090
