apiVersion: v1
kind: Secret
metadata:
    name: dbgate-cloudnative-pg-secret
    namespace: data
stringData:
    username: ENC[AES256_GCM,data:lfr9Nc1C,iv:/9MRVF0ab8SJB0OIFeoI2lXIxYs6Kt7vzWjbyE4x9yY=,tag:K/+dKVNOzBXB42kf4Bi3Sg==,type:str]
    password: ENC[AES256_GCM,data:dkfOPPZB5Qcj/rsEBJKOAZLgazfQkhlK+W9C1pNqYP1P6H3ilrT0KXHHU+6r9NPhI/F6,iv:ek3VbWhSFjwNi9q/l5xQ1VO/HSvRSa3MM7kq0AJw5R0=,tag:skFIrYcu/xu4eFwrSpz4/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRks0NGtEU3VCeEYxOU9K
            SElmWFd4TnZLbGVLK2g2NDgreWNtd2VuOEJzCnZpSkp3UnUxNEttRGRaTkFUOW1B
            ZjVkejlIUWlzNDdRc0Q2Wms1Z2VuRncKLS0tIGtnYzVHOThvOXpBcHA5aFhjbUJ1
            djg4ZDhUb3hNSGJUWEkyOXpYYVZYQncKjlmsz+ZlesGfrr8JM/kNz9eYROSJCg2D
            kdb1qrU3lkLjv5EWsExO/GMdjX+VP061FNRb0BEfmhWeRdHHGYxtTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-09T02:57:16Z"
    mac: ENC[AES256_GCM,data:qcTSKDbxYaEXVZPssMDHQ/jJHLDoNURY0Y+bNSezT7yiuiMOL618FdQtHVJPymYWkzHhgDsbn7NpUdltRVBBIAG1IPPlN6wKZErTP6P0fL6SceL1/gnrYgR1vrDsIGUUKC9ofq1fio1nvaM1yG4U2i777mu05IpXy50TZHCf7Yw=,iv:10DIK5wJLa9tTAO8zxdZyvm3da6DbkU8cBHkiT3uv8w=,tag:ge0+cWwWRhz6Ox9UnSF6Dg==,type:str]
    version: 3.13.2
