apiVersion: v1
kind: Secret
metadata:
    name: dbgate-cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:YleQpKab,iv:H6nLQwbfenVfE7KbPJxhTIsd74ZfytcuJY2c9WEuSLo=,tag:0bC49M3dMskGoToH7LW3TA==,type:str]
    password: ENC[AES256_GCM,data:OVotrRDTADgQxF8atOA3Jd8ktNXZMecHaRy69s4+99/zctlyG664W+4sQorEvJqdQDdV,iv:109MzMt0LrqJjknh7rlcy5EknDSF6kHPGCDdxQ+GcZQ=,tag:7wnzQGaHXZjSrw1E+hJiuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNXJ1RkNKaXBINzBJQ3Jo
            NEMxV0M3QklMUFdoVm1YNGZpdE00NUhTNXhRCmF6U0hRUUF1RWtERGFXSnFxcWE2
            Y1JJblpsZVo5eUVmWkM5Y0xoOVptVlUKLS0tIFdzYUN6c0dFVmkxdFNsTWZUdDhz
            TERBQlB1b29ObGpRRzJFT3lDKzBIdkUKFNFnsSylDu3StrN4tYaXbgwS5K2n7MIy
            T6Uk5j0us79kqj32RJHhwmSmWOaJ4meR3cEtDn86vXA1akRXaS2ByQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T18:44:59Z"
    mac: ENC[AES256_GCM,data:DsM02jQc4fCsGq5ItEjdIoCAEoYbDf+F7vuDYjI7q/poG1Xn3TTnlJtK17JjS8LiNcfl/dV23SP4vFmqTr95QyGTIkoEoYrECF0NSWd+VFGZY6Ldo7nwlv1XOJzc2hjvvv8ZWB+L2ndV43lbnPYimbY9pG00a8E9eli1GGoaUew=,iv:bPMbiL8o8sNDTRpXER0VgWR840c1aSqtuAOmhqTiy/k=,tag:BHFGSarTnYhkSw6wf86OOQ==,type:str]
    version: 3.13.1
