apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
    namespace: media
stringData:
    LIDARR__AUTH__APIKEY: ENC[AES256_GCM,data:CsjFuWhyiZH4w30XA7zkIg3pP0hfwdUVmqdo76uT8AQ=,iv:INeeeDQhqSdtfk1qW5yYcp5o4Y2kBKMixxbeSUQWkno=,tag:uci6DFEgs4sqUqonnOIhbg==,type:str]
    LIDARR__POSTGRES__USER: ENC[AES256_GCM,data:ndXkBfXE,iv:jqfx3qbyBZnRx0Rshx3RQaA+7vubAJcAGfk3xBHCAg4=,tag:Di1wK8U9duMMjBO1B3VH0Q==,type:str]
    LIDARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:WFj6ueGXJPsvV4qeasavqpM19adC1PiE66ofJeJSFcX2cotdw5XaUP0=,iv:WMukdL6YDqt/jMvN/GAuRVztHf9hF37e+u3UMRGGtn4=,tag:kOlf18CNY02flP2t+1vgHg==,type:str]
    LIDARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:k8uuHZAy,iv:3k6CjlhQCOEr/Ida2AqBwTm0sAM5qGvvk/qz2uw/VHk=,tag:sX2Kldxk/PZ8o3+/ZoE/dQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZXQzUk9NRnFRQWN2VW9i
            RjJVejlSaDMvQlhmMFgwK05aMS9qb1lzMnpBCm0vS3NKcnNIb0RxdWg2VkJtZ0pC
            eVRqai9xZ2FJZkExbFN3ZUI0S0k4Z28KLS0tIEtBT1cwRm5pQlpiUnpEckhxV1l3
            VkZ5aWd4UHp3Z1ByczdSYnFydmx6YVUKXQ/9i509IixQTKY/dq9Q192hZixmQi0A
            MiTphOF04EEL1eRNYkUebP18ydTv9DeASeKnIndwpnDbNlThODDb5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-07-09T04:05:01Z"
    mac: ENC[AES256_GCM,data:VaaG1bVCoJ//T8qMXbT6U68JhRSiEXNbGbsPQXE4vtMSvlqCpQW1Sc9XROKS+yjiLWuCmmjUh5nAfEY5V11bbNWZAOp7HdVHxZmJvR97cguOpcByNPDeTu14m3kzKxuoLRMErLwYwHumWHTsbCt+k7bDRKAf52+6loPLltlNMG8=,iv:4Bnv4tqc1NxoqaFCWNQg/RvIq9G791xu+GIT6b4YGL8=,tag:CrO49+K1+iHxraB9UDETpw==,type:str]
    version: 3.13.2
