# infrastructure/external-secrets/cluster-secret-store.yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: op-secret-store
  spec:
    dependsOn:
      - name: external-secrets
    provider:
      onepasswordSDK:
        vault: the-white-lodge
        auth:
          serviceAccountSecretRef:
            name: op-token
            key: token
        cache:
          ttl: 5m
          maxSize: 100
