apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info
    namespace: synology-csi
stringData:
    client-info.yaml: ENC[AES256_GCM,data:Y3bsG2UIGhMkwIbKIo7HORhvVPhtLxBGRqReE/8+42W8crpYCt8fPgn1rvF+TnZhieM78DDFpugKPryH2C3e4BTiNPNFB1pSDVCNWGnwHUGj84DfnunzRTCAz5uTDSKM03CyPTb0opQddLVDaOCiY+6c+yJyRaibRQQ04lS5EnZ7JMVHT2GLafEpxJLfMPNKETGv0UvzY/0VRuAquA==,iv:rXwt19TitcbgnMtODxXAPvWj3ck3ylHxjes3rH/fwSo=,tag:HWYNaRPXBS6IzDcKdUme4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWmkyMnBDZmpDOUVLY0Nz
            SjVjKzhNNzRYbXo0YzlYTTZhQUd5K0JDMlNnCkNLKzRsNmVyTDNwWHBQdFFDT0Qz
            TCtFMUkyUHBwUU5qcG5CL29jR2hxYlEKLS0tIFN4ZGdQN1cvTjZ6TkhkakNsVEZo
            WmFZVVhGRkltQVZYQVJNbHBwQURSUzAKu+c6I1mH+nEnSsffZnoO5bcwhmRCKgc/
            2BEa6rRC+b6THvfu4B8EMqlUGtZfs7TvLaY8vieccCoH6LT1EMiTOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T03:06:30Z"
    mac: ENC[AES256_GCM,data:MC+aRIngENpMX61Kdw/AxkMvoZG5tTq+/8YlogLu7Yvd3GkJT4jGe3ksBiDB09MHSNfUIVOPIBzp0BZjJrG5Lf8t4ahS3NC1He2aq9bwQIUb3j31EAc9PWstshLmoA+wNshJG/wRgQLED1ulsyVZR9kWme9gxjRfdMnxAC2PaZg=,iv:WVPI5i5j+v9TTKyern9PS9eP5+5v22EVeqeXAHUAvok=,tag:XJ8L6180+tsuGEoQ0rCV1A==,type:str]
    version: 3.13.1
