apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info
    namespace: synology-csi
stringData:
    client-info.yaml: ENC[AES256_GCM,data:r2jZmvBG3YsAgge+J7G7GmfVm0zrj/cHs93xwbZzhbvVYeXJeeqVYDvSQDe72mJ9QNPQKfR7/v/6EuvMaH9Y3IYh1IsDAXInYWYb/uher1jwzadLI7bWztmNmWDPQ8gKw5oa/IT1Y3tzvlnEDwh5/ReEc24PfRO+Cc9RcGSqwZr1nWKZu498/JvIIOBqNjAi1np/C6Bu8nqqY9u3CyD7Wk7B1YCC67xXc8THYXrkR+nSjIislA3RI/japtHQDfkgQpNB3cgfkDzjiNxVDqpFVH/8IyQhrBq7Df0jdx12TfhfnmyDrtdxX+5KDqIQQwTeDE2LusoG9WwsVn8lcLd7ZARTPgDOgDwrfpTaagF+FCTz6BaQDyygFPLUv099KPa7i+AYst90Qlqi3fAHTtV6Ze4=,iv:aH37PSzpgarkjpKvjcjqnKOcY3ZV4T3cYkqxrF6NsGQ=,tag:+Jvr24VR9Y8OxyFAlgRL6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSEpNalhOcHBEYjBLMnJ2
            QWFRTGZQTXNsdWdZS2Vlb0lsSkxDditxZ25jCjgxMHNHOG5iZ25qLzZPNHVGbDN6
            LzBST1pIN3pxU29XTUpkV21aa0FQa3MKLS0tIDk5bjdKYTNQYVBBWXFWNS96ZFhY
            b1I3c0tsbEYzSWNtYnp0eERVTWZQNncKFXcEfBzoBJ06M4CK7Bkea6knbP8A4cdq
            Tscc+U41E8g8QZ09vFI/v3GyCU3Z3l2wqy2r1Mxd7ih4+P/E7lc3jA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-19T01:23:59Z"
    mac: ENC[AES256_GCM,data:Fso2AmEXs2MWusnvlfpha4O1XQ8bghcu2AQnn423PnTm+sy3W7UEywA5dOMd/WwztdIAiu6C9e7qMnDxIRMvkZrNQujqvD9RN31oVpLuaQ6gCm3F45zlqsLrTAdsl7+30gn41GR4oPAM6iUrVdlAO18oEkObzmY02VeloaEhYKw=,iv:cM39bqYA3y4QDkyZqy6FwhAuazrNyVpj5wrsHnk+IlY=,tag:RiDfX8wgu1zwW14Cf/x3lg==,type:str]
    version: 3.13.1
