apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info
    namespace: synology-csi
stringData:
    client-info.yaml: ENC[AES256_GCM,data:gqyaTnjzlk306fpo5uH76Kms4z3D3HPnrozFC3rjPejNZ0phL2F4vSmyu6Vg/7TgIZT+yzJLR2wjmS0BUpK8WJFz1msEW4VCgMrZzYj6CeL305/yIFphMH8C9zef3NUMtSYAzyHSlawW1U6V0E2F+0a/HhtFJd8Ba4km6iQbYKvUimVRFWP/48q+z0b1QmDgTTLGwmyi1dBAdDulVNp8DkhYi8zjxNr+hnY/ibbRH4V41A9RuR0xpWa1Z0Ah6fk+0XHwurMZbTRdohizT8Dk518eG+I03x9J2/06VVIKqDTksEqb9t3OeVfajxFGYKqYNleLXu8jlxyuO8oUdjEkJrGWgDyRCpinK4DsH0roSH9qLIiVfqUgHb3sNWwWVVjdg09U1DVRXXlssNRhzUnAlig=,iv:CIdIjJikp5SIaoSGlMaDZJ7Q3LS6HGY0FL2v49o3N9k=,tag:3aHvgjncgPPjPDMhKEVz6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR2xkVzJQbkhSbW9sNEdF
            eEpwek1XT0FMMmdGTEtabGdLTG8xWnRkajFVCjZzbjdvY05VYUljaVdYTCtTZ3VH
            RUFuYndzT0tZQVJsbjV5ei8rUGlUU28KLS0tIHp0ODJpRiswTldROFZGV3BMbzQw
            QTZveWU0NFl3elQ0ZXdDUGlBM0hQbXcKiEmPZgc+V+ESVSauMoCA1AgoFWZAKyzZ
            tWMnCfTK9ONNYaCRjLCwnrcVILguz2xbYtThjmwtE4c2MJgYmEIoew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T01:33:10Z"
    mac: ENC[AES256_GCM,data:uH7Seb7H8Est0feoH5HeQ4T389rNx4jdSn29DO3o1Bk/S60Pahe5RLvH+lUrR17Iykpgfp6KAlMC8TsnxVGp3n41BD+7lTeJLPvCF7LRWLAwBOIoJ2elxQSGQ+ggSwUyb7rK4IP+1szJn6oMvWCnsB+SyapO9eG4qm6id7rDI0g=,iv:VQAO3dzZE8KmB5ABso6vclACZbQXQXWZ0bf7ciA0BPQ=,tag:JYZ063AtI8lKEy/XlHLn5Q==,type:str]
    version: 3.13.1
