apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dagster
  namespace: data
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dagster.${cluster_domain}`)
      kind: Rule
      services:
        - name: dagster-dagster-webserver
          port: 80
