apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name:
spec:
  install:
    createNamespace: true
  interval: 1h
  chart:
    spec:
      chart:
      version:
      sourceRef:
        kind: HelmRepository
        name:
  values:
