vault_become_user: ENC[AES256_GCM,data:hRuvbw==,iv:AcmKIACnP2J4v0lofuh9Tbv8R/S4Abs5yOmucEDWQCo=,tag:FbePRnpzChxPlBOCTALUOw==,type:str]
vault_become_password: ENC[AES256_GCM,data:e5Q6ZGacIZFOVVMSiWTf5qfwUkBl37TrTocXI9slzn1hK2nbNVFgiMaVOKvBHw==,iv:VTc6+coOYjsNI+o3JTyS193APuRemWNcrTwYCkVc3uw=,tag:Wf7jqICM18AFAcvyo3u8YQ==,type:str]
oidc_client_id: ENC[AES256_GCM,data:RY9O/stXrjOvTpqz/vCH70pfmH5GsKWseKHhD9isJHxFkg9V6Bnopw==,iv:NeuU9xL4l3BKSmJjzKOZvi5ETvleDUW2uaUerZeDa94=,tag:ZuzhJpzQcYDrsiriq+QVXg==,type:str]
teleport:
    token: ENC[AES256_GCM,data:9YSIG3aJ7SMeObvdNtkhY01SIPy8y1dskwXSHLE/gsM=,iv:oYmblQVO7HmKZDcmgrGl0CY63hn8IdJ015XkfBFDquI=,tag:L1557nsn4Fjf34+NxyrplA==,type:str]
    ca_pin: ENC[AES256_GCM,data:8vgRzmkNui1JI8nAqV/8hTmFjIb4d9b7O6JlEK/k0Oy1PmjFvdo7UmcDEcJ2cY35vgG98I2MU6S+VCRPRS74g2qmbDaQPtU=,iv:xL07BcS4vktS+P6PB74aj1z4r6YwH/Fo7gmg9m+dfPU=,tag:OhDHUFp1YfSo1X4t2QMPyw==,type:str]
    proxy_server: ENC[AES256_GCM,data:ZCsUdd6i0gPZe7wgeXi4RSFf6mZgnixDCL4i4M8U,iv:WR2gpyX185D4zm8n/tN2sQHFGSCqTuDpfQEXGhlzdCk=,tag:z3kdyrKXPLkoRBQKj7EwIw==,type:str]
nas_ip_address: ENC[AES256_GCM,data:IidgTdTnGAdATp0Yxg==,iv:4blyek2B5aCzKRATPtIafo7rRzF6dcCwGGQsmZwEQVQ=,tag:PNtai9iKaC6x8wJN3Y6bXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRy8rcmFVT2Y5aHphSnY2
            U2lWNFkrVUN6MzZCN29RWlU3a1oyMjVGNTJJCnBZejdHd3Fxb0FhYnJ5T3pnWkg4
            bFYvNXdEd3JzcGFKb3J5K2oxUEh3cFUKLS0tIENnUWxVNEtjeDFXUXVEY3FnZW1F
            Y1Vma1U4WlpsQmlRanJwMEErZ3ZsOFkK37RyNbIHuBRM+oll8wGNvZlwQMma6B0X
            ke2buj9noPBAhBpnP6PWiaT+Y5lp61yZMK64UgMknqcjqh5MyVoUaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    lastmodified: "2026-06-28T00:17:37Z"
    mac: ENC[AES256_GCM,data:TkVMthfOjYpXr3AtXPx7E4ub5P2x6BwjwCygKgA2RaxPPkVGbYwNBaNqw506wCqoK4qUcNnog0ePSDuGzY3TVyW1DQCToMmSYhgbNCZf3SQlUVM+qQn+qQE1D1+uFv37nFiuIzV1FWEuX3P/JgLgOHz6RbrE7GcddezV1TcUk6o=,iv:cHkSlZ8TvkspneCQ/XHjkUG3duKbh+zVclkZvfFsRqU=,tag:QH6pl9GkHB5PBrB813IBqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
