apiVersion: v1
kind: Secret
metadata:
    name: metabase-secret
    namespace: data
stringData:
    MB_DB_USER: ENC[AES256_GCM,data:RGfEtzFMdFc=,iv:raeuTNBMqkItJwmGXn7tPfdP0Zpzc2ZwBit0jqlO1Nc=,tag:MDQNYWvIlU83sWGF8oJdHg==,type:str]
    MB_DB_PASS: ENC[AES256_GCM,data:5v+/4p29OsVK7lh7bwjVSAW+jYYxTji+BMkJ++vei8780coa+A==,iv:xSHteNe3FtmALGkIvWyVrEwFI6Aq18sY5se8yydH0M8=,tag:GtfddcGfSGeLiHZ3xwXe3g==,type:str]
    MB_ENCRYPTION_SECRET_KEY: ENC[AES256_GCM,data:AjrWomUNQv+HihjIFyT2Gm1WEvbSBFFkAbvTN+VEXtju0dsC4ZNY,iv:fS7mAY6N3w+kWWgVE6QmzDZZzdl+HQWqj/GsmDK1SoU=,tag:NENxLPtXBXICU2rtu83l9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUnI4WEhydjdHQmZNSkN2
            bUtXOTVkR2swWVRTNW8rakNPTHNYKy9WNkh3CmFBZVN2STlxdk1PM21rbE42dVZQ
            ZUpzbHQyd3Y0WHBxV205M09qUGt5VlkKLS0tIFFnaUtUck9wS0JMUzQ5eUVydUVT
            d1BJUGs3QUdOeVVlMWVLYnl6V1BjbU0K5u0375UHvoiBGBD55KBeN1apbFeURnaI
            P60xCDqFzn8O5iSHflsTgdwp8RJeHLToE9KGmxAlUlC142gPrAVEMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-08-14T00:05:41Z"
    mac: ENC[AES256_GCM,data:2Yqa4szdRsg9i7TptueuTLSh9v3q8cNrOcmNOiV4P9ixKtBwNJOq5jJpiPslHc36Czx6McjWrqtHAzn25V2xLDoyIeCDZmAx5NwHRQRx9j6beYWGtkmn/R/2bKquImIcSq5QIS1K3tFPJ+oIiqB3ftS/XNjHQnZfuZ2fjeGVHFo=,iv:3Mq/w0rY7hMAG0bYa8qAgkvEwpAOnL11Rp1VIZ2MRWM=,tag:MIYHDlYGlZiTBHh8lSsQfg==,type:str]
    version: 3.13.3
