apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik
  namespace: cnpg-apps
spec:
  name: authentik
  owner: authentik
  cluster:
    name: apps-cluster
  databaseReclaimPolicy: retain
