apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:AaiW,iv:1OS4JUreyQbrZZV0gh9VQS7iZYKjakForZpjerl3/vM=,tag:Gl7uqb8N1DOLtm/ar+oULA==,type:str]
    password: ENC[AES256_GCM,data:RixPaIHA+lgz4bw5EC5pfU80bbn+gGwQ/z7lpMv7hZgFKEqSZo+TXW6ZRQu0uMV9nw==,iv:RodnfkLyANxbU2L2h8exWcR48ubufYdSG6WMjLd0/AQ=,tag:OLQzkcqtjDuQIWecBMIt2A==,type:str]
kind: Secret
metadata:
    name: apps-credentials
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RGNqdytiODBOQnpLUVA2
            WDMwbVcxdnZqQ0R1bjY3cktwTkMreWFldGwwCk9nR29OMnZTN2t6K1dqQTRmeXg3
            ZklrUFUvRUpxU0UxWnBUcU91R1dkdEEKLS0tIEFMWjRMandHVjlaNVdScmVvVEJT
            enlwb1oyS1VlRHJ0eFRGcUp6K2pyQlUKx0PAoKefhyBxfBMIQcN27KM5ZJKVAECR
            nmvxj4crZ8U5ZJGgXGp8ClyO1jId9BKYSHsHwfslBZxgi7gj+1oGSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T04:45:56Z"
    mac: ENC[AES256_GCM,data:JxpOFrUHikFwU0iGVBwgT942keMOyISwXn8N4ffY8IU7t+hh14f5wvoqCXL6+wUXUa4Pvsy5ip4czFHa4mI8NN50hwS+6D6ntZQOX5JVM587WUcuazzyW2yjYc8vhgDJl0pbxVELNs0XaUeUPPHXbYm958xL0d6sBvxJ4lXUFMY=,iv:xwC5HuawWcuQC3ErUXcC8IlI0OcP8vrhhxxED+AQ3o8=,tag:1Z4/pgHEZl3BSzlK+8xb9w==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:di7vQDJEB8y8,iv:4P+seWMotvzlK4STPpe5KItYBffDgfSXZ9WxfxS3AK8=,tag:AsZ0zGvB+PIdtM7WJc9v0Q==,type:str]
    password: ENC[AES256_GCM,data:mvtlGDEbu9HjZ2XFdFKqAvNvxqoqdumvnhY3inLEnd+/fdln,iv:AX4vb6T1Ytm1SZiBxfHB0ggyeJnxM5oiJS0VCX81EiI=,tag:lOYYG6KoUTRL/rC243aUjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RGNqdytiODBOQnpLUVA2
            WDMwbVcxdnZqQ0R1bjY3cktwTkMreWFldGwwCk9nR29OMnZTN2t6K1dqQTRmeXg3
            ZklrUFUvRUpxU0UxWnBUcU91R1dkdEEKLS0tIEFMWjRMandHVjlaNVdScmVvVEJT
            enlwb1oyS1VlRHJ0eFRGcUp6K2pyQlUKx0PAoKefhyBxfBMIQcN27KM5ZJKVAECR
            nmvxj4crZ8U5ZJGgXGp8ClyO1jId9BKYSHsHwfslBZxgi7gj+1oGSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T04:45:56Z"
    mac: ENC[AES256_GCM,data:JxpOFrUHikFwU0iGVBwgT942keMOyISwXn8N4ffY8IU7t+hh14f5wvoqCXL6+wUXUa4Pvsy5ip4czFHa4mI8NN50hwS+6D6ntZQOX5JVM587WUcuazzyW2yjYc8vhgDJl0pbxVELNs0XaUeUPPHXbYm958xL0d6sBvxJ4lXUFMY=,iv:xwC5HuawWcuQC3ErUXcC8IlI0OcP8vrhhxxED+AQ3o8=,tag:1Z4/pgHEZl3BSzlK+8xb9w==,type:str]
    version: 3.13.1
