apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:9hcO,iv:U3uF7GtlAbBdheLmbBlhN7fhe9TtZQQle1vbUW0e8+c=,tag:SwwlhG6habA8MEXJmlvFKw==,type:str]
    password: ENC[AES256_GCM,data:mt1s/yrt5GyEPz4MWMnpPUJgEN6eK71Khrt4TU+t2YpFDtDks6m/2UTH1qjpm7NZZQ==,iv:YGj1CRFpFUxb0vW5ghHTXa0duak7wKD8nU1sP3Uafc4=,tag:Lde/zgEQh6+3C9oPmb6whw==,type:str]
kind: Secret
metadata:
    name: apps-credentials
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkc1dvMm4zNUdjWXhOSlZY
            eDc1emgxcmVMUlVhd3FDWjJ2QzNJbkM2eXk4CktwQnV5RFcvdGlUMWJRV3JVTDlq
            RkpuM1pCUi9XeHY5a1FnL3hXT1hyR28KLS0tIGxEdmRhM25JZVBzQXQ3c2RtMFVC
            emdHanI5OHoxK2VmWGhqaVJRS2NVcjQKgY2DparrcbqNtdZjnL7c+TU8+oA5N3GF
            LKRCIQs5Mi9puw8an/3Cv6U+NZwHr00ns08I1IsqOaL5RXgG1jC97g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-28T04:15:46Z"
    mac: ENC[AES256_GCM,data:Lh7Mo/52umZyLnLC8812gvmJvmYGEpBoXw8HWRGy3CGnt/8735QMRqIN9XUPAJSjESIy7Gi5KSazVpvvog1/Pc6nmaBKN/za7tuSLnWwcH1W0OXleqm7DiKhm1U/3FNO+i62HApLZoBC0p0Ez5sA4Qu8JQNpPlC7EZqHQUoV1o4=,iv:YGXopYaX0yAckdM1KYAjjgfiwUTag50nDUVSGHO62pw=,tag:clyHXW8Rf4YSjh5FiZgqOw==,type:str]
    version: 3.13.1
