apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: data
  name: mlflow-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-backup
  resources:
    requests:
      storage: 2Gi
