apiVersion: v1
kind: Secret
metadata:
    name: deduparr-secret
    namespace: media
stringData:
    DEDUPARR_RADARR_MOVIES_API_KEY: ENC[AES256_GCM,data:NHjz73GB784+bAmCZYAbbtab8pXHGi0HUtgyh3J4yDA=,iv:4lKquDHgdPu5PYTVqjppitMWJMJ3khyOIFpXdsqXYiA=,tag:JY9G4byxomo2agI7dHbaUw==,type:str]
    DEDUPARR_SONARR_SERIES_API_KEY: ENC[AES256_GCM,data:ZPcnX5RK96MyW/m3Y4iOi8y24GPY4WbQrtrpG46W7M8=,iv:c/LAVc4oqK3Wb56vCCjRk9N7ttm6xu1TFoCJ86jyUS4=,tag:a3bxV70yxlNnfDEjwzQlkw==,type:str]
    DATABASE_TYPE: ENC[AES256_GCM,data:ggKw66Yzpjc=,iv:uKgaF85J+20tECjPjV4dm84qcQP+sXl0cKC2OWHAeWg=,tag:G6HpiU6AeJ02MEPv4nSZcQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:7RyIJf4ZkYwfTzFZdHB15IRYeirC0MDUyRFgl5WV3T4KuYwU+cmFxfsKD4yonZ6tG8zkL2/GTyuG6PS/QiYeK/6o+L7d4ATQUch5LdToW5I9vtJ4kcACY3hf1+90AZR6nqyY3aC4OGxLq5wG0EvyCx1l9PItqu54EhhfoUikOAO65Yhchq36IMw=,iv:Q0/KkvdY3QAkhxlLcllX3mgrRB0IAKftevmzCuBCp7o=,tag:20u0UQwsPXtWA56WzY6rwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYnJoL0pBczFxaGlkWkc2
            SkZqdGNwaUg1QTNxUXJGTE51T3ZjRDF1RW1jClUzMnVPbzJBUWpxL1lDV0NpcXpp
            ZTJzejViZ3dEVDdhdW9mQUdSRnovWnMKLS0tIDlIMnBpcjFNNmlzQyttM3B1MFZr
            dEhkenZRcUpuUEdZclpqMmkwSzZ0UlkKY6FQu2aKeQZAinPvccWPs7PLpTbIE0Jl
            OtKiSi02UeJPwqPfpb/AVH7iNCi/xfdRKFoH+npx9jGuAYN9Hx7Ulg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T19:47:20Z"
    mac: ENC[AES256_GCM,data:av3OXMZmVhCPKGECN3ITD/+CyFRwyZm7CPhOdRd1qVkDLLPt6T5EgtcNDDXDsCUq0etmysn2I/MwxgXrHwikyK5++o9Kj2A7VNMOYXZgQqBeMHlZv0yKPcSBiGjBabO5Oo7UhfxDUJI+mNk97LHjYa7NJtFkC0OsFs68c+K7PAI=,iv:Go7GjzOOixASAfWV32UZMAr6OVUU+xyA6yliwK7z0BA=,tag:QKTmeIoYvCE1IwX4+qyHHA==,type:str]
    version: 3.13.1
