apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: calibre
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`calibre.${cluster_domain}`)
      kind: Rule
      services:
        - name: lidarr
          port: 8181
