apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: media
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:EX1pAIYRTDcAmEiPRphEQX71WzgiAIbfVMaqSg2Ky+w=,iv:rcMfW2bWNeHcMylVuuksN0YFtanS/+Hew85/EXeem+w=,tag:A+8vEWY5WuWUGYWMJiq4qg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:pieRE0AwTEjAnU5tGmXC6yF4nQAdTfbHjiSVjQ1o9ME=,iv:J77dFkuYWtqSbj04PyYxUMiFnRMVyV7JWDzjn7g+Gek=,tag:B16zi6kIwmaG8qU5QZrz0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbi9FaVg2dDROWlcxZlcx
            cnJMSDd0a3UyM0kvOWd4RVptcjhTSFlaYkg0ClNpME9ZejBEbnNBZTI5OTFIMTZm
            dTJBM1pmNzVIbDNQeDV1c0pFTXM3VEEKLS0tIHZva3NIQis5QTk1TGZJcWI1d2ZK
            dWhJU1dpTXBKZHBMcmlJK1RXU0U0eWsKVPfjueM61xMtERIRn+lYFkH45plBLIPC
            rK060upO0BLtKBkmiy2SwRHLhVK9c3V4tgPyt1NjDBVVleua6Ct5hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19azmnl8ee2f4r95jnwvr47uhllf33eq66dfc3vuxezq7k5vwqgfsyrdv8n
    encrypted_regex: ^(data|stringData|spec)$
    lastmodified: "2026-06-14T11:23:36Z"
    mac: ENC[AES256_GCM,data:FnquC/NdrHi1nJZDAuECcubPanVQS8LUK3uzLCHoC2Twr/bc0pvNvQBJw14JvOAQE/TACDoFNIZYI7/G6m7v8VJMBlbrWn78ap9AIGS/viKL/LRUZ5wUveg5RpGfwqTELTcqoY06kh1juZMMQqbdlhnLb1ecKdDUf4cexmzb71g=,iv:31SjOQd2DxlpTnVyyxxj31mNlxJIGVZwZCDtALynucI=,tag:glIgAneGaZ9cAXd88K1i1w==,type:str]
    version: 3.13.1
