apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-ingress
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`radarr.theblacklodge.dev`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
